### ISSUE TITLE
Table - Allow pinned styling from theme in addition to background prop

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1121]
Currently, to add background treatments to pinned header, footer, column we have to specify that treatment in the background prop for each instance. --> Allow to set in theme.

**Comment by taysea** [comment]
After some exploration, it seems what is happening is:
- If only `background.pinned` is defined in props, then the `mergedProps` of `TableCell.js` is not properly stripping out the background color and is placing `pinned` underneath both header and footer. As soon as `header` or `footer` is defined background prop, this issue is resolved
    - Conclusion: `normalizeProp` in `DataTable.js` is not sifting out `pinned` properly when `background.header` and `background.footer` are not defined

    ```jsx
    const normalizeProp = (prop, context) => {
      if (prop) {
        if (prop[context]) return prop[context];
        if (contexts.some(c => prop[c])) return undefined;

        ** when background.header and background.footer are not defined,
        then we are just returning the background prop which contains the
        pinned stuff
        return prop;
      }
      return undefined;
    };
    ```
