### ISSUE TITLE
Loading - problem statement

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1287]
Consolidate the exploration research down to a problem statement to enable iteration.

**Comment by vavalos5** [comment]
Matt came up with the problem statement which can be found below:

"As a Tech Professional and user of HPE as-a-service products, I need to execute tasks, gather information, configure new jobs, etc. in an effective, productive, and confident manner. Often, I have many people depending on me for important and time-sensitive tasks. Scenarios where I need to be productive and deliver results sooner rather than later, but am dependent on systems or processes for which I am not in control, my perception will always be that things are taking too long and might even be uncomfortable by not being able to directly affect my outcomes. In these scenarios, I need to feel like I am productive, confident, and in control."
