### ISSUE TITLE
Design System + HPE Compliance 

### ISSUE THREAD

**Issue by karatechops** [grommet/hpe-design-system#1290]
Presenting Design System website user journey to the web compliance team on 12/02/20. Completion of this task will result in the website migrating from design-system.hpe.design to design.hpe.com. As a result of this change, a 301 permanent redirect will need to be put in place from the old URL to the new.

**Comment by MikeWalrath** [comment]
1. Complete the form https://compliance.hpecorp.net/dns/domain_request?mode=wizard
2. Provide the zone file from the current Google DNS, so that we can create it on our DNS name servers.
3. Once we create it on our DNS name servers, we will require you to update it, and we will provide you with the name servers.  Once updated, test to ensure it is functioning appropriately.
4. Unlock and provide the authorization code.

**Comment by ericsoderberghp** [comment]
sub-issues completed
