### ISSUE TITLE
Implement bold cells in Figma

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1293]
Currently in Figma, we don't offer bold cells like how we have in the DS. These cells are for unique identifiers and interactive text.

- [x] Bold cells for Unique ID's + interactive Text (include each interactive state)
- [x] Bold cells for numerical values for Unique IDs (include each interactive state)

**Comment by vavalos5** [comment]
Figma file: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A13974

**Comment by halocline** [comment]
@vavalos5 I left a question related to what we name these cells in Figma (I don't know enough about the implementation, but wondering if we should be thinking of these as "Identifier Cells" and "Action Cells" as opposed to "Cell Bold"? Trying to lead with how they are to be used/applied rather than the treatment to be applied.

**Comment by vavalos5** [comment]
Just awaiting Matt's final 👀
