### ISSUE TITLE
Skeleton components approach - Loading Behavior

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#1318]
Ideate on how to approach skeleton content. Should they be templates with guidance? Should they be separate components? Should they be built into existing components?

- [ ] articulate a few options with pros and cons of each
- [ ] decide on which approach to take
- [ ] create new issues for next steps

**Comment by taysea** [comment]
Seems like providing an example with guidance to start would be a good starting point. Noticing a good use case for this is the Financial Services Dashboard where multiple cards are loading data on the first render (showing 3 spinners total on the page at once, one within each card). Given that the loading of data is managed by each card independently in state, it seems the caller could leverage this same variable and instead of displaying a spinner would render a skeleton version of the card in the meantime. We could provide an example and guidance of how to build the "skeleton version" of the card.

**Comment by ericsoderberghp** [comment]
We should update https://design-system.hpe.design/components/spinner to include guidance to not have multiple spinners on the page at the same time.
