### ISSUE TITLE
Update Headings and Wizard Figma Files to match the Theme 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1332]
Currently we have a discrepancy within Figma and the theme. We will need to conduct and audit and ensure they are aligned 
![image](https://user-images.githubusercontent.com/17712467/102552729-e8292680-407e-11eb-8f3c-02532b8df4c3.png)

**Comment by ericsoderberghp** [comment]
> Is this referring to the color usage on the headings or is text sizes too?

I think this came up just for colors, but it wouldn't hurt to verify that the sizes are aligned while we're there.

**Comment by vavalos5** [comment]
I changed the typography colors for: light background, light background - contrast, dark background and dark background - contrast to match the theme at this time. No other changes have been made to headings until we discuss whether we want to go with `text-strong` or `text` for headings.

**Comment by vavalos5** [comment]
including what I posted on Slack after reviwing with Matt:

"Upon reviewing the theme and Figma with Matt, we noticed that the theme is using the default `text `color for all headings but Figma designs are showing `text-strong `( in table, form, wizard, accordion and layer). We both agreed that we never specified whether the header’s color is `text-strong` or `text` and really comes down to aesthetics. I do believe `text-strong` gives a better hierarchal appeal.

Is this something we’d like to discuss as a team to conclude which color we want to go with before making any changes to the theme or Figma? "

**Comment by MikeKingdom** [comment]
When we tried the design system theme with Quake, it was quickly noted by folks that the headings didn't seem very readable and we overly muted looking. We ended up going with text-strong there.

I'd vote for text-strong

**Comment by vavalos5** [comment]
I've created a Figma file [here](https://www.figma.com/file/P3jh0GrT8ZI7qNiRCpSX5g/Heading-Examples?node-id=0%3A1) to show some misalignments to view them side-by-side.

**Comment by vavalos5** [comment]
Examples have been readjusted so they're more similar and easier to compare.

**Comment by vavalos5** [comment]
Leaving this in review over the weekend in case we get anyone on the the slack channel who is opposed to the `text-strong `announcement.

**Comment by vavalos5** [comment]
I came across two articles that talks about how #black should be AVOIDED over #white background as it can cause eye strain when users read the text over an extended period of time for people are photophobic, have astigmatism, dyslexic. This disparity in color brightness creates intense light levels that overstimulate the eyes when reading text and causes the eyes to work harder to adapt to the brightness.
[https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/#:~:text=High%20Contrast%20for%20Accessibility,text%20on%20a%20black%20background.&text=For%20normal%2Dsighted%20users%2C%20stick,black%20to%20prevent%20eye%20strain.](url)

also, this % is a big # to pay attention to.
A survey found that “58 percent of adults in the U.S.” have experienced eye strain from working on computers. 


not so much accessibility but readability

will continue to do research on whether it's specifically for large bodies of text and whether it matters fo headings.

**Comment by vavalos5** [comment]
"Readability is one of the more important aspects of Web design usability. Readable text affects how users process the information in the content. Poor readability scares readers away from the content. On the other hand, done correctly, readability allows users to efficiently read and take in the information in the text. You want users to be able to read your content and absorb it easily."

"Black text looks great on iOS. Dark gray text looks better on desktop browsers, especially on Windows because of the different anti-aliasing algorithms."
[https://www.joelonsoftware.com/2007/06/12/font-smoothing-anti-aliasing-and-sub-pixel-rendering/](url)


"Reading black aliased text rendered in a web-safe font on a white background made my eyes tired, but not sore, after 4 hours. Reading black anti-aliased text (non-web-safe font) of the same size on the same background and on the same screen, same topic, same line lengths and same interline spacing, made my eyes tired in 8 minutes, made me feeling dizzy in 42 minutes, my eyes became sore in 1 hour and 3 minutes, and my speed of reading was about 20% slower."[https://annystudio.com/try/sharp-text/](url)

"Pure black text on white backgrounds can cause eye strain when users read the text over an extended period. White has 100% color brightness, and black has 0% color brightness. Such a disparity in color brightness creates intense light levels that overstimulate the eyes when reading text. This causes the eyes to work harder to adapt to the brightness."

"Pure black isn’t harmful to all users. Low vision users, who are sight impaired but not blind, tend to read text better with pure black text or white text on a black background. When designing for them, you may need to use black for an accessibility mode. For normal-sighted users, stick with dark gray over black to prevent eye strain."[https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/](url)


"There’s a reason the text you’re reading now is not pure black (#000000), and the background is not pure white (#FFFFFF). It’s because many dyslexic users are sensitive to the brightness the high contrast colors cause. This can cause the words to swirl or blur together "
https://where.kevin-marks.com/textsamples.html

"When you put pure black next to a set of meticulously picked colors, the black overpowers everything else. It stands out because it’s not natural. All of the “black” everyday objects around you have some amount of light bouncing off of them, which means they aren’t black, they’re dark gray. And that light probably has a tint to it, so they’re not even dark gray, they’re colored-dark  #gray."
https://ianstormtaylor.com/design-tip-never-use-black/

---------------------------------------------------------------------------------------------------------------------------
It has been difficult finding anything that talked about black or grey headings specifically. 

From what I captured black text on white background does cause strain in the eyes and can be overpowering. But, that's only for large paragraphs of text. I'm back to being in the middle of which color to go with. Headings are headings and don't think they'd impair readability if the text stays `text-strong`. Since we use `text` for bodies of text, we shouldn't come across readability issues. The goal is to make sure that our designs meet the minimum color-contrast ratio for normal and large text on a background, which we do comply.

However, I did notice that Carbon and Material use the same color for their headings and paragraphs. The difference is that their headings are of course larger in size and bold giving the headings the illusion that they are "black".

Thoughts?? 🤔

**Comment by vavalos5** [comment]
Per this mornings standup, we have concluded to stick with `text-strong` for our headings. Figma file has been updated and aligned with theme. Changes to the other text colors have also been updated. 

https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/HPE-Typography-Styles?node-id=0%3A1

Wizard Figma file is aligned with theme:
https://www.figma.com/file/GEhgYzx3b8MejBjg9gAxyA/Wizarding?node-id=71%3A22
