### ISSUE TITLE
Filtering chips styling and state

### ISSUE THREAD

**Issue by rajasekar-ramasamy** [grommet/hpe-design-system#1414]
Currently, we don't have a Figma component for Filtering Chips and states of Chips

**Comment by ericsoderberghp** [comment]
Can you include links to any Figma designs where this is being shown?

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp https://www.figma.com/file/EA0OZFdocKVcQ55c7Jainb/HPE-Filter-Templates?node-id=671%3A11067

**Comment by MikeWalrath** [comment]
@rajasekar-ramasamy this was something that Greg worked on quite a bit. I don't remember all of the specifics but did look into the what it would take to create chips. https://www.figma.com/file/EA0OZFdocKVcQ55c7Jainb/HPE-Filter-Templates?node-id=1%3A3741

However because of the added styling we didn't believe that it was necessary add a specific "chip" we could reuse the styling and functionality of button with icon. Is there a use case that isn't being met with the existing designs? 
![image](https://user-images.githubusercontent.com/17712467/108745338-2ff18180-74f8-11eb-8af5-f76c5fdb12d6.png)

**Comment by ericsoderberghp** [comment]
I'm not seeing any filter chips on that design. I'm guessing that's where the chips would go. I was looking for an example of chips in use today somewhere.

**Comment by britt6612** [comment]
Per discussion, we removed the chips styling example in the design system.
Will close the issue for now until further discussion around design.
