### ISSUE TITLE
Form - readonly inputs

### ISSUE THREAD

**Issue by rajasekar-ramasamy** [grommet/hpe-design-system#1419]
`readonly` is a valid DOM attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly which indicates that the user can see the value but cannot change it. This issue is to create designs showing what the various input components would look like when `readonly`: TextInput, TextArea, MaskedInput, CheckBoxGroup, RadioButtonGroup, Select, RangeInput, DateInput. `readonly` components do not participate in validation, so we don't need to show any error states. The initial proposal is to just remove the border from the input.\

## Deliverables

- [x] document research + use case gathering [time box to half a day] for TextInput, MaskedInput and Select
- [x] 2-3 design ideations
- [ ] review with the team
- [ ] update grommet/grommet-theme-hpe as needed, publish to their repositories

During standup, we discussed focusing on TextInput, Select and MaskedInput first and figure out whether CheckBoxGroup, RadioButtonGroup, RangeInput and DateInput requite different treatments/more research.

**Comment by halocline** [comment]
Clarifying question: "just remove the border from the input" = remove the border from the FormField? If so, it makes sense in my mental image.

**Comment by ericsoderberghp** [comment]
These borders:

![Screen Shot 2021-03-01 at 3 00 01 PM](https://user-images.githubusercontent.com/11637956/109570388-ce548880-7a9e-11eb-8877-337c1a6f5eca.png)

**Comment by vavalos5** [comment]
Will we still be going with the designs i've created here: https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=3360%3A1169

**Comment by vavalos5** [comment]
Another use case that showed up can be found in this file: https://www.figma.com/file/fhyL55xFBwzX1G9fx72Ihu/Design-System-Questionnaires?node-id=2%3A3
![Screen Shot 2021-08-11 at 1 13 03 PM](https://user-images.githubusercontent.com/62117454/129096728-21249641-59e2-4b9f-aae5-bc0ef18273db.png)

**Comment by bahriaditi** [comment]
Adding another use case, that came up from the CCS team during Office Hours. Define read-only and disabled - for ex: can we have an input value that is not editable (i.e. when the user is restricted on what they can edit). At the DOM level, there are specific attributes - read only vs. disabled. But then at the conceptual level these could feel the same? 

In terms of accessibility, something to consider: A readonly element is just not editable, but gets sent when the according form submits. A disabled element isn't editable and isn't sent on submit. Another difference is that readonly elements can be focused (and getting focused when "tabbing" through a form) while disabled elements can't.

**More resources:**
http://g.recordit.co/gTHdMSaFdF.gif
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly#attribute_interactions

<img width="594" alt="Screen Shot 2021-11-03 at 10 34 06 AM" src="https://user-images.githubusercontent.com/87677275/140162175-1980b251-ab1b-41cc-83d3-fd5761d05489.png">

**Comment by halocline** [comment]
Requested again in Office Hours on 3/3/2022

Follow up with @Keeth-HPe , Chandan, and @rajasekar-ramasamy when this work is completed.

**Comment by halocline** [comment]
Request initiated from mahanthi.arun-kumar on CCS team.

Dependent on definition from https://github.com/grommet/hpe-design-system/issues/1419

Considerations:
- Styling when within a FormField
- Styling when stand alone (needed?)
- When within a FormField:
  - Should FormField accept a `readOnly` prop?
  - If so, prevent `readonly` from leaking into the DOM on the FormField div
  - How to handle if `readOnly` prop is specified, but child is an input other than TextInput or TextArea? (`<input />` and `<textArea />` are only valid form elements)


- [ ] Please contact mahanthi.arun-kumar on CCS team when this issue has been closed.

**Comment by KennyAtHPE** [comment]
Current designs for a read-only state we have for the new TextInput component. This was designed using this [reference](https://design-system.hpe.design/components/namevaluelist?q=read%20only#name-value-pair-as-a-read-only-display-for-text-inputs)


![image](https://user-images.githubusercontent.com/86075038/173003812-67a8a654-ce1d-4da9-8641-d85ea1fcedb5.png)
We received a suggestion from Greg to include a different colored background than the default light/dark background

![image](https://user-images.githubusercontent.com/86075038/173003710-4f03a4f0-e454-4ea2-9a81-f95fb6f1fd37.png)

Another question is whether or not we should have any left padding for the value

**Comment by taysea** [comment]
Slack question related to readonly: https://hpe.slack.com/archives/C04LMJWQT/p1669849608443059

**Comment by vavalos5** [comment]
I've done some reseach on text-inputs, masked-inputs (couldn't find any since it's similar to text-inputs) and select inputs and have documented research. Please see 3 options of each input in this [figma file. ](https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=5689%3A2518&t=2uj2t2q4nyO6NHQn-1)@ericsoderberghp @KennyAtHPE @jcfilben @SOjaHPE. Lmk your thoughts. I've also included some questions I ran into along the way.

**Comment by vavalos5** [comment]
Copy and pasting Eric's comments on the designs:

Some initial reactions ...
- Options 1 and 2 feel the most like they are "read only" to me because they are somewhat similar to NameValuePair. They are just text.
- Option 1 immersed in other form fields seems slightly odd, due to the alignment, but I could live with it.
- Option 2 feels good to me when immersed in other form fields.
- If all or most fields are read only, I probably gravitate towards Option 1.
- If most form fields are not read only, I probably gravitate towards Option 2.
- Option 3 actually looks visually the cleanest to me, when mixed in with other form fields. But, I'm also left wondering what the background color means. It is verging a bit towards styling we use for an aside or help panel, which isn't the right concept here.
- All that to say, I have a slight preference for Option 2.

I received feedback from Jessica too. I'd love to get the team's perspective on this. I'm creating a follow up ticket to share with team and gather insight on next steps. Follow up Ticket: #3056
