### ISSUE TITLE
Research on how to support contextual help

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1481]
Within Figma there isnt a distinction between info validation vs error validation. It would be nice to add a variant to Figma component to include info validation. 
https://hpe.slack.com/archives/C016NNY4TA9/p1614379506047500?thread_ts=1614367643.046400&cid=C016NNY4TA9

**Comment by vavalos5** [comment]
What is info validation? If there is an instruction a user needs to perform, it would be best to include that into the instructions at the top of the form. Error validation is just a way to convey a message to a user that the input hasn't been addressed

**Comment by ericsoderberghp** [comment]
Info validation would be a message associated with the value entered/selected but not inhibiting submittal of the form. For example, if there are some restrictions or costs associated with a shipping address, that could be annotated with an informational message.

**Comment by vavalos5** [comment]
<img width="831" alt="Screen Shot 2021-04-16 at 3 20 28 PM" src="https://user-images.githubusercontent.com/62117454/115089583-5a900300-9ec7-11eb-9df5-a90c3da2fba9.png">

I'm not sure if removing the 'circle-alert' icon makes the validation instance as prominent as it is with it. I created some other potential examples.

**Comment by ericsoderberghp** [comment]
> I'm not sure if removing the 'circle-alert' icon makes the validation instance as prominent as it is with it. I created some other potential examples. The last 2 examples are showing validation with our swatches red. IF i use our critical color, it is not accessible at 14px. text. The question is, do we really want to remove the 'circle-alert' icon?

I think whatever approach we take should work across all form input components, such as Select, TextArea, FileInput, DateInput, etc. Since some of these already have a control icon on the right side, I don't think we should include a validation error icon on the right side at the same time.

As indicated, we should not be using red text, for accessibility reasons.

I thought the initial issue was to remove the icon only for "info"rmational messages, not for validation errors.

**Comment by vavalos5** [comment]
Thank you @halocline for this clarification. After looking at the use case, it seems as though they're requiring the user to turn on the Multi-Factor Authentication toggle. If we are saying that an "info" validation only provides informative information and does not interfere the user from moving forward to the next step, then the text provided underneath the use case does not seem correct. I'm awaiting a response from Derek and/or Diane to further understand what they're trying to achieve.

**Comment by MikeWalrath** [comment]
Adding Figma link from the CCS use case https://www.figma.com/file/haSQhFGJH6yrkhMda4CP7p/HPE-GreenLake-v0.11-(Post-June)?node-id=2629%3A28212

**Comment by vavalos5** [comment]
I’ve done a little bit of research on displaying information below a component that provides additional info. about it. However, i’m having a little bit of a hard time differentiating it from descriptive text.

CCS’s use cases have been using a string of text below a disabled component. So, I was trying to figure out how that would work if the component isn’t interactive. Due to the disabled attribute on the component, the component is not accessible and wouldn’t make sense to have descriptive text that would not be read on a screen reader. I think in this case, the text should not be below the component, but rather above somewhere where the screen reader could read it.

I created 2 examples of how we’d treat info-validation when a component is not disabled and another for the disabled use case.

https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/HPE-Text-Input-Component?node-id=3623%3A1402

**Comment by vavalos5** [comment]
Going to move to parking lot for now until I chat with Eric on how to move forward

**Comment by vavalos5** [comment]
Had a convo with a few folks such as Gina, Ian from Ezmerald, Greg and Eric about this same topic. It looks like the they felt that this information should be styled similar to notifications. However, Eric and I both agreed that it shouldn't. Also, we feel that it shouldn’t be referred to as “info-validation” but more or so “contextual help”.

How might we show that and give guidance? The world has yet to know... TBD 🤔

**Comment by vavalos5** [comment]
I think it would be good for us to step back, empathize, and understand exactly what we're trying to solve for. Let's go back and gather research on how others might be doing this and become knowledgeable in the topic. 

Here is a conversation where this ticket was last left at: https://hpe.slack.com/archives/GPPLUK6LR/p1620942768313500

To do:

- [ ] Understand problem by gathering use cases from CCS (if any others), GLC, Nimble, Financial Services, etc..
- [ ] Gather research on topic, how other companies/frameworks are styling and showing contextual help on disabled and non-disabled states 
- [ ] Create a list of questions you might want to look into along the way
- [ ] Create a problem statement
- [ ]

**Comment by vavalos5** [comment]
@Keeth-HPe I came across this Smashing Magazine article that might be useful for your research: https://www.smashingmagazine.com/2011/11/extensive-guide-web-form-usability/

**Comment by Keeth-HPe** [comment]
> @Keeth-HPe I came across this Smashing Magazine article that might be useful for your research: https://www.smashingmagazine.com/2011/11/extensive-guide-web-form-usability/

Awesome ! Thank you

**Comment by Keeth-HPe** [comment]
https://www.figma.com/file/9TbVvlBaU1z8aqDNd7LDNk/Research-on-how-to-support-contextual-help-1481?node-id=0%3A1

Research has been finalised.
