### ISSUE TITLE
Add guidance on max width of a table

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1504]
## Deliverables
- [x] determine updated guidance
- [ ] update the design system site (from the last comment here)

Based on the number of columns/content what is the guidance on the max width of a table. 
![image](https://user-images.githubusercontent.com/17712467/112184735-1ad64400-8bc5-11eb-82ec-e7f36f37343c.png)

**Comment by ericsoderberghp** [comment]
See also #1475

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp @MikeWalrath @vavalos5 here's my recommendation for max-width for table
https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=4686%3A141052

**Comment by vavalos5** [comment]
@rajasekar-ramasamy Was this ready for a review? If so, can you move to "In Review" to let @ericsoderberghp know that it's ready for review. Thanks!

**Comment by vavalos5** [comment]
Moving to "in review" for Raja as it's ready for review

**Comment by ericsoderberghp** [comment]
From the Figma content and additional conversations, I'd like to summarize this as:
- Use the right set of columns. Don't add more just because the data is there. Don't remove frequently used ones, requiring the user to drill in and out frequently to compare rows.
- To support readability, make tables as wide as they need to be and no bigger.
- Limit the whitespace on individual columns by using `size` for table columns.
- When the table has the potential to be wider than the screen
  - use `pin` to anchor the primary column, to provide row context
  - use horizontal scrolling within the table, not at the level of the entire page
- When the table has the potential to be narrower than it's layout context
  - align it horizontally with the rest of it's layout context, typically aligned to the start of the content, as opposed to stretched
  - also align any header above the table, including heading, search, filter, actions, in the same way. This prevents an orphaned actions menu/button out to the right away from the table. But, don't force the header above the table to align its width to the table, as that might compress the contents of the header too much.
