### ISSUE TITLE
Right justified numeric content that is truncated on the right 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1515]
Is truncation on the right side the correct approach for right justified numeric data?
![image](https://user-images.githubusercontent.com/17712467/113029120-4ae39100-9149-11eb-861f-2e9a242d5764.png)

**Comment by ericsoderberghp** [comment]
Should take a look at this from a design exploration perspective and create some guidance as necessary.

**Comment by vavalos5** [comment]
In the Table Figma file, I had written that numerical values should always be visible and not truncated so they're always accessible/visible.

<img width="844" alt="Screen Shot 2021-04-13 at 1 37 45 PM" src="https://user-images.githubusercontent.com/62117454/114617922-96279480-9c5d-11eb-9d5e-d01f7c53bc50.png">

https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A12752

Do we still want to explore a different option?

**Comment by ericsoderberghp** [comment]
I think the key in this example is whether the content is a number that probably has units associated with it vs. a more random identifier, such as a purchase order number.

**Comment by vavalos5** [comment]
I created an example w/ truncated numerical values. Mike, Matt and I had a discussion and felt that we should include some text if truncation on numerical text is absolutely a must. Screen shot below w/ details. Our suggestions are that they continue to be truncated on the right for consistency and to use a tooltip. Also, since in English we read left to right, it makes the most sense. There aren't any tables we've seen with truncation on the left.
<img width="744" alt="Screen Shot 2021-04-14 at 2 28 04 PM" src="https://user-images.githubusercontent.com/62117454/114790342-76659e80-9d39-11eb-8017-57c66e73c6f7.png">

**Comment by vavalos5** [comment]
![Screen Shot 2021-04-15 at 11 26 07 AM](https://user-images.githubusercontent.com/62117454/114924586-01e73a00-9de3-11eb-8dbb-bacbd9535553.png)
Updated file w/ default tooltip

**Comment by vavalos5** [comment]
Eric confirmed this is good. 

Figma file could be found here: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A12752
