### ISSUE TITLE
Feedback/questions on Pagination 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#1549]
We received the below questions regarding the Table/Pagination example. Adding the design tag for now. We can update the example or the guidance based on the design decisions. 

Is there any scrolling?  Where is it? 
Is the pagination footer sticky or is it part of the table scroll region? 
Are the headers sticky? 
Do you size the page so that an entire page is visible at once?

**Comment by vavalos5** [comment]
Some of these questions are answered in the Table Figma file which could be found here: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table?node-id=2390%3A12930

Since these are table specific, they pertain in the Table Figma file. However, we can include some content in the pagination file linking it to the Figma file.

I'm not sure I understand the question: "are the headers sticky?" Is that referring to table headers? If so, that doesn't seem to pertain to pagination.

Is there more clarification on "do you size the page so that an entire page is visible at once?"

**Comment by MikeWalrath** [comment]
Will be adding guidance from table Figma file and possibly adding an example with sticky header/pagination.
