### ISSUE TITLE
Update the toolbar button

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#1738]
We made a recent change to the ordering of items button which used to be a pencil tool. Need to update to the wrench tool

**Comment by vavalos5** [comment]
Reference from the Table Customization link on the DS site: https://design-system.hpe.design/templates/table-customization

**Comment by vavalos5** [comment]
https://www.figma.com/file/TonE8uQ33e5QJRPknZx36q/Ordering-Of-Items?node-id=33%3A12

**Comment by vavalos5** [comment]
Investigate why we decided to change from a pencil icon to a wrench.

Is it more identifiable? Let's try to have some reasoning behind that.

**Comment by ericsoderberghp** [comment]
I think it was because the pencil icon might be used to edit the content, such as a table row, or something else in some details right above the table. The pencil as "edit" wasn't clear that this was editing the columns of the table as opposed to the content inside the table.

**Comment by vavalos5** [comment]
Ah yes, that makes sense. I guess what I meant to say in this ticket is whether either of those icons are the best options to visually show what the button does. 🤪

**Comment by bahriaditi** [comment]
@vavalos5 @ericsoderberghp (cc @taysea) I think it makes sense to use an icon that visually represents 'configure' / 'settings' since it is altering the view of the table based on user preferences. The wrench icon is a good option, however the gear/ cog icon maybe a more clear and universal way to indicate that. If you agree, I can update the design file.

See mockup for reference:
<img width="1145" alt="Screen Shot 2021-07-26 at 4 01 33 PM" src="https://user-images.githubusercontent.com/87677275/127070149-5ec5fd16-9f4e-4e19-acc7-663ce62ec1ef.png">




------


**Related comments:** _(please let me know if I should create a separate issue about the toolbar button)_

- The [toolbar button](https://design-system.hpe.design/components/button#toolbar-button) border width should be 2px based on the [Figma design specs](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=681%3A5164).

- The hover and active state for the toolbar button are missing. See [Figma design specs](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=681%3A5164)

**Comment by taysea** [comment]
I am happy to go with the "Settings" icon of a gear. That had been @ericsoderberghp other suggestion when we were doing the rework. Maybe at some point we can run a mini user test to validate if the settings icon is indicative enough.

Re: toolbar button, I think we want the border to be 1px so it aligns with the TextInput styling to its left. Is this correct @vavalos5 ? If so, we should update Figma.

**Comment by vavalos5** [comment]
Ah yes! I'll make the changes to the toolbar button on Figma now. Thanks @taysea!

Agreed on the cog icon @bahriaditi. I think this is more commonly used and identifiable icon.

**Comment by vavalos5** [comment]
I've updated 😄 https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1
