### ISSUE TITLE
Respond to this design inquiry from Slack re: status in a menu

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#1769]
Slack thread: https://hpe.slack.com/archives/C04LMJWQT/p1628156259032300

Gautam S  3:37 AM
Hi team,
I am looking for some feedback on the application header that we are designing for server management applications. We are using a drop down menu to display a summary of statuses (of individual sub-systems). Along with displaying the status, they also act as links to pages that have additional details of the sub-system. This allows users to "follow-the-red" and fix/troubleshoot issues. A couple of specific questions I have:
We'd like users to know when one or more of the sub-systems changes state. We have used badges to convey there is are unread status change. The inspiration is from how Figma uses badges to inform users that updates are available. Is this OK?
In the list of sub-systems, should we display only "red" items to avoid adding cognitive load and the clutter? Or should we have the same ordered list of all the sub-systems so that users get a sense of the summary?
Should we add an additional breakpoint in between the responsive break points at medium and large to display labels alongside the icons when space is available?
Adding my Figma frame for more clarity on the questions.

**Comment by halocline** [comment]
I've made my best efforts to speak to Gautam's questions since he has re-inquired. Please review and correct any mis-guided statements I may have made.

https://hpe.slack.com/archives/C04LMJWQT/p1628760898071900?thread_ts=1628156259.032300&cid=C04LMJWQT

**Comment by vavalos5** [comment]
Thanks for being on this @halocline I'll set some time for @bahriaditi and I to take a look at the ask and follow up

**Comment by vavalos5** [comment]
Aditi and I have gotten together to answer Gautaum's questions. Below are our answers: 

Thank you for being so patient. @Aditi Bahri and I got together this morning to go through your questions.

Q1: Remove the blue notifications on the list items and give a high level overview on the icon itself using stack component to let user know how many items need attention (attack stack component link).

Q2: We felt that this is not a DS question and more of what is trying to be accomplished through the use case and user flow.

Q3: As a good practice, always use a11yText to be mindful of keyboard users and use tooltips for mouse users. No need to add another breakpoint.

One other thing we noticed was that the icons seemed to have been scaled making them look unproportioned on your header examples. Were they stretched when pulled from the assets library?

Lastly, the drop menu is that the text being used is incorrect for the list items. They seem to be using form and label text styling rather than default.

We hope this helps :slightly_smiling_face:

**Comment by bahriaditi** [comment]
> I've made my best efforts to speak to Gautam's questions since he has re-inquired. Please review and correct any mis-guided statements I may have made.
> 
> https://hpe.slack.com/archives/C04LMJWQT/p1628760898071900?thread_ts=1628156259.032300&cid=C04LMJWQT

@halocline thanks for responding to Gautam's question – your reply was spot on. Noting that this seems to have been resolved in the Slack thread, but we'll keep an eye out for any further questions.
