### ISSUE TITLE
Button Guidance — Should "Cancel" on Wizard be "Exit" instead?

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#1884]
Right now when you press "Cancel" on the wizard, a confirmation dialog opens asking if you want to truly cancel or if you'd like to continue with the wizard. This creates a slightly confusing experience where the affirmative action is cancel. Typically, we use "cancel" as the secondary action to the primary action of a modal. In Wizards, would it be more fitting to rename the "Cancel" button to "Exit" and then the confirmation modal can have a primary button that says "Exit Wizard" and a secondary (or default?) button that says "Cancel"?

- [x] Decide on guidance
- [x] Create a ticket to update site examples and guidance based on outcome

**Comment by bahriaditi** [comment]
@Keeth-HPe assigning you this ticket to work on next. Please let me know if you need more info or if anything is unclear. Thank you!

**Comment by CitizenFox** [comment]
I think the action of cancellation is tricky here because it remains ambiguous as to whether the user is:
A) Leaving the flow
B) Cancelling the action of leaving the flow

When it isn't immediately clear what cancellation does, I really like doing these two things:

- Provide a clear binary choice. For example, yes or no.
- Provide a secondary term that reaffirms the action. For example, stay or leave.

So we present users with choices that look like this:

Are you sure you want to exit the wizard?

- Yes, Leave
- No, Stay

Any thoughts?

**Comment by bahriaditi** [comment]
This helps a lot, @CitizenFox - Thank you! I'd love to put together a live mockup flow during our meeting later on to confirm this approach.
