### ISSUE TITLE
Buttons - Update border radius for S,M,L size variants in Figma to match site

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1899]
New variants created in Figma currently have the same border-radius = 4px. 

On the design system site, large button border-radius = 6px.

- [x] Connect with a developer to confirm this change in the Figma library
- [x] Make the updates in Figma

**Comment by Keeth-HPe** [comment]
✅Connected with developer and confirmed that  :
border-radius is 4px for all sizes..
Small button: line-height: 22px
Medium button: line-height: 24px
Large button: line-height: 28px

✅And the button components in Figma is as per these dimensions

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe! 
@vavalos5 tagging you so you can review :)

**Comment by vavalos5** [comment]
@Keeth-HPe I got a chance to look at your file. I adjusted the radius on the large buttons. 

One last thing that is needed on the small button is for the padding to be aligned with the design system site. The padding top and bottom are correct, but the padding on the left and right should be adjusted to 8px rather than the 10px that is on the Figma file. Can you please adjust ) I adjusted the first top left one.

After those changes, you can publish.

Almost there!

**Comment by Keeth-HPe** [comment]
@vavalos5  Thank you! I have adjusted the padding for the 's' buttons to 8px and published them too. 

And regarding radius of buttons, Brittany informed me that 4px is the radius for all button sizes as per grommet. Hence I did not change it, should we change the 'medium' size buttons too ?

**Comment by vavalos5** [comment]
Looks great @Keeth-HPe Good job! This ticket is good to close 🎉
