### ISSUE TITLE
Figma - Inviting Design System contributions

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#1991]
Came up during the Design System Office Hours:

What is the best way to invite contributions for use cases and designs from other designers outside of the Design System team?

- [x] Partner with Scott and Eric to brainstorm some ideas
- [ ] Explore Figma branching feature
-- Connect with Ephrem, Chris M. and Greg
- [ ] Explore "sandbox" or a waiting room to house ideas from other teams (design & dev)
- [x] What would this user flow look like for designers?
- [ ] Create a first draft of proposal that can be shared with the DS Council
- [ ] Get feedback from other stakeholders across the org

**Comment by KennyAtHPE** [comment]
Figma's new Branching feature allows designers outside of the DS team to contribute directly to DS Figma files. Essentially users can create branches of a file in which they can change whatever. Afterwards, the changes can be reviewed by the owners of the original final and if approved the changes can then be merged into the master file. Very similar to GitHub, but here's a quick overview video: https://www.youtube.com/watch?v=tbNCGEC2G1E

**Comment by bahriaditi** [comment]
I found 2 more helpful articles on the topic of creating a contribution model for design systems:
https://eightshapes.com/articles/why-contributions-matter.html#dss
https://medium.com/eightshapes-llc/defining-design-system-contributions-eb48e00e8898

**Comment by KennyAtHPE** [comment]
Some thoughts and recommendations:
1) First figure out where designers are interacting with the design system and then understand the current ways in how they can escalate issues and/or offer contributions. Some (not all!) examples:
a) DS site - Contains links to create issues on Github and to ask questions within the DS slack channel
b) Figma - Post comments directly on designs

2) Understanding the pain points when escalating issues or offering recommendations
a) Github - Non-intuitive to designers outside of the DS team. What labels to use? Who to assign to? When will I receive a response and should I follow up with someone?
b) Slack - Probably the current best way to contribute however only a small group of people are actively participating. Maybe designers aren't sure how to structure their questions and who to ask specifically?
c) Figma - No direct way for designers to ask questions or to contribute other than to comment however this lacks visibility and rarely happens unless specifically asked for

3) Based on this, here are some ways to approach this:
a) Emphasize feedback and contributions more heavily on the DS site and slack channel. Perhaps adding a comment section within each DS subpage for direct feedback and public visibility. 
b) Providing a point of contact rather than ambiguously mentioning the user to contact the "Design System team." This could be someone who helps point to the slack channel or shows the user how to create a ticket within the backlog. Additionally, this could be as simple as a list of everybody on the design team and their roles + best way to reach them.
c) Figma doc on how to contribute, raise issues, and provide recommendations. Add a part to the new Figma guide? Figma branching can be further explored (refer to comment above)
d) Create a journey map to further understand pain points and to gather suggestions directly from other designers. **I'd suggest getting in contact with Christopher Conetta from the research team since he's created journey maps for similar issues in the past.**
