### ISSUE TITLE
Skeleton loading - Guidance on when to use vs. spinner

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2004]
Teams have been asking for guidance on when to use the skeleton screen vs. a spinner.

Please create guidance on best practices, scenarios, guidance and use real live HPE use cases.

**Comment by vavalos5** [comment]
designs can be found here: https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/HPE-Loading-Indicator-Component?node-id=221%3A17108

**Comment by ericsoderberghp** [comment]
Currently, we don't have Skeleton loading anywhere in the design system site. I think we should at least include a rudimentary first pass at adding it, so that we have a bit of context in order to be able to provide guidance on when to use which.

See https://github.com/grommet/hpe-design-system/issues/2003

**Comment by jcfilben** [comment]
Closing, the Skeleton page in the design st=ystem site has guidance on when to use skeleton vs spinner. https://design-system.hpe.design/components/skeleton?q=skelet#when-not-to-use
