### ISSUE TITLE
Font issue in DSCC - specifically the character "i"

### ISSUE THREAD

**Issue by rajeshnaroth** [grommet/hpe-design-system#2080]
In windows OS, 'i' is becoming indistinguishable from 'l' because the dot gets merged with the body. Thus something like  "wait" reads as "walt". This is much more pronounced in smaller font sizes such as 14px

### Is this issue related to the design system core library or design system website?
design-system-core

### Expected Behavior

i should be distinct from l

### Actual Behavior

'i' is becoming indistinguishable from 'l' because the dot gets merged with the body.

### URL, screen shot, or CodeSandbox exhibiting the issue

<img width="1611" alt="Screen Shot 2021-11-18 at 1 20 05 PM" src="https://user-images.githubusercontent.com/18208175/142499223-75158c63-5129-4dbc-ae0b-15f14852f584.png">

<img width="1636" alt="Screen Shot 2021-11-18 at 1 19 03 PM" src="https://user-images.githubusercontent.com/18208175/142499292-9d1d6cba-3601-4b4b-a502-04c78973fff0.png">

When zoomed in, it looks ok. So it must be an antialiasing issue.
<img width="508" alt="Screen Shot 2021-11-18 at 1 20 34 PM" src="https://user-images.githubusercontent.com/18208175/142499352-098dbfb6-11f5-4aff-b929-58eeca1360dd.png">

### Steps to Reproduce

From a windows machine, any browser, log on to https://sso.common.cloud.hpe.com/ Font issue is present anywhere the size is around 14px.

### Your Environment

Windows OS

- Design System version:
- Grommet version:
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Any

**Comment by halocline** [comment]
Analysis from @samuelgoff: 
hey @gliss yes, by default Windows tends to render fonts with poorer anti-aliasing. Fortunately, there’s a way to ameliorate this: add a CSS rule to the root (html) like so:
```
html {
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
}
```

I don’t have access to the site this URL points to (probably requires VPN access), so I’m looking at ones that use similar styling in the header:
- If you apply this to the Design System site, you’ll notice the text in the header gets a little easier to read, but the logotype itself doesn’t, since it’s an SVG, which tends to render with better anti-aliasing under most conditions.
- On GLC, that secondary header row is more like 16px, but changing it to 14px reveals the issue with this particular weight of font at this particular size. However, if I apply those CSS rules to that block of text, it doesn’t change noticeably, because I see GLC already incorporates -webkit-font-smoothing: antialiased into the generated stylesheet, however the combination of styles I included above works on a larger range of systems (including windows)

The bottom line is this is a result of the design decisions made when this font was created, which also includes x-height. To me, the solution would be one or more of the following:
- add the above CSS styles if they’re not already being used
- choose a different `font-weight`. a lighter weight will render with better separation between the dot and body of the “i”
- use larger text. 14px is considered “hard to read” by modern standards. 16px is the new minimum, and 18px is considered much more comfortable as a minimum size.
- less ideal: if “Data Services Cloud Console” were converted into an SVG, this _might_ produce better results; you’d have to try it out to see
- far less ideal: choose a different font that’s designed for optimal readability at 14px

Sorry, but IMO this is not a bug, but a feature of the font + weight + size + all of the other design decisions that have come before this point :slightly_smiling_face:

**Comment by SOjaHPE** [comment]
@L0ZZI are there any update with your communications with the NZ font foundry regarding our MetricHPExs font face related to this bug?

**Comment by ericsoderberghp** [comment]
![image](https://user-images.githubusercontent.com/11637956/169870617-f20ea94a-618a-4bf5-9fc4-451b5efe03e0.png)

**Comment by samuelgoff** [comment]
hey @SOjaHPE & @ericsoderberghp, I did a pretty deep dive into the web font the foundry provided for our review, as well as a pretty detailed analysis of the 3 versions of our font that are currently in use throughout the organization. I want to make sure the result of all this work isn't hidden from view, inside a private Slack thread. Here's what it says:

I just completed a deep dive into the differences between the “new” test version of Metric (v1.002) you linked to the other day vs the MetricHPE version downloaded from Brand Central, and based upon what I’m seeing, the test version looks like a big step backward, with no advantage to switching to it. Perhaps this is intentionally hobbled for evaluation purposes (or the foundry separated out the glyphs into separate localizations), but I’m evaluating across every facet. Here are the issues I see with the test version:

- only 34 languages supported vs 93 in our current BrandCentral version
- only 69 glyphs included vs 453 in our current BrandCentral version
- only 1 OpenType feature (kern) included vs 8 in our current BrandCentral version

Regarding the separation of the dot on a lowercase “i” vs the body ([#2080](https://github.com/grommet/hpe-design-system/issues/2080)): On the Retina Display resolution of my M1 Max MacBook Pro, there is no measurable difference between the font versions in terms of how they render & anti-alias in a browser (Chrome). This is measured down to the individual pixel level, using the following steps:

- performed a screen grab of every weight of both versions of the font
- perfectly aligned one version over the other in Photoshop
- set the top layer mode to “difference”
- added an adjustment layer to boost anything brighter than pure black (which indicates no change)

![zoom-200%-antialiasing-vs-none](https://user-images.githubusercontent.com/2007084/169894629-b70b5792-ce73-469f-a864-ca5bcad7b459.png)
![no CSS anti-aliasing](https://user-images.githubusercontent.com/2007084/169894695-7473e778-c54a-48
![webkit font smoothing](https://user-images.githubusercontent.com/2007084/169894719-618d7201-56c6-4848-8022-d04be70e72f4.png)
a0-9150-7658eb48483f.png)
![text rendering auto](https://user-images.githubusercontent.com/2007084/169894745-ea4dcced-363c-401c-8e90-57229bb485e8.png)

The only thing that made a noticeable improvement (well beyond a measurable difference) was the additional lines of CSS I suggested at the outset of this discussion, specifically `-webkit-font-smoothing: antialiased`, though the inclusion of `text-rendering: auto` helps ensure better results across more browsers & versions.

See attached images, including one in which I zoomed in 200% & did a screen shot. This really shows off the difference the improved anti-aliasing makes (noticeably improved across all weights except perhaps black), at least on webkit browsers, on a Retina Display Mac. If we want to repeat this test on Windows, I could easily upload this test page to my Vercel account, so you (or anyone else) could try it and see if there’s any improvement in the font rendering with the new font version. However, even if we found an improvement in rendering for those users, we would need assurances from the foundry that the features that appear to have been stripped from this version would be present in the actual, licensed version — unless he now breaks those glyphs and characters out into separate localized versions of the font, which would also be made available to us. Otherwise, if this test font is any indication, it would represent a significant step backward.

Additionally, please note this “difference” image that shows how profound of an effect the anti-aliasing CSS rule has on the font rendering. I boosted the brightness 50% so the gray pixels are more obvious, but the point still stands: nearly every pixel in the font renders differently, and IMO much more clearly.

![anti-aliasing-changed-pixels](https://user-images.githubusercontent.com/2007084/169894778-5a80f619-788a-46f2-a97c-d83caa34e931.png)

For that reason, my original analysis & recommendations still hold:

> The bottom line is this is a result of the design decisions made when this font was created, which also includes x-height. To me, the solution would be one or more of the following:
> 
> * add the above CSS styles if they’re not already being used
> * choose a different `font-weight`. a lighter weight will render with better separation between the dot and body of the “i”
> * use larger text. 14px is considered “hard to read” by modern standards. 16px is the new minimum, and 18px is considered much more comfortable as a minimum size.
> * less ideal: if “Data Services Cloud Console” were converted into an SVG, this _might_ produce better results; you’d have to try it out to see
> * far less ideal: choose a different font that’s designed for optimal readability at 14px
> 
> Sorry, but IMO this is not a bug, but a feature of the font + weight + size + all of the other design decisions that have come before this point 🙂

Please let me know if you have any questions.

**Comment by halocline** [comment]
Regarding response to the original reported issue:

> From a windows machine, any browser, log on to https://sso.common.cloud.hpe.com/ Font issue is present anywhere the size is around 14px.

the advice is:
- Apply `-webkit-font-smoothing: antialiased` `text-rendering: auto`
- Follow HPE Design System guidance and components which have appropriate font-sizes and weight applications built in
  - Default HPE Design System font size is 18px and 'small' is 16px
  - 14px 'xsmall' should be minimized, if not avoided
- Avoid using small font combined with 500+ weights

That said, this issue deserves more investigation as the [screen shot posted here](https://github.com/grommet/hpe-design-system/issues/2080#issuecomment-1134921469) shows other instances where the 'i' appears problematic:
- Notice the 'i's in the headings and button labels (both of which are larger font-sizes) run together.
- 4/10 user testers cited the legibility as an issue.

**Comment by ericsoderberghp** [comment]
This will be carried forward by https://github.com/grommet/hpe-design-system/issues/2990
