### ISSUE TITLE
Form - Should Numerical FormFields be a smaller width than default size?

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2112]
During an Office Hours call, the India team had questions regarding the width of numerical values within FormFields. Here is an example below to give more context:

We should do a bit more research on best practices, standard design for such use cases and  provide guidance.
![Screen Shot 2021-12-02 at 8 11 29 AM](https://user-images.githubusercontent.com/62117454/144460336-111d12c9-e378-4426-b085-045fa02e3eef.png)

**Comment by Keeth-HPe** [comment]
@ecircenis Would like to hear some insights on this from you. 
Can we have consistent sizes for all the form fields, while the form field's text name example can help the user understand that it is a numerical form field?  

Because, there are use cases where the description text can be longer, like this one below. Forcing us to make the form field size bigger.
<img width="300" alt="Screenshot 2022-02-14 at 10 39 19 PM" src="https://user-images.githubusercontent.com/86280029/154021368-5162a8c6-8829-4055-8a5f-94a34e47f3e1.png">

**Comment by bahriaditi** [comment]
Thanks @Keeth-HPe - these are all important things to consider before we make a decision around guidelines.

As a next step for this issue, can you please create some quick design iterations to help test out these listed use cases? We can discuss more/ review these together next week.

**Comment by Keeth-HPe** [comment]
Hi  @ericsoderberghp  @halocline 

Here are my [findings on whether numerical FormField should use smaller width or default width](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=4988%3A3653). Leaning towards keeping it small (156px) based on research. Please review and share feedback :)

**Comment by halocline** [comment]
@Keeth-HPe - Thank you for sharing your findings. A lot of the research you've collected (as well as my knowledge from past UX work) has all recommended having the input field sized to the number of characters expected. The CVV and postal code fields are great examples of this.

If I understand your recommendation, it is to have a smaller width field, however you are not recommending the width be sized equal to the number of characters of the expected input. Is that correct? Are there any reasons why we shouldn't be recommending to size width equal to expected input character length?

Additionally, the recommendation is to allow description and info/error messages to span wider than the input field itself, correct?

Just wanting to clarify these points, and then we can dig into some of the finer details.

**Comment by Keeth-HPe** [comment]
@halocline - Thank you for reviewing. 

- Yes, that's right!  Smaller width for all numerical form fields (that's 156px).  

- And no, wouldn't recommend to size width equal to the expected input character length, because the expected input could vary from the user entering only 1 character to a maximum of 5 or 6 characters. 
So, unlike CVV or postal code fields, these numerical fields do not have a fixed number of characters to be entered all the time. 
<img width="727" alt="Screenshot 2022-02-24 at 1 51 34 PM" src="https://user-images.githubusercontent.com/86280029/155485873-042e3658-af7a-45fd-b0e9-de48b520822c.png">

The use cases we have are mostly about 'file sizes', 'Node count', where users can enter the value they want between the maximum and minimum.
So each time the user enters the maximum value or minimum value we do not want to width to change accordingly. 


- Yes, the guidance is to use succinct, short & descriptive labels. But if extra information is required, it’s okay for the help text or error message to be span wider. 

@bahriaditi  Please correct me if I'm wrong :) , let us know what you think.

**Comment by ecircenis** [comment]
I don't think this is going to work, in all cases.  Much of the reason for shorter fields is to put two fields next to each other.  But, if the labels/help can be longer or the error text can be longer (and it will be in our cases), then you lose the benefit of placing two FormFields next to each other because each of them must allow for longer description/help/error content (i.e. there could be errors in both of the side-by-side fields).

I'm all for being able to have outlined field contents that can be sized independent of the container for the label/help/error, but realize that this will not always allow for placement of fields side-by side.

![image](https://user-images.githubusercontent.com/17883783/155594544-b8bdfd1e-3814-461b-9a41-9c008d6f9000.png)

Also, why set a 156px limit for numeric text input?  Shouldn't it be defined by the width of the TextInput itself?  I.e. if I only want to allow the user to enter 2 characters, size the input accordingly.  On the other hand, if I need to enter $15,234,657,754.32, then size the field accordingly.

Finally, don't limit this to numeric fields.  There are cases where non-numeric TextInput fields are of a fixed width.  For example, US state abbreviations, serial numbers (which are alphanumeric), Yes/No responses in over-the-top confirmations, etc.  But I would not even limit this to TextInputs; make it work for any input.  The outlined part of the FormField should size itself to whatever content is placed inside. But the outer label/help/error should not be affected by the content size and should be sized separately.  This all applies unless the FormField is in a stretch container, in which case, it should stretch the outlined content as it does today.

![image](https://user-images.githubusercontent.com/17883783/155596476-75751f05-5565-4020-9b26-c421161f9b0b.png)

**Comment by scottoja** [comment]
There will always an exception to the rule but there are ways to increase the likelihood that adjacent fields can be supported by consolidating input labels, help, error, and message text when it makes sense. 
<img width="453" alt="Screen Shot 2022-02-24 at 2 33 32 PM" src="https://user-images.githubusercontent.com/83719939/155637149-d2d17929-5d2a-4388-aa55-df65644f203f.png">
<img width="399" alt="Screen Shot 2022-02-24 at 2 33 18 PM" src="https://user-images.githubusercontent.com/83719939/155637150-ad903d24-f2c6-46e5-97d1-77df442284de.png">
<img width="530" alt="Screen Shot 2022-02-24 at 3 36 55 PM" src="https://user-images.githubusercontent.com/83719939/155637695-40ecb7b4-3170-4433-a924-cda9a0c8e90d.png">

Yes, it would be beneficial to expand our DS guidance to go beyond just numeric fields, you provided great examples.
Yes, in agreement that the outlined part of the FormField should size itself to whatever content is placed inside.

**Comment by bahriaditi** [comment]
Thanks @ecircenis and @SOjaHPE for you thoughtful feedback.
Based on your comments, I am recommending we move ahead with the following:

## Numeric TextInput
- Width should be defined by the width of the input itself (instead of forcing a fixed width)
- Width of form field should be independent of validation and label line width
- Wherever possible, adjacent fields should be supported by consolidated validation. We need to provide visual examples to show how this will be presented in different cases, similar to those posted by Scott above.

## Non-numeric TextInput
- Identify use cases where TextInput width should be determined by input content (Ex: US state abbreviations, serial numbers (which are alphanumeric))
- [ ] Create separate issue for this

## Input Outline ( Checkbox & Radio Button)
- Consider having the outlined part of the input field sizing itself to whatever content is placed inside
- [ ] Create separate issue for this

@ericsoderberghp let us know if you have any additional thoughts.
@Keeth-HPe please move forward with the work needed around Numeric TextInputs as noted above.

**Comment by ericsoderberghp** [comment]
Given that a typical use case is for something like "number" + "units", is there any reason we cannot take the sub-bullets for "Numeric TextInput" and apply then to non-numeric cases as well? In other words, remove the distinction for "numeric".
I think this also can apply to MaskedInput and Select as well for all of the same reasons. The rationale seems good and none of it seems specific to "numeric" situations.

**Comment by ecircenis** [comment]
One way I see this working is: if I want two form items side by side and using the same validator, then both form items could be children of a single FormField.  There are already examples of this sort of thing being done where checking a checkbox in a formfield progressively discloses other form items within the same formfield.  We could do the same thing by placing a numeric text input and a unit selector side by side within a formfield.  The only downside is the extra outline that results.  Ideally, it should be possible to place multiple form items inside the same formfield and not have the extra outline.  Doing this would allow a single field validator to validate the entire content of the formField.
![image](https://user-images.githubusercontent.com/17883783/156793776-aef6874f-dda7-4d2c-a369-ff53df0803fb.png)

**Comment by bahriaditi** [comment]
@ericsoderberghp added more sub issues under parent ticket #2321 - haven't converted these to issues yet.
