### ISSUE TITLE
Form - Guidance on character limits on input, description field, and other fields

### ISSUE THREAD

**Issue by StingRay005** [grommet/hpe-design-system#2210]
This should be broken down into smaller issues prior to prioritization. Adding the following details to keep context:

Design direction for the following:
- [x] Guidance for when to use the character limit
- [x] How to display characters used out of max allowed
- [x] Any visual/message changes as character limit is getting near max (what threshold is "near")
- [x] Any visual/message changes as character limit is reached/exceeded

Development considerations:
- [x] Explore / consider shipping input fields / form fields with smart default character limits which may be overwritten by props provided (suggested by @eddieshowcase during office hours)
  - [x] Is this something we'd want to / should support?
  - [x] How would this work with validations (e.g. shown in info initially, but transfer to error if limit exceeded? treated similar to "required"?)

[https://www.figma.com/file/bk2unnNVpr97YSIbj2Krri/AuthZ?node-id=2855%3A34088](url)

**Comment by vavalos5** [comment]
It would be good to know how often are users inserting more than 100 characters and whether this is really needed or just becomes a distraction. Also, how does this work for screen readers?

**Comment by dahliaferrer** [comment]
Agree with @vavalos5 
- [ ] Ask developers **Who could I ask? 😊 Any suggestions? **
- How tight are the character limits on most form fields?
- How often do users surpass those character limits, resulting in errors/validation failures?

In a convo @ericsoderberghp and @bezAdane our initial thoughts are that this does not occur often. If developers state that this is a frequent issue, however, we would take more time to consider the benefits of a character counter. 

In the meantime, Eric, Beza, myself are considering the following (draft) guidance:

If users frequently violate a character limit, increase the character limit to avoid user frustration! If you cannot increase the character limit, then test or determine how often users surpass the character limit. If users frequently violate the character limit, then state the requirement underneath the relevant form field. 

Thoughts?

**Comment by dahliaferrer** [comment]
Chandan doesn't know how often users surpass the character limit. Who could I ask? @bahriaditi If no one knows I think we could ask Research!

He showed an alternate manner to handle this: https://www.figma.com/file/RSujQNCIyx6g2LXDjUMuFy/CaaS-end-to-end-UI?node-id=63%3A41968

**Comment by dahliaferrer** [comment]
@SOjaHPE **What do you think of asking Research to test character counter?** 

Thoughts: we could find a few fields that designers/developers have considered implementing a character counter on due to character limitations. Then test a few things:

1. How many characters would a user enter in a field if they did NOT have a limitation and consider setting a limit more in line with what 90% of the people do want to write.

2. How often the users would violate the limitation if we had set the limit the designers/devs proposed

3. Testing different options: 
- simple counter 87/100 on right side
- message: You have 23 remaining characters
- testing using word limitations instead of character limits
- the user gets a message when they reach 75% of the character or word limit

**Secondary research**: most design systems have stated what Eric pointed out: if users are running into error messages and spending time rewriting, the best UX is to have a more generous character limit. 

A UK gov website gave a few suggestions, one of which is setting a threshold: "set a threshold in the component markup. For example, data-threshold="75" will show the count message only when users have entered 75% of the limit." 

On accessibility, I've seen a design system state a screen reader should mention the limit when they interact with the field. Another design system stated that they should hear the limit when they stop typing. That latter seems less helpful. By that point they could have written their life story and only when they stopped did they realize the field didn't capture anything except the first 50 characters.

**Comment by dahliaferrer** [comment]
Wrote Katy about analytics on character counters we are currently using in our UIs. Much simpler scope. Bill Tipton reached out, he'd like to talk about Accessibility on character counters. Have a meeting today.

**Comment by StingRay005** [comment]
@dahliaferrer - Could you please share the outcome of your meeting? Do you feel like we have sufficient guidance here to get it across the finish line this week?
@bahriaditi @bezAdane - Any additional comments from a designer's perspective? I realize we discussed this in the sprint planning session this week.

**Comment by dahliaferrer** [comment]
Saw this from Edgar in HPE-design-system Slack channel:

"The grommet textarea is built on the HTML component of the same name.  If you set the maxlength attribute of an HTML [textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea), **_it doesn't allow you to enter more than the maximum, so you don't have to worry about "max length exceeded" because it cannot happen_**.  Does the grommet component support setting maxlength?"

Taylor replied:
Yes, the grommet component supports maxLength.
Doing the following would limit the TextArea to 100 characters.
<TextArea maxLength={100} />

**Comment by dahliaferrer** [comment]
In a convo with Bill Tipton, he emphasized a few important factors to keep in mind with regards to the character counter, but some of them don't really apply since (see comment above from Edgar) Grommet **doesn't allow** "to enter more than the maximum"
1. Please make it so that the reader tells the user before they start typing what their character limit is. In this way the user can plan what they will write and be blocked by error messages or time-consuming rewriting.
2. Announce when the user does go over (but in the case of a Grommet component, Grommet doesn't allow you to go over anyway, so maybe instead, announce that **they've hit the maximum**.)
3. The save button should appear once they've stopped typing and they have not exceeded the maximum.

**Comment by dahliaferrer** [comment]
Research team: 
I'd asked Katy (Kelly responded) if they have knowledge of any character counters used in our UI's and analytics on those that could give us some insights. The answer was no, but Kelly mentioned to speak with Salina Brown, on the Experience Studio team, who might have a "better grasp on the analytics you are requesting." Will write her an email today, but I don't think this should hold us back from issuing guidance @bezAdane . Everyone seems to agree a character counter is pretty standard and Twitter is a good example. 

The questions I have are:
1. In general, how many characters do most users need to give a name and description for a server or any cloud services we offer?
2. In general, how many characters do most users need to describe a problem?
3. Specific to our UI's, how long do users remain on a page with a character counter? (a longer than usual time could signal that they are experiencing difficulty keeping to the max character count we've set, and a short time could signal that our max is easy for users to remain under)
4. Specific to our UIs, how many times do they hit the max or get an error message?

**Comment by dahliaferrer** [comment]
DRAFT guidance:

When to use
Add a character counter to fields when users are likely to exceed the character limit for that type of field. Ex. when a field allows the user to enter a description, report a problem, give feedback, insert comments, etc. 

When not to use
If there is a low probability that someone would exceed those limits. Ex. when a user is naming anything in the apps, it is against their best interest to give an excessively long name. In this case, you would usually not add a character counter. 

Do's
1. If you don't add the character counter, the moment a user types more characters than the field limit, highlight the field in red. Add the following error message below the field: (!) Shorten this text to fit the character limit of ___. [fill in the limit]. [see guidance on field character limits](https://design-system.hpe.design/components/tag?q=characters#anatomy) 
2. Use a numerator/denominator format. Ex. 0/128.
3. Count down the characters as the user is typing. Ex. 52/128 if they've typed 52 characters. 53/128 when they type an extra character, etc.
4. The character counter should be in the same color as the field title.   

[ @bezAdane  Can you think of any other do's? ]

Don'ts
1. Use color for the counter. It already stands out and using red in other circumstances has resulted in the user making more errors.

[ any other dont's? ]

Accessibility
1. When the user tabs to the field, ensure the reader [ @bezAdane could you give the props/aria for this?] immediately announces the character limit. By announcing it before the user begins typing they can plan what to write and not be frustrated by error messages or rewriting.
2. Announce - while the user is typing - when they reach or exceed the character limit.
3. The save button should be announced when the user has stopped typing and they have not exceeded the maximum.

I would need some help understanding this (below), Beza. Also, I've checked off some of the items in Eric's tasks at the top. I think we've covered them. But these below I would need someone to show me. The Figma link provided is no longer an active link.

Development considerations:
Explore / consider shipping input fields / form fields with smart default character limits which may be overwritten by props provided (suggested by @eddieshowcase during office hours)
 Is this something we'd want to / should support?
 How would this work with validations (e.g. shown in info initially, but transfer to error if limit exceeded? treated similar to "required"?)

**Comment by bezAdane** [comment]
Closing this ticket.
