### ISSUE TITLE
Onboarding - Update 'new issue' template on GitHub

### ISSUE THREAD

**Issue by bahriaditi** [grommet/hpe-design-system#2292]
For whom:
To facilitate onboarding of both the consumers of our Design System and new team members as they create new issues. 

Why:
The [current template ](https://github.com/grommet/hpe-design-system/issues/new) follows a template for filing bugs/ dev centric issues. Need an updated version that works for designers, developers and PMs. Having an updated version can encourage more people to file tickets directly in GitHub.

## Deliverables

- [x] draft a proposal
- [x] review with the team
- [ ] publish

**Comment by taysea** [comment]
Proposing we could have different "templates" (similar to what other repositories like [Next.js](https://github.com/vercel/next.js/issues/new/choose) do)
1. [Figma component library bug](#figma-component-library-bug)
2. [Design System documentation example bug](#design-system-documentation-or-example-bug)
3. [Feature request (example on site or Figma component requests)](#feature-request)

# Figma component library bug

Thank you for catching a bug in our Figma library! Please fill this out as completely as possible to help us troubleshoot.

## What component does this relate to?

## Describe the bug

## Expected behavior

## Link to component file

## Screenshot or screen recording of bug

## Steps to reproduce

# Design System documentation or example bug

Thank you for catching a bug in our documentation! Please fill this out as completely as possible to help us troubleshoot.

## What does this relate to?
- [ ] Written guidance
- [ ] Example
- [ ] Missing, incorrect, or broken link

## If this is a bug in an example, describe the bug.

## Expected example behavior or written guidance

## Link to example or guidance section

## If this is a bug in an example, screenshot or screen recording of bug

## If this is a bug in an example, steps to reproduce

# Feature request

Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.

## What is this feature related to?
- [ ] Figma component library
- [ ] Design System site examples

## Describe the feature you'd like to request
A clear and concise description of what you want and what your use case is.

**Comment by ericsoderberghp** [comment]
I like the different templates approach. I'm wondering if we should either split it into two:
- something is broken
- something is missing
and have the user indicate the scope and context as needed.

Or, split up by primary context as well:
- something is broken in Figma
- something is broken on the HPE Design System site
- etc.

I'm trying to think about what would make it easiest from the submitter's perspective, what would produce the least amount of friction and get the most people using them.

**Comment by britt6612** [comment]
I like the direction of the following:

> Or, split up by primary context as well:
> 
> something is broken in Figma
> something is broken on the HPE Design System site
> etc.

especially since most of the users are doing something in Figma or the site..

**Comment by taysea** [comment]
I've started building these templates out as described about:
1. figma bug (broken)
2. design system site bug (broken)
3. figma feature request (missing/desired)
4. design system site docs/example request (missing/desired).
T

To view the templates, click on a yml file: https://github.com/grommet/hpe-design-system/tree/updated-issue-template/.github/ISSUE_TEMPLATE
