### ISSUE TITLE
send bi-weekly email Design System newsletter

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2319]
Don't over-think this to get started.

A simple text email with "highlights from the past couple of weeks" and "some things we're working on".

Send to Kamlesh, he will figure out who to send it to and send it.

**Comment by britt6612** [comment]
🗞 Latest news from the Design System 🗞
 
We've heard your feedback that it’s "hard to keep track of the latest HPE Design System developments." We also know that people prefer choice in mediums when consuming communications. So, in addition to Slack and "Office Hours," we will distribute this email newsletter to update you on advancements and changes to Design System patterns, components, and guidance.
 
Below you'll find what's new from January 24th to February 11th 2022
 
HPE theme breaking change
Text-Weak – In order to provide a more subtle text color that meets accessibility requirements for color contrast, the value for text-weak is changing from #BBBBBB to #757575 for light mode and from #606B7D to #8C98AA for dark mode.
 
A new namespace of text-xweak is being added with the values that were previously assigned for text-weak. Theme-defined disabled states (such as Form Fields) will automatically be updated to use text-xweak. However, instances where your code is using text-weak via props may need to change to text-xweak after the release.
 
The new text-weak value passed WCAG AA contrast values. #BBBBBB and #606B7D will remain the value for disabled fonts.
 
We would like to hear any feedback on this change ahead of the next release of the HPE Theme. To test out this new change, apply the theme’s stable branch to your project by the [following these directions](https://github.com/grommet/grommet-theme-hpe#stable). This is a breaking change that will be in the next HPE theme release which will be published in March. 
 
Communications
Office Hours – India Office hours will now be help every other Thursday, 9:00 PM IST/ 7:30 AM PST. This office hours is open to all. Contact Kamlesh Thakur, if you would like a calendar invite.
 
Roadmap Updates
Page Layouts  
·      Published Context Layouts page which provides guidance for [designing for responsiveness](https://design-system.hpe.design/templates/content-layouts#designing-for-responsiveness), [responsive breakpoints](https://design-system.hpe.design/templates/content-layouts#breakpoints) and [page margin](https://design-system.hpe.design/templates/content-layouts#page-margin).
·      Began publishing a collection of [page layout templates](https://design-system.hpe.design/templates/content-layouts#templates) and [dashboard templates](https://design-system.hpe.design/templates/dashboards#dashboard-templates) which provide customizable templates for design and development Collaborating with UCEP to align the Global Header/Footer Service with page layouts guidelines. Provided proof-of-concept project to deliver the [HPE Global Header as a Web Component](https://github.hpe.com/grommet/hpe-global-header). 
No Data – Added guidance and example [displaying empty/missing values](https://design-system.hpe.design/components/namevaluelist#name-value-pair-with-empty-value) in a NameValueList.
Navigation – Published [five types of navigation patterns](https://design-system.hpe.design/templates/navigation#types-of-navigation), the strengths for each and when to use.
 
Stay current with latest changes
·      Toast Notifications – Enhanced the ability to allow greater control over placement of Toast Notification. Make sure you are aware of the trade-offs associated with [placement design decision](https://design-system.hpe.design/templates/toast-notifications#placement).
·      Accessibility – Do you know the [4 core principles of accessibility](https://design-system.hpe.design/foundation/accessibility)? Read up on what it means to be perceivable, operable, understandable, and robust. 
·      Buttons – Have “grouped buttons?” What type of Buttons can be appeared together? How should they be ordered? How should they be aligned? See [Button ordering](https://design-system.hpe.design/components/button#button-ordering) for more detail.
 
Grommet Release – Released Grommet v.20.1 which included an enhancement allowing form validation to occur “onMount” for controlled input forms, and bug fixes for “double focus on select and search,” DateInput formatting, Button icon alignment and styling for TextInput with suggestions. View full release notes [here](https://github.com/grommet/grommet/releases/tag/v2.20.1).
 
Thank you for using the HPE Design System!

**Comment by britt6612** [comment]
sent email template to Kamlesh he was going to send out think this can be closed.
