### ISSUE TITLE
Page Layouts - add new grommet components

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2334]
Leverage the learnings from implementing page layouts so far to define new grommet components in support of this, to make it easier for teams to follow the patterns without needing to copy/paste a lot.

- [x] create an initial pull request including the API surface and a story or two
- [x] review with the team
- [x] respond to review feedback
- [x] final pull request review and merge
- [x] grommet-site documentation

**Comment by jcfilben** [comment]
![image](https://user-images.githubusercontent.com/54560994/154136825-fc31082b-798e-4161-849e-3d6e0000f7ed.png)

Page Layouts Grommet Components

I am thinking there should be Grommet components for the App Container and The Page Container. The Global Header and Footer pertain only to HPE and the Page Header and Page Content seem too broad, if they were Grommet components they would be trivial.
 
There was some discussion around naming and how “container” as a name can be used is so many different contexts. I am wondering if we should call the Grommet components `<Page>` and `<App>`? **Would love to discuss and get other thoughts on naming.** (For simplicity’s sake I will continue referring to them as App Container and Page Container until we settle on naming since that is what they are called in Figma and on the Design System site).
 
The App Container will be a Box with the following props set:
height={{ min: ‘100%’ }}
width={{ min: ‘medium’ }}
flex={false}
{…rest} passes into Box
 
Page Container
width/kind= ‘wide’ || ‘narrow’ || ‘full’
pad=”medium”
alignSelf={kind === "full" ? "start" : "center"}
margin={kind === “full” ? ‘none’ : { horizontal: ‘auto’ }}
{…rest} passes into Box

I am still thinking about naming for the width/kind prop on the Page Container. I think we should avoid using width since Box has a width prop and it is different than Page Container width, this could cause confusion. Calling the prop `kind` doesn't feel quite right since it doesn't fit with how we are using `kind` elsewhere. In Button kind feels more related to theming. Definitely open to discussion & thoughts on this.

**Comment by taysea** [comment]
I think that `kind` could work if we consider some of the styling to be handled by a theme object similar to the implementation we currently have in DS site: https://github.com/grommet/hpe-design-system/blob/master/aries-site/src/examples/templates/page-layouts/components/PageContainer.js#L9

**Comment by ericsoderberghp** [comment]
For HPE, is `App` primarily there as a container for the global header?
Would it work for a grommet app to just use `Page` and not have `App`?

**Comment by ericsoderberghp** [comment]
Regarding `kind`, the name feels a bit broader to me than what we are using it for. For `Button`, it controls all aspects of styling, padding, border, background, etc. For `Page`, it seems to be focused primarily on the maximum width of its contents. What about `<Page max="wide" />` or `<Page size="wide" />` or `<Page limit="wide" />` or `<Page maxContent="wide" />` or ??? I'm just stirring the pot a bit to see if anything resonates. Still open to discussion.

**Comment by ericsoderberghp** [comment]
Regarding `PageHeader` and `PageContent`, I do see some value in `PageContent`, especially when used within `<Page />` context, in which case the `PageContent` would tap into the `PageContext` to see how to limit its layout. `background` would stretch all the way across but it would derive alignment, margin/pad, and max content width from `PageContext`.

I do think `PageHeader` could be delayed for now, until we have more from that on the design side. Callers could use:
```
<Page>
  <PageContent>
    <Header />
  </PageContent>
</Page>
```
in the meantime.

**Comment by jcfilben** [comment]
> For HPE, is App primarily there as a container for the global header?
Would it work for a grommet app to just use Page and not have App?

Yes, App is mainly there for the global header & footer. I agree, we don't need to have App in Grommet.

> What about <Page max="wide" /> or <Page size="wide" /> or <Page limit="wide" /> or <Page maxContent="wide" /> or ???

I like `maxContent` it is specific without being too verbose.

**Comment by taysea** [comment]
> 

Another thought `maxWidth` -- to me, initially `maxContent` registers as relating to the amount of content as opposed to its direction

**Comment by halocline** [comment]
The main idea I am attracted to is `<Page />` serving as the context provider and `<PageContent />` being the context consumer.

If we went the route of something like `maxContent` would that ship with default alignment, margin, etc.? Would we then allow the caller to override via props?

I had been thinking of people who might want the ability to create custom Page types of "marketing, landingPage, cozy, compact, roomy" which might ship with additional defaults (alignment, pad, margin, gap, etc.) which was why `kind` emerged. However, that would all be achievable with props to create their own flavors if they wanted.

That said, the more I type, the more I am attracted to the `maxContent` approach which primarily controls the max-width and ships with theme defaults which may be overridden via props.

Apologies for typing my stream of consciousness "out loud." 🤪

**Comment by jcfilben** [comment]
Thanks for the feedback everyone!

I have created a codesandbox that shows what I am thinking so far: https://codesandbox.io/s/grommet-v2-template-forked-mv6p0?file=/index.js

Some notes:
- I ended up leaving the prop name as `kind` since it is controlling more than just the width. Setting kind to "wide", "narrow" or "full" affects the max width and the alignment and can be modified in the theme.

- I am questioning if we should allow the pad to be set in the theme for each kind. (Currently my codesandbox sample theme structure only allows the user to define padding that is then applied to all the kinds of page layouts). I realize for the hpe theme we want the padding to stay the same for the different kinds, but for grommet users may want to change padding per kind of page layout.

- To allow the background for PageContent to take the full width instead of being restricted by the kind width you can set the `full` prop on PageContent.

- I am wondering if `PageContent` should be renamed to `PageSection`. PageSection makes more sense to me but wanted to check if anyone else had opinions.

**Comment by ericsoderberghp** [comment]
I'm good with heading towards a pull request and continuing feedback in that context. I kept finding myself wanting to make comments on specific lines, which I think would be easier in a pull request context.

**Comment by jcfilben** [comment]
> I'm good with heading towards a pull request and continuing feedback in that context. I kept finding myself wanting to make comments on specific lines, which I think would be easier in a pull request context.

Sounds good I will start working on a PR

**Comment by jcfilben** [comment]
re-opening until docs on grommet-site get merged

**Comment by jcfilben** [comment]
Grommet PR and grommet-site PR have both been merged
