### ISSUE TITLE
PageHeader - update design system site to use PageHeader

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#2562]
## Problem

How can we verify that the PageHeader component is useful and demonstrate its use to our customers via the design system site?

## Deliverables

- Update the site itself to use PageHeader for site pages, like https://design-system.hpe.design/components/box
- Update the examples on the design system site where appropriate to use PageHeader

Examples to be updated:
- [ ] Site detail pages (Box, Filtering, etc.) (1) -- single place to update all
- [ ] Page (5)
- [ ] NameValueList (4)
- [ ] Tag (3)
- [ ] Content Layouts (2)
- [ ] Global Banner (1)
- [ ] Dashboard (3)
- [ ] Lists (1)

**Comment by vavalos5** [comment]
Wizard will not be updated as it is different from the PageHeader. We established early on that Wizard has its own unique PageHeader. Which it also sounds like we'll be revisiting Wizard, specifically adding steppers at the PageHeader level due to teams wanting to show more transparency to the user on what is expected from them.
