### ISSUE TITLE
Menu - Update Figma file for grouped items

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2640]
Follow on to #2621 

NOTE: Guidance and examples are being staged on the DS site for comments and review. To keep workflow streamlined, review comments should be incorporated and/or addressed prior to this Figma work.

A link to the site guidance and examples will be added to this issue for reference.

- [ ] Update Menu Figma file to include examples of a menu with grouped items.
  - [ ] Determine whether these updates should occur in the legacy file or the new component format.

**Comment by MeganBeierle** [comment]
@halocline @bahriaditi @ericsoderberghp 

Hi all- 
After speaking with Matt about this task today I have an updated design to propose to the team. It had been discussed in the past that we need either an outline or an alternative treatment for the separation line. The live implementation has the separation line running across the entire list box and it is felt that this treatment doesn't create a cohesive look for the list. The idea of adding an outline to the entire outside of the list box isn't ideal because of so many instances that would need to be changed as a result. Here is a link to the proposed design: https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=2706%3A1335

This style of separation line had been discussed in the past and I think it would be a good solution. Let me know your thoughts! 
Megan

**Comment by ericsoderberghp** [comment]
I'm supportive of the shortened separator line, aligned to the text

**Comment by halocline** [comment]
> Here is a link to the proposed design: https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=2706%3A1335
> 
> This style of separation line had been discussed in the past and I think it would be a good solution. Let me know your thoughts! Megan

This seems reasonable. No concerns from me visually. I believe we will need to tweak Grommet implementation, is that correct @taysea?

**Comment by halocline** [comment]
Created https://github.com/grommet/grommet/issues/6188 as follow on to this issue for implementation.

@bahriaditi , @vavalos5 if we are okay with the proposed visual design direction, I believe we can close this. If so, please feel free to close.

**Comment by vavalos5** [comment]
Nice job @MeganBeierle! @halocline @bahriaditi I'm good with this :)

**Comment by MeganBeierle** [comment]
https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=0%3A1

I added the new design to the "Finished" page and created the dark version. We will leave this as visual guidance and Kenny will update the component when it is converted to the new layout. Marking as finished.

@bahriaditi @KennyAtHPE
