### ISSUE TITLE
Implement "Sentence case" capitalization

### ISSUE THREAD

**Issue by dahliaferrer** [grommet/hpe-design-system#2744]
In accordance with all of our brand guides and the Chicago Manual of Style that HP and HPE rely on, we are implementing sentence case. 

- [ ] Change DS guides to change any "Title Casing" that would confuse our users if we ourselves aren't adhering to sentence case!
- [x] Talk with Raja about best way to do this.
- [x] Review Edgar's links

Continuation of this ticket:
https://github.com/grommet/hpe-design-system/issues/2610

**Comment by dahliaferrer** [comment]
@ericsoderberghp  Let's set up a chat with @CitizenFox

**Comment by dahliaferrer** [comment]
for next issue:
- [ ] Retroactively change, methodically, any previous UIs that I can access

**Comment by dahliaferrer** [comment]
I've changed the guidance on the Voice & Tone, I've created a PR for @ericsoderberghp and Taylor, too, I believe.

**Comment by dahliaferrer** [comment]
In my chat with Raja today, Wednesday July 27, he liked the idea of including me earlier in the discussions. He prefers me commenting on files so that people learn. I'm not against it. He said he would schedule another chat for next week.

He brought up his POV that most of the users are experienced and "will know" things. This brought up an interesting juxtaposition to the whole motivation behind user experience. In our next talk I'd really like to gather his experience from when he was starting his studies and career. Actually, I'd like to get a lot of developers and our admin-customers from their initiation into their studies and careers. This type of qualitative survey (and let's see if we can get some quantitative knowledge) would greatly inform the content strategy greatly towards our admin-customers.

**Comment by ecircenis** [comment]
Can we get a table in DS that clearly shows places where we put text and whether it should be title vs sentence cased (and maybe a column for rationale)?  For example, I'm all for using sentence casing for names in NameValuePair, FormField labels, DataTable column headings, etc.  But there are some that we should talk about.  For example, should we use title case for dialog titles (they are titles, after all).  And, if we do that, should we have consistency between the buttons/menu items/anchors that lead to those dialogs (the names and case match)?  I think an exhaustive list would eliminate all confusion.  When we do this, we should update ALL examples in DS to match the new standard, otherwise it will lead to confusion due to inconsistency.

**Comment by ecircenis** [comment]
Also, consider that the Chicago Manual is more about document writing and not as authoritative in UX circles because it doesn't really address product use (forms, HTML controls, etc).  There is, however a lot of UX research when it comes to case use.  Here are some examples, but there are probably many more, and you would have to dig a bit to find things that map more to controls rather than blocks of text:
https://uxdesign.cc/title-case-vs-sentence-case-in-ux-writing-212087192261
https://www.herosmyth.com/article/headline-capitalization-ux-title-case-vs-sentence-case
https://www.everyinteraction.com/articles/title-case-vs-sentence-case-in-ui/
https://www.nngroup.com/articles/glanceable-fonts/

**Comment by dahliaferrer** [comment]
Thank you, Edgar! I did look for some when I first was tasked with this, but didn't find much actual UX research per se. It was mostly blog-style with UX writers' opinions on sentence/title case. I'll definitely look into any UX research! Thanks!
________________________________

**Comment by taysea** [comment]
Follow-on: https://github.com/grommet/hpe-design-system/issues/2897
