### ISSUE TITLE
Feedback- Explore icon options

### ISSUE THREAD

**Issue by MeganBeierle** [grommet/hpe-design-system#2796]
- [ ] Explore multiple options for a floating feedback icon.
- [ ] Explore multiple options for look/behavior of actionable star and thumbs icons.

**Comment by MeganBeierle** [comment]
@ericsoderberghp Hi Eric! This is what I want to get done in the feedback work this week. Let me know if you need anything from me on this!

**Comment by MeganBeierle** [comment]
https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=198%3A9863

@ericsoderberghp Hi Eric! Can you please put this into "For Review" in the main board. I don't know how to move it over. 

@bahriaditi Hi Aditi! I explored some additional icons and color treatments this week and they are ready for review. I was thinking about coming to the designer check in next week to talk through these. LMK if that's ok. Megan

**Comment by bahriaditi** [comment]
> https://www.figma.com/file/StvDVAzAJvZzzTNmd7TQVu/Feedback-components?node-id=198%3A9863
> 
> @ericsoderberghp Hi Eric! Can you please put this into "For Review" in the main board. I don't know how to move it over.
> 
> @bahriaditi Hi Aditi! I explored some additional icons and color treatments this week and they are ready for review. I was thinking about coming to the designer check in next week to talk through these. LMK if that's ok. Megan

Hi Megan, great idea! See you tomorrow :)

**Comment by KennyAtHPE** [comment]
@MeganBeierle just watched the designer check-in recording. I vote for a purple color with an icon. 

If the goal for this is to be shown on platforms in addition to the DS site, I think it'd be beneficial for the color to be different than our primary buttons and notifications. The teal, green, and neutral colors seem too much like those other components and could lead to confusion. As for the icon over the "feedback" text, since the feedback component is a layer that lives on top of page content, I think it'd be best for it to be as small as possible to avoid any possibility of it covering content,

**Comment by bahriaditi** [comment]
@MeganBeierle closing this ticket since we are tracking the prototype work in #2760
