### ISSUE TITLE
HPE Grommet Community — Create list of "interest items" for survey

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#2880]
To start the HPE Grommet Community, we want to hear what topics/materials the community is most interested in.

- [ ] Gather list of topics/kinds of materials that devs are wanting (e.g., ResponsiveContext/Grid/Box tutorials, scannable examples, back links to grommet site)
- [ ] Send to Jeff Krenek

**Comment by taysea** [comment]
Ideas:
- Guide: Understanding Box and Grid for layouts
- Guide: Understanding ResponsiveContext
- Guide: How to translate Figma designs --> Grommet components and props
- Open question: What kinds of examples would you like to see on Design System site? page layouts, etc.?
- Open question: How do you learn best? Written guides/blogs, video tutorials, etc.?

**Comment by jcfilben** [comment]
Feedback from grommet community:

Areas of confusion:
- Extend and styled components
- Right to left
- Internationalization
- Dark and light mode
- ThemeContext
- How css properties map to grommet (naming)
- Didn't realize there was a theme
- Using `as` vs `forwardAs`
- How grommet determines background color
- Responsive behavior built into grommet

Requests:
- Sample application for v2 (v1 had Ferret application)
- Mode code examples in docs
- Have content in one place, not external wiki docs outside of the grommet docs

Ideas:
- make documentation searchable (currently only component names are searchable)
- change site to better support documentation within the page (instead of external sources like the wiki pages)
- add started project and code (current started is out of date and contained in a separate github repo)

**Comment by halocline** [comment]
> What Grommet topics would you be interested in learning about? (select all that apply) 
> 
> Layouts:
> * General layouts
> * Building with Box and Grid (based on flex-box and CSS grid)
> * Responsive behaviors
> * Right to left language
> * Other

**Comment by halocline** [comment]
> Theming:
>
> * Theme customization 
> * Light and dark modes
> * Use of Styled-Components
> * Pros and cons of styling approaches
> * Other

**Comment by halocline** [comment]
> What's your preferred way to learn? (select all that apply):
> 
> * Written guides/blogs
> * Video tutorials
> * Project-based tutorials (mini app/project)
> * Workshops
> * Documentation site
> * Topical presentation / talk
> * Live-stream coding sessions (Twitch, etc.)?

**Comment by halocline** [comment]
I think we might want a miscellaneous section as part of Q1

Miscellaneous:
- How Grommet determines appropriate text and background colors (this could fit under accessibility)
- Passing DOM attributes as props
- Internationalization and messaging
- Other

**Comment by taysea** [comment]
Closing, email has been sent to Jeff.
