### ISSUE TITLE
Form - Draft managing objects

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#2899]
### Proposed solution
- Use collapsible objects to show/hide detail as needed. The intent is that collapsible objects will reduce the noise and resulting cognitive overload by hiding extraneous detail.

### Deliverables
- [x] 2-3 visual treatments/layout (meeting the criteria below) for [Beza]:
  - [x] Object collapsed state
  - [x] Object open state
  - [x] Object list / section displaying the multiple objects
- [x] Share visual treatments and make decision on which style we want [Team]
- [x] [Codesandbox prototype](https://codesandbox.io/s/crud-child-objects-jh42hw?file=/src/childThemes.js) showing the the object list in a context of a larger form [Matt]
  - [x] Apply selected visual style to prototype
  - [x] Real use case example
- [x] Demo and discuss interactions and behaviors with team [Team]
- [x] Collect feedback, write up next steps in follow on issue(s) (e.g. testing phase, build Figma component, behavior documentation / guidance, DS site pull request)
  - #2998
  - #2999
  - #3000

### Success Criteria
- Collapsed object state
  - Are recognizable as distinct items
  - Have a label which uniquely identifies the item
- Expanded object state
  - Are recognizable as a distinct item
  - Have a label which uniquely identifies the item
  - Display inputs to collect the object detail
  - Delete/remove button to remove the object
  - Ability to collapse object
- Behaviors
  - Validate object on blur (no need for Save button --> assuming input values are what the user intends)
  - Moving focus to another object or section will result in the open object automatically collapsing
- Style
  - Feels visually consistent with the rest of Design System designs.

**Comment by halocline** [comment]
Figma file for review comments: https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=8004%3A45548

**Comment by vavalos5** [comment]
> Figma file for review comments: https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=8004%3A45548
> 
> Soliciting comments from: @ericsoderberghp , @taysea , @KennyAtHPE , @vavalos5 , @SOjaHPE

Nice job! I think the new approach is coming along. I've left my comments in the Figma file but I do like how Option 1 is looking the best. 👏🏼

**Comment by KennyAtHPE** [comment]
> Figma file for review comments: https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=8004%3A45548
> 
> Soliciting comments from: @ericsoderberghp , @taysea , @KennyAtHPE , @vavalos5 , @SOjaHPE

Added some comments, appreciate the multiple different approaches. Think that there's more room to explore some visual styling options and button placement/wording but great job so far!

**Comment by halocline** [comment]
Thank you @KennyAtHPE, @vavalos5 , and @taysea for all your comments. Much appreciated.

I left comments as well, but I left a few regarding some suggestions for how we might aid both authors and reviewers in evaluating our design choices. Specifically, I think it might be valuable for us to [include our solution criteria](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8?node-id=7990:59252#272550240) alongside the proposed solutions. Please read through for consideration.

**Comment by bezAdane** [comment]
> > Figma file for review comments: https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=8004%3A45548
> > Soliciting comments from: @ericsoderberghp , @taysea , @KennyAtHPE , @vavalos5 , @SOjaHPE
> 
> Added some comments, appreciate the multiple different approaches. Think that there's more room to explore some visual styling options and button placement/wording but great job so far!

Yes,  based on some of the comments and suggestions i agree there is a room for some room for visual styling exploring :)

**Comment by bezAdane** [comment]
Based on the feedbacks and todays conversation we had I am putting the[ figma file here](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=8167%3A72696) where you will find some of exploration on heading treatment size/ and other typography explorations. Exploring other types of collapsible UI elements in addition to Accordion. Though its not pixel perfect and hi-fi wanted to show the other direction explored and get something out for prototype.

**Comment by vavalos5** [comment]
@halocline Do you know if we need to do a second review for Beza's ticket on the second round of ideations she's done? She will be OoO until Oct. 12. If we need to put this back in backlog or into a new ticket since first ideation has been completed, we should do that so it doesn't linger in the active board. LMK if I can help.

**Comment by halocline** [comment]
Here is the link to the [Codesandbox prototype](https://codesandbox.io/s/crud-child-objects-jh42hw?file=/src/App.js).

Currently it has the "Create cluster" use case. Will add the "user permissions and filters" use case.

Next steps are to review the implementation with @bezAdane, incorporate any adjustments, then schedule a session to review with the larger team.

**Comment by KennyAtHPE** [comment]
@halocline @bezAdane my thoughts after playing with the prototype. 

**General behaviors (expand/collapse, focus, keyboard)**
- Not entirely sure about the interaction of having the sections collapse when tabbing past them or clicking outside of the container. Made me wonder why things were closing when I was clicking around.
I do really like the way the interaction works currently with the [Accordion component](https://deploy-preview-2982--keen-mayer-a86c8b.netlify.app/components/accordion?q=accord) where the section will close once a different one opens. 
- Not sure if testing has been done with Bill but I think it could be helpful to get his feedback on this

**Accordion-style vs. border-all-style**
- Big fan of the border-all-style since it provides a divider between the bottommost instance and the Remove All + Add Instance buttons.
![image](https://user-images.githubusercontent.com/86075038/197611861-aa83f47e-eab3-4128-bd86-51243063ed57.png)

**Border color**
- I prefer the 'weak' border color. Although I would like to see it with the same border color as the input fields or possibly even darker than those.

**Object Label font-weight**
- I prefer 500 over the other options. Think the other options are too strong visually when you have a lot of instances.

**Other**
- Could I possibly see an example without the 'Region' select at the bottom? Wondering if there is enough spacing between the Remove All + Add Instance buttons and the Create + Cancel buttons. Also, will spacing be enough to differentiate these or should there be a dividing line between them?

**Comment by halocline** [comment]
Issues created for testing interaction w/ Bill, implement design direction in Figma, add use case and guidance to site. ☝️
