### ISSUE TITLE
Managing Child Objects [Testing phase] - Refine prototype and test with Bill T.

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#2998]
[Prototype](https://codesandbox.io/s/crud-child-objects-jh42hw?file=/src/childThemes.js)

Follows on: https://github.com/grommet/hpe-design-system/issues/2899
- Refine auto close object behavior. Currently the keyboard behavior is nice, but the onBlur implementation causes undesirable closing when mouse pointer clicks outside of object. One option might be to only close when focus is applied to a different object or the "Add {object}" button.
- Consider using Accordion instead of Collapsible.
- Refactor form implementation.
- Evaluate screen-reader experience.
- Test w/ Bill T.

**Comment by jcfilben** [comment]
**1. Refine auto close object behavior.**

I adjusted the auto close behavior to only happen when a user is navigating with a keyboard. I found the auto close behavior a bit too finicky when using a mouse. It felt like there were too many times I accidentally closed the object. Also when using a mouse I found it helpful to have multiple groups open at the same time so I could compare or refer back to information between groups easily.

**2. Consider using Accordion instead of Collapsible.**

I stuck with using Collapsible. I didn't want us to have to encourage changing the hpe theme to style Accordion. In addition using Accordion didn't feel like it reduced code complexity.

**3. Refactor form implementation.**

Done. The prototype no longer has multiple `<Form>` elements and everything is now contained within one `<Form>`.

**4. Evaluate screen-reader experience.**

I tested on my end with JAWS and voiceover and made a few tweaks here are there before testing with Bill.

**5. Test w/ Bill T.**

Brittany, Kenny, and I met with Bill T. to test out two different prototypes.

Prototype 1 - https://codesandbox.io/s/grommet-v2-template-forked-csflw4?file=/FormObject.js
Prototype 2 - https://codesandbox.io/s/grommet-v2-template-forked-wojfto?file=/index.js

The difference between the two is the second prototype moved the focus to the newly created object (in the examples above 'New Animal') when 'Add animal' was clicked. In the first prototype the focus remained on 'Add animal'.

Bill said that the first prototype was easier to use. I think moving the focus caused confusion.

Additional notes:
- It would be helpful to have the object names as headings so it is easier to jump between them. In the examples above having 'New Animal' as a Heading instead of Text.
- The aria-label of 'Show detail' and 'Hide detail' on the collapsible button control didn't make it clear that you are able to edit the details. Bill suggested including the word 'edit' in the aria-label.
- Bill thought the summary info was helpful and gave him a better idea of each object.

Next steps:
I will clean up the prototype to include bill suggestions and include a link to the new prototype here.

**Comment by jcfilben** [comment]
Updated codesandbox example: https://codesandbox.io/s/grommet-v2-template-forked-7e0vpd?file=/index.js

Note: I chatted with Kenny about switching the Collapsible Button label to use Heading instead of Text. We adjusted some spacing to give more balance but I don't think this is 100% finalized yet. I believe Kenny, Vicky, and I will connect more to discuss this week and figure out the spacing.
