### ISSUE TITLE
Accessibility Page - Review Bill T.'s document

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3006]
Bill, Brittany and I have begun a project with Bill. My idea was to create some content to add to the accessibility page where we talk about what assistive technologies there are and who it affects. The idea is to provide people with more knowledge on the different types of impairments and what assistive technologies there are to be accessible.

**Comment by vavalos5** [comment]
Assistive technology is either software, hardware or a combination of both that could be used by a person to access digital technology such as software, web pages or documentation. There are many types of assistive technology talked about in [Tools and Techniques (WAI)-W3C](https://www.w3.org/WAI/people-use-web/tools-techniques/#main). A few examples are screen readers that generate synthesized voice for people who are visually impaired or blind to listen to and interact with digital technology, screen magnification software to magnify the screen to help people with low vision see the screen more effectively, speech control software for people with mobility issues with their hands preventing them from using a physical keyboard allowing them to access and interact with digital technology by using their voice, or sip and puff devices for people who may have other types of mobility disabilities and use their sip and puff device just like it was a keyboard.

 People who are both blind and deaf use a braille display to access digital technology by using their sense of touch to feel and interact with the digital technology through their fingers as they read the braille cells. Also, people who are blind and visually impaired can use a braille display to help reduce audio overload (screen reader user reding digital technology and taking notes, peoples voices on conference calls and one's own voice  when communicating with others). 

Since there are many assistive technologies that can interact with digital technologies and fortunately when you are designing and developing digital technology such as software you do not need to be an expert in any of these assistive technologies. 
Web Content Accessibility Guidelines 2.1 (WCAG) has made this step easier for you. if you follow these guidelines and perform manual evaluation as described below most if not all assistive technologies should work effectively for the end-user. Basically, assistive technology works by programmatically interfacing with the digital technology. This is why if accessibility is designed and developed using accessibility guidelines such as WCAG 2.1 without any syntax errors in the code this should help create a delightful experience for users who use assistive technology. This is true if you do not forget to evaluate  the digital technology manually by people with a broad range of disabilities  using a mix of different assistive technologies as talked about [in Involving Users in Evaluating Web Accessibility (WAI)-W3C](https://www.w3.org/WAI/test-evaluate/involving-users/). One should also complement this manual testing with automated testing to save time and to locate the issues that can be detected by software only and do not require a real person to provide information that a real person can only detect. For example, if a certain element passed a WCAG Success Criteria such as if a hyperlink is concise and descriptive when reading out of context or if a graphical element has a meaningful alternative description.


Next step would be providing Bill with feedback and starting some visuals based off of the context.

**Comment by vavalos5** [comment]
When it comes to inclusivity and accessibility, assistive technology enables individuals with disabilities to live a more independent, healthy and communicative life. Assistive technology is either software, hardware or a combination of both that could be used by a person to access digital technology such as software, web pages or documentation. There are many types of assistive technology talked about in [Tools and Techniques (WAI)-W3C](https://www.w3.org/WAI/people-use-web/tools-techniques/#main). A few examples are screen readers that generate synthesized voice for people who are visually impaired or blind. This makes it easy to listen and interact with digital technology. Another type of assistive technology are screen magnification software to magnify the screen to help people with low vision see the screen more effectively. Lastly, speech control software helps people with mobility issues with their hands, preventing them from using a physical keyboard and allowing them to access and interact with digital technology by using their voice, or sip and puff devices. Sip and puff devices help people who may have other types of mobility disabilities and use their sip and puff device just like it was a keyboard.

People with eye impairments such as those who are blind and people who are both blind and deaf use a braille display to access digital technology by using their sense of touch to feel with their fingers and interact with the braille cells. Also, people who are blind and visually impaired can use a braille display to help reduce audio overload (screen reader user reading digital technology and taking notes, peoples voices on conference calls and one's own voice  when communicating with others). 

Since there are many assistive technologies that can interact with digital technologies, it is not needed to be an expert in any of these assistive technologies when designing and developing. Web Content Accessibility Guidelines 2.1 (WCAG) has made this step easier for you. When following these guidelines and perform manual evaluation as described below, most if not all assistive technologies should work effectively for the end-user. Basically, assistive technology works by programmatically interfacing with the digital technology. When accessibility is designed and developed using accessibility guidelines such as WCAG 2.1 without any syntax errors in the code this should help create a delightful experience for users who use assistive technology. This is true if you do not forget to evaluate the digital technology manually by people with a broad range of disabilities using a mix of different assistive technologies as talked about [in Involving Users in Evaluating Web Accessibility (WAI)-W3C](https://www.w3.org/WAI/test-evaluate/involving-users/). One should also complement this manual testing with automated testing to save time and to locate the issues that can be detected by software only. This does not require a real person to provide information that only a real person can detect. For example, if a certain element passed a WCAG Success Criteria, such as a hyperlink that is concise and descriptive, when reading out of context or if a graphical element has a meaningful alternative description.

@britt6612 Next week, can you review my changes and let me know if there's anything else you'd like to add? I'll let Bill know that you're going to review it and will send him the final changes. Please ensure the links are also included in the e-mail you send him. Thank you! :)

**Comment by britt6612** [comment]
When it comes to inclusivity and accessibility, assistive technology enables individuals with disabilities to live a more independent, healthy, and communicative life. Assistive technology is either software, hardware, or a combination of both that could be used by a person to access digital technology such as software, web pages, or documentation. There are many types of assistive technology talked about in [Tools and Techniques (WAI)-W3C](https://www.w3.org/WAI/people-use-web/tools-techniques/#main). A few examples are screen readers that generate a synthesized voice for people who are visually impaired or blind. This makes it easy to listen and interact with digital technology. Another type of assistive technology is screen magnification software to magnify the screen to help people with low vision see the screen more effectively. Lastly, speech control software helps people with mobility issues with their hands, preventing them from using a physical keyboard and allowing them to access and interact with digital technology by using their voice, or sip-and-puff devices. Sip and puff devices are used to help assist people who may have other types of mobility disabilities to use their keyboards.

People with eye impairments such as those who are blind and people who are both blind and deaf use a braille display to access digital technology by using their sense of touch to feel with their fingers and interact with the braille cells. Also, people who are blind and visually impaired can use a braille display to help reduce audio overload (screen reader users reading digital technology and taking notes, people's voices on conference calls, and one's own voice when communicating with others).

Since there are many assistive technologies that can interact with digital technologies there is no need to be an expert in any of these assistive technologies when designing or developing. Web Content Accessibility Guidelines 2.1 (WCAG) has made this step easier for developers and designers to follow. When following these guidelines and performing manual evaluation as described below, most if not all assistive technologies should work effectively for the end-user. Basically, assistive technology works by programmatically interfacing with digital technology. When accessibility is designed and developed using accessibility guidelines such as WCAG 2.1 without any syntax errors in the code this should help create a delightful experience for users who use assistive technology. This is true if you do not forget to evaluate the digital technology manually by people with a broad range of disabilities using a mix of different assistive technologies as talked about [in Involving Users in Evaluating Web Accessibility (WAI)-W3C](https://www.w3.org/WAI/test-evaluate/involving-users/). One should also complement this manual testing with automated testing to save time and locate the issues that can be detected by software only. 




## Not sure about the sentences below they are no clear to me what we are trying to get across.
This does not require a real person to provide information that only a real person can detect. For example, if a certain element passed a WCAG Success Criteria, such as a hyperlink that is concise and descriptive, when reading out of context or if a graphical element has a meaningful alternative description.

**Comment by britt6612** [comment]
sent to Bill to review
