### ISSUE TITLE
DataTable Page on DS site horizontal scroll issue

### ISSUE THREAD

**Issue by jcfilben** [grommet/hpe-design-system#3029]
When the DataTable page in the design system site is viewed on a narrow screen you can horizontally scroll past the content.

https://design-system.hpe.design/components/datatable?q=datata

https://user-images.githubusercontent.com/54560994/202801843-7102efa3-738c-42b9-ae80-8e123fd56f47.mp4

**Comment by ericsoderberghp** [comment]
I am still seeing this behavior with Safari on OSX:

<img width="354" alt="Screenshot 2022-12-12 at 3 45 48 PM" src="https://user-images.githubusercontent.com/11637956/207183777-ef87074c-afb0-4749-bca6-f2fb19999d71.png">

**Comment by jcfilben** [comment]
I'm on version 15.5 of Safari and I am not seeing this issue

**Comment by britt6612** [comment]
Im on 15.2

**Comment by britt6612** [comment]
Figured I would time box this issue since it is low severity:

However what I found was very strange and hard to debug in the production site of the hpe design system site it shows that there is a horizontal scroll on `DataTable` page due to some of the examples towards the bottom of the page having overflow, however on the local host it shows the examples being correct and it has a horizontal scroll due to the code block that is on the page.. @taysea added some `overflow` for the codeblocks so this overflow does not happen which is correct in the production site but showing overflow in the localhost.

not sure how we want to handle this ticket if we want to move it back to TODO: 
it also may be to the fact that we are on an older version of Safari
