### ISSUE TITLE
Navigation Pattern 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#305]
app, page, marketing, sidebar
	
sub-nav: app title, app name, nav(opt), search(opt), icon, anchor, button) Light/dark

**Comment by ericsoderberghp** [comment]
Some additional details:

- include desktop and mobile variants, especially mobile when multiple nav spaces are involved, like global + app
- something about how many navigation varieties should be visible at the same time. Avoid too much navigation chrome that makes for clutter and takes away from the task at hand
- have a few separate variants, rather than squeezing everything into one or two
- poker hand concept
- long reference document variant

Consider the following references:

- Server app design
- design system site design
- publisher.grommet.io, bar and card varieties

**Comment by halocline** [comment]
Closing due to staleness.
