### ISSUE TITLE
Tabs - revise styling based on branding refresh

### ISSUE THREAD

**Issue by L0ZZI** [grommet/hpe-design-system#3107]
Updated styling of the tabs component. 

Look at how the revised HPE Green impacts the component from and accessibility and usability perspective. 

![image](https://user-images.githubusercontent.com/86075038/198405273-a6631dd4-828a-4cc6-b6c0-0460cd78aecf.png)

## Deliverables

- [x] Evaluate design proposals shown and draft an update to the Tabs component in Figma
- [x] Review with the design system team
- [x] Include in the typography refresh to see how the changes feel in concert with the rest of the typography changes in the pipeline
- [ ] when settled, update grommet-theme-hpe with the changes

**Comment by vavalos5** [comment]
Connected with Keeth this AM during designer check in. We discussed the following as next steps:

- Icons swapping are text strong by default, Keeth to check with Chris and Matt on whether we want to solve for the future text styling or the present text styling
- create a pros and cons list on new direction of styling
- research on whether we should continue to align to our current buttons or if the new styling is the right way to go since its a different styling to our other components

**Comment by vavalos5** [comment]
@Keeth-HPe Can you help us by providing updates on this ticket and where you currently are please. Please connect with @SOjaHPE too. Thanks!

**Comment by halocline** [comment]
Jan 24 - @Keeth-HPe , @L0ZZI , and @halocline met to answer questions Keeth had regarding tabs work and refinement.

My takeaways from the conversation:
- Active tab will receive 'text-strong', 'bold' weight, and 'brand' green underline
- Inactive tabs will receive 'text', 'normal' weight, no underline
- Hover state of inactive tabs will receive an underline with a color value same as 'text' but should probably be part of the border namespaces in our design tokens
- Regardless of state, icon and font colors should be the same (see open questions below).
- Because of the active tab being bold, switching active tabs will cause a slight reflow of the tabs layout. Overall dimensions may grow or shrink slightly depending on label lengths. This should be negligible and unnoticeable since other content below the tabs will also be changing. We are not changing font-weight upon hover, so no reflow concerns there. 

Open questions:
- In Figma, how to handle icon colors changing between states? My understanding is that this is a problem when building the Figma component; in coded implementation, this is not an issue. My opinion is that icon and font color should match and we should not let a limitation in our design tool affect our desired design direction.
- Size of underline
- Amount of padding around tab label? Should it have horizontal padding? How does having/not having padding affect the look of tabs when presented below a heading? Within a specialized menu's drop container? Should the label be flush with the rest of the typography? Does padding cause it to be too ragged?

Next steps:
- [ ] complete exploration
- [ ] present exploration and recommendation to a subset of Design System team members
- [ ] document design direction decision
- [ ] create issue for implementation of Figma component
- [ ] create issue for implementation in HPE theme

**Comment by SOjaHPE** [comment]
@halocline  about your open questions above -

**Matt wrote:**
_In Figma, how to handle icon colors changing between states? My understanding is that this is a problem when building the Figma component; in coded implementation, this is not an issue. My opinion is that icon and font color should match and we should not let a limitation in our design tool affect our desired design direction._

That is tracked in the below ticket, the icon path name layers are not consistent across all the icon files, which means that the customization isn't persisted when the image files are swapped out. It is a bit of a boring exercise to get those cleaned up, something that should get done. 

For now, the work around is for figma designers to manually update the icon color as appropriate with the correct color. We should educate designers until it is addressed.

https://github.com/grommet/hpe-design-system/issues/2622

**Comment by taysea** [comment]
I had the theme updates running so I grabbed screenshots of the tab with horizontal pad vs none in a screen context to see with headings/page content:


### horizontal pad
![Image](https://user-images.githubusercontent.com/12522275/217056659-4fcad643-bd34-4e40-80c3-85b8e0cce968.png)

### no horizontal pad
![Image](https://user-images.githubusercontent.com/12522275/217056660-dcd12ca3-2436-44f9-b95c-8bec7159da03.png)

**Comment by Keeth-HPe** [comment]
@halocline @L0ZZI Based on our conversations here are my findings. Please share your feedback. 
https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/branch/p3Btu2OR2pkutAOI0dfjsr/HPE-Tabs-Component?node-id=4928%3A52451&t=zMprBVFrebepsbBL-1

@SOjaHPE

**Comment by ericsoderberghp** [comment]
I'm wondering if we should consider implementing the Tab itself as a `kind` of Button?

[This comment is not about the design but about follow on implementation work]

**Comment by halocline** [comment]
> @halocline @L0ZZI Based on our conversations here are my findings. Please share your feedback. https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/branch/p3Btu2OR2pkutAOI0dfjsr/HPE-Tabs-Component?node-id=4928%3A52451&t=zMprBVFrebepsbBL-1
> 
> @SOjaHPE

Hi @Keeth-HPe - Apologies for the delay on this. I left [comments in the Figma file](https://www.figma.com/file/p3Btu2OR2pkutAOI0dfjsr?node-id=4739:45221#366208121) next to the example showing the proposed tabs styling in the context of a page.

In the comments I wrote: "As I interpret this task (https://github.com/grommet/hpe-design-system/issues/3107), we are really wanting to answer 'Does the proposed tab style fit well when presented in context with the rest of the brand refresh typography updates? Are there any points of friction or inconsistency?'" and then provided some suggested steps needed for us to complete this answer.
- Apply the rest of the brand refresh typography changes to the example so that we can fully evaluate how the tabs work with the rest of the typography changes.
- Show an active tab other than the 1st tab so that we can see if the tabs controls are recognizable and how the fit with the rest of the layout.
- Answer "how much padding, if any, should tabs have?" Is raggedness of the left content edge an issue?
- Confirm hover and inactive states for inactive tabs.

Does this seem like the right question to be answering for this issue? If so, are these suggested steps the right ones to allow us to answer?

If we can see the items in the proposed steps, then I think we have the ability to answer the core question of this issue. Depending on the answer we then either:
- complete this ticket by:
- [ ] document design direction decision
- [ ] create issue for implementation of Figma component
- [ ] create issue for implementation in HPE theme

OR
- make an alternative recommendation, then complete the ticket with the steps above.

**Comment by Keeth-HPe** [comment]
Hello Team,
 I guess, since I moved the frame to the WIP progress Page, you were led to the old visual example. My bad
 My apologies @halocline @ericsoderberghp 
 
 Please refer to the document below where I have answered all the above questions and evaluated the proposed designs. 
 
 https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/branch/p3Btu2OR2pkutAOI0dfjsr/HPE-Tabs-Component?node-id=4998%3A53326&t=iJXxFhKi66sazOy1-1

**Comment by ericsoderberghp** [comment]
Further work to align with the overall brand refresh at a fine detail level will be tracked via https://github.com/grommet/grommet-theme-hpe/issues/308
