### ISSUE TITLE
Refactor container-driven layouts example to use Data

### ISSUE THREAD

**Issue by JCoder121** [grommet/hpe-design-system#3109]
Context: the Data refactor ticket was broken up into individual tickets per example. Refactor container-driven layouts example with Data component: https://design-system.hpe.design/templates/content-layouts#container-driven-layouts

**Comment by halocline** [comment]
Convo from Slack:

Good callout and observation. I agree that the visual design for vanilla DataFilters doesn’t seem harmonious.

Do you have a deploy link / draft PR I can peek at?

Here are the things I am thinking about:

- One of primary purposes of this example is to show how the layout responds based on various screen sizes, so I am interested how the vanilla DataFilters might be implemented for responsiveness? How it transforms from inline to drop? Need to revisit where the drop filter is placed?
- Are these screenshots in the “scaled” or “fullscreen” mode? I want to make sure that what I am seeing is not an artifact from something not coming through correctly in the scaled mode?
- In this context, the inline version of the DataFilters does feel kind of “boxy” whereas the custom feels more clean (the custom design was inspired/borrowed from the HPE GreenLake Marketplace product). What are the tradeoffs between cleanliness of layout vs. consistency in using a Form-like presentation for the filters? Are there design decisions we can make here? Should we (you and I) create a problem statement and success criteria to help guide and ground this discussion?
- Getting folks together for a half hour for you to demo/compare/contrast the differences. Hear their thoughts on what’s working and what’s not.

So with these thoughts :point_up:, I think we should:
- confirm scaled vs. fullscreen
- continue the implementation to try to consume DataFilters as is (including responsive layout aspects) so that we can demo the current state,
- list out our success criteria,
- list out items we’d like to see improved (e.g. do we need some greater control over DataFilters to affect its properties such as showing/not showing a heading? Specifying its heading level? Others?),
- facilitate a discussion with a broader cross-section of the team to share what we were able to achieve with vanilla DataFilters, share the aspects we think could use some improvement, listen to their thoughts and reactions.

**Comment by JCoder121** [comment]
3/22/23:

Blocked on https://github.com/grommet/grommet/issues/6701 for DataFilter functionality.
Will connect with Matt, Eric, and Taylor regarding design direction for drop down inline filtering menu.

**Comment by JCoder121** [comment]
4/19/23 status: on track 🟢 

Design direction: primarily focus on inline filters. I connected with team members and we agreed the point of this DS example is to show the container driven layout behavior with filters on the left and a grid on the right. The example keeps existing code that responsively changes the filtering layout according to breakpoint size (Filters Button when `breakpoint` is `small` or `xsmall`). Therefore, the filtering in this example is similar to the Inline filtering example found on Storybook [here](https://storybook.grommet.io/?path=/story/data-data-inline--inline). I agree with Matt's earlier comment about the Inline Filtering potentially being too "boxy" when compared to the custom-built FilterPanel. However, with the current way that Data is implemented combined with the idea that the example is meant to highlight responsive + grid behavior, I feel that this approach is acceptable.
