### ISSUE TITLE
Date Input - Create additional variants (small, large) in Figma

### ISSUE THREAD

**Issue by Keeth-HPe** [grommet/hpe-design-system#3145]
Based on DateInput - #3016

Tasks

- [x] Create a ' Small 'Variant
- [x] Create a 'Large' Variant
- [x] Review with Jessica & Vicky

**Comment by Keeth-HPe** [comment]
Based on DateInput - #3016

We need two additional variants. Small and Large 

Small: https://storybook.grommet.io/?path=/story/visualizations-calendar-simple--simple

Large: https://codesandbox.io/s/grommet-v2-template-forked-jkexx1?file=/index.js

**Comment by Keeth-HPe** [comment]
@jcfilben @vavalos5 

As per the story examples and grommet examples that were given by Jessica, I have worked on the calendar component.
Request you'll to please review both small and Large variants.  

Figma File : https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/yIz7w5Juq4ZUOZYvUTPYFX/HPE-Design-System-Components?node-id=980%3A18265&t=2tCLEYfhGKBgB5Ra-1

**Comment by vavalos5** [comment]
Thanks Keeth! It's looking great! I left a few comments on your Figma file. :)

**Comment by jcfilben** [comment]
@Keeth-HPe I added some comments to the figma file, let me know if there are any questions!

**Comment by Keeth-HPe** [comment]
@jcfilben 
Thank you so much for the review & comments.

As per discussion Jessica, I'm noting down the 3 things we would need clarity on and Jessica is going to check and get back.

- [ ] Does the green background for the range, be according to grommet (If yes, we have to break the color style in figma) 
or can we just use "Light/Validation ok" ?
 https://storybook.grommet.io/?path=/story/visualizations-calendar-range--range&globals=theme:hpe
 

- [ ] Currently, the dimensions of the button in figma cannot be accurately aligned as per grommet, as we have to break the button component to increase the icon size within. Should we continue using the buttons we have in our figma library or detach them and resize them accurately according to grommet/

- [ ] Font sizes are different by 1 or 2 pixels. In figma we do not have certain sizes, for example 18px and 14px for Text/normal. Should we break the styles or match the closet font size available in figma?

 @vavalos5

**Comment by vavalos5** [comment]
@Keeth-HPe are these questions directly to me or posted in general? I'd suggest chatting through these issues with Jessica to discuss solutions together.

I did leave some comments on your Figma file. Thanks!

CC: @SOjaHPE @ericsoderberghp

**Comment by Keeth-HPe** [comment]
> @Keeth-HPe are these questions directly to me or posted in general? I'd suggest chatting through these issues with Jessica to discuss solutions together.
> 
> I did leave some comments on your Figma file. Thanks!
> 
> CC: @SOjaHPE @ericsoderberghp


Hi Vicky, as mentioned on the same thread, these questions are something Jessica and myself discussed. I noted it down for Jessica to keep a track on. :)

**Comment by jcfilben** [comment]
It sounds like they may be a bit of confusion...
Keeth and I talk about the following:

1. The green background color for the range is using an opacity. Right now Figma doesn't have this color built in as one of the hpe colors. I was thinking that this is a conversation that the designer should have. Grommet has various places where we use the hpe colors but apply some type of opacity to them. How should this be supported in Figma? I thought this conversation was best left up to the designers since I am unfamiliar with what supporting various opacities would entail in Figma.

2. The 'next' and 'previous' icons for the large Calendar size are built in grommet using the 'medium' button and a 'large' icon within the Button. Keeth mentioned that changing the icon size when an icon is within Button is not currently supported. my thoughts are that this is something that we should be supporting in Figma but ultimately I will leave that decision up to the designers.

3. The font size of the date buttons are not aligned with our t-shirt sizing. I have opened a separate issue for this. https://github.com/grommet/grommet-theme-hpe/issues/322. For now I think a reasonable approach would be to set the text size in the Figma component to align with our t-shirt sizing until we get this resolved in the hpe theme.

**Comment by Keeth-HPe** [comment]
Thanks for the clarity, Jessica. Definitely was a little confused.
I would discuss this with the designers and get back to you.

**Comment by SeamusLeonardHPE** [comment]
Resurfaced do to our branch cleaning projects.
https://hpe-my.sharepoint.com/:x:/p/kenny_tran/EagZuftPiF9Hj2m-hR6hiMMBx1_aL8mrD9ZscMFTtQhAVQ?e=ghXMmX

Figma branch linked:

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/yIz7w5Juq4ZUOZYvUTPYFX/HPE-Design-System-Components?type=design&node-id=980%3A18265&mode=design&t=d4aAmhC13ttk3hZZ-1

Going to archive for now, as I would recommend rebuilding the component using atomic principles before expanding it into 3 size variations.

**Comment by SeamusLeonardHPE** [comment]
Closed as will be part of refactor in #3685
