### ISSUE TITLE
Help sidebar - create example implementation

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/hpe-design-system#3165]
- Create an example implementation of the 'inline' Embedded Help Panel that Gina has designed.
- Connect it up to the back-end TCaaS service providing the content to demonstrate it fully in action.
- Assume for now that individual pages are in charge of deciding whether to render this, that it isn't a separate stand-alone service in itself.
- A simple starting point: `<HelpSidebar topic={...} />`

## Acceptance Criteria

- [ ] code published to GitHub
- [ ] example published to Netlify to be used for demonstration purposes

**Comment by SOjaHPE** [comment]
@GinaTaylor using this ticket to track the In-App Contextual Help inline sidebar panel POC work targeted for our latest sprint that starts Mar 01, 2023

**Comment by MikeKingdom** [comment]
Update 3/10
- Standalone example created that uses hooks up to real support.hpe.com content from Joe Boyle.
- Both phase 0 and phase 1 examples working.
- Initial topic list is currently hardcoded since the API doesn't support a way to get that list (and probably won't in the Glasgow timeframe) Clicking on a topic displays the real content via a support.hpe.com url.
- Phase 1 example uses real support.hpe.com API (based on TCaaS) via a local proxy to show clicked on topic in the sidebar)
- Working on changes in GLCP to use the example help sidebar in its layout. Targeting Devices page first since that is what we have content for.

**Comment by SOjaHPE** [comment]
@chesleyratliff the work related to the in-app  'inline' Embedded Help Panel is being tracked here.

**Comment by MikeKingdom** [comment]
Update 3/13
* Initial example in GLCP (phase 0 with working content links):
![image](https://user-images.githubusercontent.com/12054362/224821365-b2f059fa-4837-4497-846c-43c477570387.png)
* Initial list of titles and resourceIds for TCaaS is currently hardcoded. Joe Boyle is working on a potential workaround to retrieve that information from TCaaS
* Chiranjib Halder is working on control option from the global header (global header is slated to come from a web component in Glasgow) He is also working out API proxy so we can properly call the API from GLCP
* There are responsive-ness issues to work out. Current breakpoints for GLCP pages don't account for space needed for a sidebar:
![image](https://user-images.githubusercontent.com/12054362/224822519-0adcb933-244e-4f59-8fa9-79c33b9b0ef6.png)
* details about when sidebar stays open or closes during navigation need to be decided/specified
* Behavior of modals needs to be investigated:
![image](https://user-images.githubusercontent.com/12054362/224823114-cad2c198-c489-46ad-b718-70054a97afcd.png)

**Comment by SOjaHPE** [comment]
@GinaTaylor / @chesleyratliff  some questions about the Embedded Help Panel behaviors -

* The Embedded Help Panel will be closed by default
* When the panel is open, and the user navigates and changes pages, what renders in the panel content area for those pages w/o defined content in Glasgow?
* Possible UX enhancements - consider the global hfs service 'light bulb' icon has a 'glow' state if the panel is closed and a page has contextual help content. Subtle affordance for this first release.
* As Mike mentions above, responsive-ness issues that will need to be addressed
      * currently GLCP doesn’t respond to xsmall or small view port breakpoints
      * need to dynamically set those breakpoints for the state of the Embedded Help Panel - whether open/closed 

These topics will be covered in today's tech deep dive session to review the end to end solution, Mikes proof of concept

**Comment by GinaTaylor** [comment]
@SOjaHPE 
In terms of which phase will be for Glasgow, I believe there have been some discussions on Product/Eng side around skipping phase 0 and building phase 1 for Glasgow. We need to confirm with @chesleyratliff and Joe Boyle.
Phase 1 has a list of topics and the actual topic/subtopic content displays inside the panel rather than linking out only:
![Screen Shot 2023-03-14 at 11 12 16 AM](https://user-images.githubusercontent.com/89482747/225068497-920cdd90-2f7d-4ef8-8aec-d582e0765cff.png)
*there are still a couple of open items for this design - like the use of icons in the cards and how those will be chosen (if we use them at all - it might be prudent to leave these off for MVP)

Here are my comments on behaviors from question above - 
- yes, the EHP will be closed by default
- if the user navigates to a new page, ideally the panel would remain open and the content would dynamically change with the page. For Glasgow I believe we will have ~10 different panel content options that will be linked to all of the GLCP pages. This might be an open item for now.
- we will not be using the lightbulb icon for the EHP in the header. We tested some new icons, and the icon that tested the best for this was a "book with question mark" - it is a new, hybrid icon created for testing. we would like to have it added into DS for this purpose. 
![Screen Shot 2023-03-14 at 11 02 43 AM](https://user-images.githubusercontent.com/89482747/225067331-bfa36955-dd8e-44f3-94f5-507d2d19c657.png)

![Icon-nopadding](https://user-images.githubusercontent.com/89482747/225066303-04f4e65d-c076-4050-afd9-fb91e844701c.svg)

- Responsiveness
 * We are aware that GLCP does not respond correctly at smaller breakpoints - including the header. We are working on revising the header to be responsive, but the actual GLCP pages will take more time. I had been working on possible responsive behavior of this panel for smaller breakpoints - does it just take over full screen? Not available at smaller? open in a new window? open in a overlay instead? Open to suggestions for short term and long term. (I know with GLCS, it opens inline on the page until 769px width, then at 768 and below opens full width - they also have some responsive issues and the help content would not load for me this morning...)
 
![Screen Shot 2023-03-14 at 11 04 03 AM](https://user-images.githubusercontent.com/89482747/225067641-6f9a9a33-e716-4bb0-b674-d55d967183e1.png)

![Screen Shot 2023-03-14 at 11 04 40 AM](https://user-images.githubusercontent.com/89482747/225066983-d03970c0-3202-4586-9ad0-23323929ae25.png)

**Comment by MikeKingdom** [comment]
Update 3/16
- Joe and I worked out a workaround to how we get the initial list of topics from the TCaaS API given a single resourceId. TCaaS is also looking at fixing/improving the 'pages' api to potentially provide titles and resourceIds as a more supported way.
- Working with Chiranjib on how this will be rolled out to other pages (initial example will be on Device Inventory page)
- We are sharing the work on a glcp branch as Chiranjib looks more at the global header and api proxy needs. For local dev mode and cypress tests the content will be simulated via Mirage (like all other api calls in the GLCP ui.)
- Still looking at options for how to handle modal popups while keeping the help accessible

**Comment by MikeKingdom** [comment]
Update 3/22
- Plans to decide by 3/27 if this feature stays Glasgow due to difficulties with how it interacts with Modals, Wizard and the new webcomponent global header being introduced in GLCP. 
- Current branch implements phase 1 designs
- Still have some issues to solve with modal/wizard interactions as well as responsiveness concerns.

**Comment by MikeKingdom** [comment]
Update 3/31
- Changed the main app to have its responsive breakpoints relative to its container rather than the full window. This basically means it at least responds like it would have if it was squished to that size by just the window when the help wasn't open. This makes it way easier to rely on whatever responsiveness was coded into the various pages without knowing about the help side panel.
- Still working on making modals only take over the main panel and not lock out the help side panel. We have a decent way to do this although it will likely require a change in grommet and glcp

**Comment by halocline** [comment]
PR submitted and in merge process.
