### ISSUE TITLE
Rich text editing - Create initial design direction

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3222]
Parent issue: #3331 

## Problem Statement

How might we provide users the ability to add/edit hyperlinks
within a TextArea so they can complete tasks quickly?
 

## Deliverables

- [x] gather use cases
- [x] research other similar text-editing examples
- [x] iterate v1
- [x] collect feedback
- [x] iterate v2
- [x] create examples utilizing iterations
- [x] collect feedback from Matt
- [x] collect feedback from Kurt and Kenny
- [x] make any last changes needed
- [x] create Templates
- [x] gather screens w/ screenreader output
- [x] annotate and create screen reader output w/ keyboard focus
- [x] share w/ Sylvia
- [x] share out

## Context

There is a need to support functionality which enable users in GLCP to insert links into a text string. Need a solution/proposal 

**Ideas:** Is this action supported by a contextual menu that appears after text is selected/highlighted or an action/control adjacent to the textarea. Dynamically display an input 'url' field under the text area?

- [ ] #3287
- [ ] #3288

PROVIDED by GLCP - User actions: Highlight word or phrase which begins as text --> click button --> display formfield input --> specify a URL or file path --> save --> turn the highlighted text into an anchor.

**Comment by halocline** [comment]
Recommend considering a pattern similar to that implemented in Slack when applying a hyperlink to a subset of text.

![Screenshot 2023-03-20 at 2 27 09 PM](https://user-images.githubusercontent.com/1756948/226458210-123fbf0b-0fa5-4259-8804-e7c2b34676ca.png)
![Screenshot 2023-03-20 at 2 27 17 PM](https://user-images.githubusercontent.com/1756948/226458245-ab4d2f36-0723-4a18-9eb8-6998887ab56b.png)
![Screenshot 2023-03-20 at 2 27 37 PM](https://user-images.githubusercontent.com/1756948/226458357-f37f4ee0-9dd5-436b-b5d7-dee095c09c24.png)

**Comment by vavalos5** [comment]
4/14- I've begun this yesterday afternoon by collecting the use case from Sylvia. Will be reaching out to other teams to see if they have similar needs.

**Comment by vavalos5** [comment]
I've began a set of explorations on how we might handle adding a [link to text within text area.](https://www.figma.com/file/evH1LQewFPc8Y2fteywMxM/HPE-Text-Area-Component?node-id=3095%3A13649&t=13z4y2atkzwrxWtc-1)

Note i've explored having the 'attach' icon on the:

- top-left
- top-right
- bottom-right

I've also explored 2 different background colors of where the link button lives:

border-weak
background-contrast

This is due to the fact that this component could be placed on our `background` or `background-back` backgrounds.


Looking to get some feedback @halocline @KennyAtHPE 

Thanks! 😄

**Comment by halocline** [comment]
Thank you for the updates @vavalos5. Nice to see the different explorations and states.

A few quick reactions:
- I'm wondering if the [Link](https://icons.grommet.io/?s=link) icon would be more appropriate than the paper clip / attach icon?
- I tend to lean towards the button placement in the top as that seems consistent with most text editors I am familiar with. And a slight preference for top-left which might be more discoverable because of F-pattern.
- background-contrast seems like the right direction to go and consistent with its intended use.
- RE: Highlighting with keyboard - I believe shift + arrow keys are the keyboard controls.
- Many text-editors will also provide a keyboard shortcut (e.g. Cmd + shift + U, Cmd + k) but are inconsistent. Can we include a) what the shortcut should be and b) a tooltip hover state?
- Once the link has been added, should the anchor color be text-strong?

**Comment by ericsoderberghp** [comment]
Nice to see the the variety of research examples!

I'm wondering how the user would come to know how to interact with this.
- What happens if nothing is selected and the user clicks on the link icon?
- What happens if the user is editing the other text in the text area after adding the link and puts the cursor in the middle of the link and starts typing or using the backspace key?
- How does the user edit the link after it has been initially created?
- If the user types or pastes something that looks like a URL, how do they add a label to it?

Button placement might be easier to contemplate if we could see it in the context of an entire page. I'm wondering if top right would feel better if there are other form fields around who also have control icons on the right side.

**Comment by vavalos5** [comment]
Thank you @halocline and @ericsoderberghp for the feedback!

I've considered all of the above minus the keyboard shortcut as i'm going to be connecting with Bill to better understand this.

In the mean time, i've added all of the [different states and annotated the visuals](https://www.figma.com/file/evH1LQewFPc8Y2fteywMxM/HPE-Text-Area-Component?node-id=3095%3A13649&t=g6wfco7u5QsECQm7-1).

I've also applied the current designs in a [GLCP context example](https://www.figma.com/file/evH1LQewFPc8Y2fteywMxM/HPE-Text-Area-Component?node-id=3114%3A14440&t=g6wfco7u5QsECQm7-1).

Let me know your thoughts 😄

**Comment by vavalos5** [comment]
@halocline I've reviewed your comments and made small changes. Once we confirm this is good for iteration, i'll transfer the examples to it's own Rich Text Editing page where it'll live as a template rather than a component. Reasoning I don't want to transfer it yet is due to our comments/collaboration on this page - sadly they don't transfer.

**Comment by vavalos5** [comment]
Walked Kenny and Kurt through the designs i've created and felt like we might be able to create 1-2 more different examples when editing text. Will create those and collect feedback.

**Comment by vavalos5** [comment]
4/28 Update - Similar to yesterday, will be creating a few other options to consider. Next steps would be to start keyboard, mouse, screen reader annotations.

**Comment by vavalos5** [comment]
5/2 Update- shared out with team. Devs feel there is enough information to create an implementation and test with Bill.

**Comment by halocline** [comment]
Based on the share out today, this work provides initial design direction and recommendations. Next step is to create an interactive prototype to work out and refine interaction details, behaviors, keyboard/mouse/screen reader interactions and is represented by #3332.

@vavalos5 , I am good with closing this issue. Great job. Thank you.
