### ISSUE TITLE
Map - Create Marker and Clusters, and zoom in/out into components

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3377]
- [x] Based off of the work Chris and Joelle did, recreate markers and clusters into components and variants.
- [x] Get a review from Kenny
- [x] Kurt to create zoom in/out and reset components
- [x] Get review from Kenny
- [x] Kurt to review with Chris

**Comment by vavalos5** [comment]
Clusters can be found [here](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=459%3A66511&t=jPgAsQl48cAUh1GV-1).

**Comment by L0ZZI** [comment]
On the 'ok" clusters is there a reason we're not showing an icon, like the others? I think the removal of that would lead to them being more washed out. But, we spoke about it having a ok status color as a stroke in our exploration—I would say that's a good solution as well. Best might be both but it really depends on how strong you want the "ok" elements to compete with the rest of the status.

With regard to the holiday theme 😂, I have to ask whether we would show all of them at the same time? If it's showing all resources in any status, I would think that's a canvas-like fullscreen experience used to navigate. I thought the MVP was to target to highlight specific clusters by specific status? My assumption is the map would be used for critical and warning status as a primary focus. I know we have a generic styling for location points (or a more generic style for the cluster bubble) on the map that I would probably use if we're just trying to call out the sheer number of resources. 

All is to say. I think by downplaying the 'ok' status clusters is okay if the there is enough contrast and the use is to see the red. Otherwise I would just change the map styling to a non-status based style. (see attached image)


![Image](https://github.com/grommet/hpe-design-system/assets/1753301/5532808b-687c-4c32-96f4-b2debced0cb5)


The only other aspect I would maybe look at is the direction on the buttons, you might want horizontal version. The minus looks a little odd below the plus and you might have layout where vertical space is a commodity.

Other than those comments, it's looking really good!

**Comment by vavalos5** [comment]
@kurt-ph Please review Chris's comments as well. Let me know if you have any questions.

**Comment by vavalos5** [comment]
Based on feedback from Chris, the following to be completed today:

**Vicky**:

- Do we want to have both the ok icon and the ok stroke? Chris was asking why don’t we have the ok icon. He mentioned both might be good but depends on how strong we want the ok element to compete with the rest of the status.


**Kurt**:

- Chris had asked whether we’d be showing all of them at the same time? He thought the MVP was to target and highlight specific clusters by specific status? The thought it to have the map show and be used for critical and warning statuses as the primary focus. Please create a map version more aligned to this ask.

- Use a more generic style for the cluster bubble on the map that would call out the most amount of resources. Please reflect this on the map examples.

- In regards to the buttons, we should explore a horizontal version. Chris felt the zoom in/out buttons looked odd - specifically the minus being below the plus. There might instance where vertical space is limited and needs accommodation. Please make explorations.

**Comment by vavalos5** [comment]
Clusters with status "ok" icon now have the icon implemented into them. They can be found [here](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=459%3A66511&t=Bdwon8Azh3ttwlG1-1). @L0ZZI FYI

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/73f29b64-2cbd-453f-a476-92e8e43d10b7)

**Comment by vavalos5** [comment]
Matthew from GLCP is sharing feedback w/ us on feedback he’s gotten on Maps from his POMs:

- The following are interactions they’re expecting that need to reflected on the data: city level, the state level and the country level. Is this feasible? How are we displaying the data. How is data going to be defined? How many clusters?  Looking for an answer by October (this is WIP for October).
- I mentioned that I’d assume this is something more defined in the API rather than something we’re specifically defining. @SOjaHPE @halocline do we have an idea of which Map we'll be utilizing to provide Matthew and his POMs with some answers? Also, wanted to know if my answer i've provided him is the right answer or if this is something we'd be defining/can be defined by teams within the API?

- Another concern is that people aren’t getting the status icons such as the diamond, the triangle and the circle. POM are saying that the markers and clusters aren’t resonating w/ the icons. I mentioned icons are needed for accessibility and to meet WCAG standards. In addition I went into detail what the different shapes mean and how they’re standard to help those with color impairments. They wanted to know if there was another treatment.



![Image](https://github.com/grommet/hpe-design-system/assets/62117454/23536cad-b48d-42db-9d67-2a3d3a6c8644)
- ^ The map - a lot of people can’t tell the difference between the markers and the clusters. POMs are saying they wouldn’t recognize or tell the difference between a red cluster with a number. I mentioned the direction is a common experience across different maps and people know that when they view clusters, these are larger data sets clustered together to delve further into where as markers are singular data sets that you can still delve into, just depends on how zoomed in you are. This also sounds subjective.

- Matthew mentioned that they’re going to take it back to the customer and get their feedback. I wanted to understand further how that works so I asked how do they do that. He said they’d have to do user research and take it to the user to test it out. Matthew’s approach is to reach out to Katy’s group and get users to delve further on how this approach is working for them. But perhaps we can get some traction from users at Discover.

**Comment by kurt-ph** [comment]
Had a Sync with Mattew:

**Comment by kurt-ph** [comment]
Updates from our last meeting.

PM wants to see, I think we need more clarification on the city level. Since it seems subjective on how we close we get to the zoom level. Would it be the entire city boarder or zoomed in sections focused on different parts of the city. I think it would be beneficial to define that to see the use of clusters and markers used here. So will need to look into that & hear back from Matthew on that.
    - City level
    - State level
    - Country level
    
Also Chris mention, it could be confusing to see the OK cluster. But have a critical or warning items in it. There needs to be  a better way to view or filter that. As seeing the OK cluster, some items can get lost in translation. Users might have to utilize search or filtering to narrow down to critical status only for example. Just something to think about.

**Comment by vavalos5** [comment]
@kurt-ph Based on the last feedback you received from Chris, was there anything else that needed attention in regards to this specific ticket?

In regards to Chris's comment, based on the research I’ve done, this was the direction I’ve seen on data sets. I know it would be confusing to not be able to see 2 critical clusters if the other 100 are ok and the cluster itself is a green ok cluster. Perhaps we can make an exception? Research conducted states that the color of the cluster should be reflected on the largest set on data. Like a heat map. @L0ZZI 

@SOjaHPE Were there any other dependencies for this? If there aren't any other pending things, then we can close this ticket.

**Comment by vavalos5** [comment]
@kurt-ph Did Chris say anything about the zoom/in out and reset buttons?

I went through our Figma file and didn't see the comments Chris left that you mentioned, can you point me to those please.

**Comment by kurt-ph** [comment]
He didn't comment on the zoom/in out. I only tagged @L0ZZI for visibility.

**Comment by vavalos5** [comment]
Similar to what Mike mentioned during share out yesterday, icon size don't necessarily have to meet accessibility as long as the button meets the 22px x 22px width and height to meet Level AA. This means, what we currently have implemented meets our Level AA accessibility standards.

Including some research below.

http://kb.daisy.org/publishing/docs/html/images-icons.html


![Image](https://github.com/grommet/hpe-design-system/assets/62117454/9f961602-9b61-497a-9078-c6a801d65b5f)


https://w3c.github.io/wcag/understanding/target-size-minimum.html


![Image](https://github.com/grommet/hpe-design-system/assets/62117454/cf9fe3aa-0db8-496b-a2a4-ca9cccc6b1ea)


![Image](https://github.com/grommet/hpe-design-system/assets/62117454/68161903-8f51-4c10-8551-3ab3103261c0)


Closing as done. 😄
