### ISSUE TITLE
Map - Confirm styling for default/neutral marker

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3431]
**Deliverables**
For use cases where status is not present (primary use case is HPE GreenLake Platform devices page, where devices do not have status):
- [x] Confirm the default / neutral styled location marker styling, ensure it is documented in Figma, and add link here
- [x] Confirm the default / neutral styled cluster marker styling, ensure it is documented in Figma, and add link here

**Comment by kurt-ph** [comment]
Hi @halocline can you provide me with a link to the **HPE GreenLake Platform devices page** so I can see it as a reference?

**Comment by kurt-ph** [comment]
Here is my updates on earlier exploration. I tried all the possible neutral colors from our HPE Library and find different ways it can be displayed on the map. Explored various options before defining styling for clusters/markers.

![Neutral_1 - Exploration ](https://github.com/grommet/hpe-design-system/assets/130700747/e9815e2c-f133-4317-98dd-7356e5c55203)

**Comment by kurt-ph** [comment]
After feedback and discussion, I furthered defined the markers + clusters we can possibly use on the Map UI. The challenge with exploring color is we don't want the user to be confused thats it's another status. So my recommendation would be to stick the monochromatic palette. I took the time to explore other color neutrals, if that is a direction we want to take.
![Neutral_2 Define](https://github.com/grommet/hpe-design-system/assets/130700747/2fec7fc5-a4de-49a1-8b02-e4ac5e4b25c1)

**Comment by kurt-ph** [comment]
Here is the different variations I explored and how the markers would look on the Map:
- Neutral Light
- Neutral Dark
- Neutral Color

![Neutral - Light](https://github.com/grommet/hpe-design-system/assets/130700747/086d716f-5cf7-4872-a9fd-3eb287c65fdf)
![Neutral Dark](https://github.com/grommet/hpe-design-system/assets/130700747/f693826b-45bd-4a7a-9e59-4b74fcf8df2a)
![Neutral - Mixed](https://github.com/grommet/hpe-design-system/assets/130700747/f1baebeb-fcec-4491-860c-44ada6fa83b9)

**Comment by kurt-ph** [comment]
@halocline Would like your feedback on this when you get the chance. Open to ideas & suggestions you have on this.

Default / neutral styled location Marker & Cluster styling: Recommendations
![Recommended - Neutral](https://github.com/grommet/hpe-design-system/assets/130700747/1b6cc2ba-9731-43c4-9380-ea764ef7451a)

Figma link:
https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1%3A23&mode=design&t=l4qgK0zVfYyGBgND-1

**Comment by kurt-ph** [comment]
@halocline @KennyAtHPE @SeamusLeonardHPE 

Thanks for all the feedback and suggestions. Seamus had the right direction in mind, so taking that feedback into consideration. I think Kenny's feedback is valid, it's confusing if hovering over the marker and it turns into another outline, which isn't clearly communicated that it's a hover since it does not contrast well enough distinctively on the map.

I made a quick prototype of the hover state I'm thinking of going with both the clusters & markers. You don't have a bunch of dark clusters/markers that is overpowering the map. But the dark fill states works great as a single hover interaction. Open to thoughts and feedback on that.

Neutral Prototype:
[](https://www.figma.com/proto/bMVkdgHkimCENGHiKPGcYH/Maps?page-id=1%3A23&type=design&node-id=1087-90339&viewport=-48629%2C-7584%2C0.73&t=JRwW6Ncf67QI2PzU-1&scaling=min-zoom&starting-point-node-id=759%3A70416&mode=design)

**Comment by kurt-ph** [comment]
@halocline @KennyAtHPE @SeamusLeonardHPE @vavalos5 

Some feedback from the show and tell. Having a filled interaction for hover might introduce some inconsistencies for the current status markers we have. An option that was presented during feedback was the possibility of scaling the neutral cluster/markers as another option. Current problem with the current hover state now is the lighter shade isn't visible to users as they hover over it.

I've included some iterations & prototype here to review and we can try it out on different views of the map: Could't get the hover effect to scale from the center, but this is the closest I got it to.

Map 1: Country Macro View
https://www.figma.com/proto/bMVkdgHkimCENGHiKPGcYH/Maps?page-id=1%3A23&type=design&node-id=1178-91177&viewport=-24138%2C-4461%2C0.38&t=a7NKSC0HymhfqOSK-1&scaling=min-zoom&starting-point-node-id=759%3A70416&mode=design

Map 2: Multiple States View
https://www.figma.com/proto/bMVkdgHkimCENGHiKPGcYH/Maps?page-id=1%3A23&type=design&node-id=1182-91222&viewport=-24138%2C-4461%2C0.38&t=69MoY3tfShCTiCjA-1&scaling=min-zoom&starting-point-node-id=759%3A70416&mode=design

Map 3: State View
https://www.figma.com/proto/bMVkdgHkimCENGHiKPGcYH/Maps?page-id=1%3A23&type=design&node-id=1182-91227&viewport=-24138%2C-4461%2C0.38&t=BlkUYPhNP7XTLR9S-1&scaling=min-zoom&starting-point-node-id=759%3A70416&mode=design

Map 4: City View
https://www.figma.com/proto/bMVkdgHkimCENGHiKPGcYH/Maps?page-id=1%3A23&type=design&node-id=1182-91278&viewport=-24138%2C-4461%2C0.38&t=uTocXUGNAjUIA9jT-1&scaling=min-zoom&starting-point-node-id=759%3A70416&mode=design

![Scaling Markers:Cluster](https://github.com/grommet/hpe-design-system/assets/130700747/48b6e340-e6b8-4a56-bda2-350cddb40eaf)

**Comment by vavalos5** [comment]
Kurt, thank you for making these prototypes. I can see the challenges you've faced when creating these. Upon reviewing the ones the Seamus created, I think that's the direction we'd want to head towards. I did see the two options you've created @SeamusLeonardHPE and feel like the first example where the hover affect is applied makes more sense than the color change. The color change was difficult to see since the grays are so much alike. If I was a person with a color impairment, I probably wouldn't be able to distinguish between the two grays on hover. However, the hover affect where the cluster becomes larger is much easier to see. Nice work both of you here!

**Comment by kurt-ph** [comment]
@halocline 
Hi Matt, this ticket is pretty much done. I've had designers & Seamus look at the map for review. I even included the prototype for the Neutral Clusters/Markers and did a review for that as well. This is the direction I've came up with after feedback and iteration and feel this is ready to go. So for now, closing this ticket as this is complete.

If you have any further questions or things you like me to include. Let me know.

I've included the links for reference below:

Prototype flows for each Map Level:
https://www.figma.com/proto/bMVkdgHkimCENGHiKPGcYH/Maps?page-id=1%3A23&type=design&node-id=1213-91616&viewport=-23936%2C-5447%2C0.37&t=jEFbhq8Sy3KqG7Oa-1&scaling=min-zoom&starting-point-node-id=1213%3A91616&show-proto-sidebar=1&mode=design

Neutral Cluster/Marker Stylization can be found here:
https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1%3A23&mode=design&t=4rAXHGIoflqIqMGp-1

**Comment by taysea** [comment]
Follow on work: https://github.com/grommet/grommet-leaflet/issues/25
