### ISSUE TITLE
Multiple sections or subsections - Where do we place buttons when there are multiple sections?

### ISSUE THREAD

**Issue by vavalos5** [grommet/hpe-design-system#3445]
Related to #3387

This question came up during GLCP Crit. Edgar wanted to know if the placement of the button is correct or what design system's guidance is when there are multiple sections or subsections where buttons are needed. Including [Figma link](https://www.figma.com/file/9JDPwHsK6dnut8HWXtsdOb/branch/1GmOWvQBhlmyMbftWww0Xr/API-Management?type=design&node-id=4600%3A56289&mode=design&t=jA5GFSpIFby6YPrV-1) and example below.
![Screen Shot 2023-06-27 at 11 24 12 AM](https://github.com/grommet/hpe-design-system/assets/62117454/5fff8e09-59a2-4de9-9932-4f73b1a1d80a)

Acceptance Criteria

- [x] Gather additional use cases for vertical sections
- [x] Research best practices for button placement
- [x] Create recommendations for button placement for section headers, inline and table areas
- [x] Create follow on ticket to socialise Guidance.

**Comment by SeamusLeonardHPE** [comment]
Rough draft of problem statement & initial discovery document using templates. 

Will add in feedback from [#3387](https://github.com/grommet/hpe-design-system/issues/3387) which is in review currently.


https://www.figma.com/file/87VrlH5EXRGD8fwytABQeD/Button-Placement----Multiple-sections-%233445?type=design&node-id=0%3A1&mode=design&t=BFanDQlXKHOpeaCY-1

**Comment by SeamusLeonardHPE** [comment]
After looking though the design system guidelines,  discussion with Edgar on usage, and creating multiple research examples I concluded:

1.    There is no current design system documentation for “Section Headings” outside of H2 styles.
2.    His example is the best approach, as it follows table width guidelines, and similar to the “PageHeader” component, it right aligns the related “action” that can be carried out on that section. In addition to this, when [I tried a ‘left aligned’](https://www.figma.com/file/87VrlH5EXRGD8fwytABQeD/Button-Placement----Multiple-sections-%233445?type=design&node-id=34-3953&mode=design&t=QIHQynGTx9LME6bo-4) alternative the buttons did not stand out as clearly due to being crowded with other page content. 
 
Question raised. 
1.    Is guidance documentation in the guide enough to resolve this or…
2.    Should a “SectionHeader” component be created in figma, with suitable use cases along with documentation in the guide.
 
Recommended guidance.
1.   At any ‘pageSection’(as indicated by a H2), where an applicable ‘action’ can take place, any button or overflow menu should be aligned to the right of the containing div.




![Image](https://github.com/grommet/hpe-design-system/assets/135040188/41121ddd-3083-4ec6-9bb9-6c9aa7b13b07)
![Image](https://github.com/grommet/hpe-design-system/assets/135040188/d907f889-1710-4ec3-89e2-667bdd47dcd7)

**Comment by MikeKingdom** [comment]
I still question that the button should be right aligned. Pages like the bottom example seem to be aligning to the right based on the immediate content and not necessarily the entire page look. How this looks and where your eye goes is very dependent on this ragged variation in content.

In most cases it makes alot more sense for the button to have 'locality of reference' where it's right next to the thing you care about. If it gets pushed too far right you may not even notice it's there.

For tables, it helps to have actions on the right side and most people are used to that and I'm not convinced we have to have all cases right or all cases left here.

I also have concerns about giving guidance for responsive-ness since we've run into big problems with these types of examples on smaller screens

**Comment by taysea** [comment]
@SeamusLeonardHPE In sprint demo today, we discussed how it would be helpful to have a 30-min call with various folks on the team to have a more focus, synchronous review of this work. Can you find a time for this session with our team?

**Comment by SeamusLeonardHPE** [comment]
@SOjaHPE @KennyAtHPE 

Added in questions that arose during our calls & swarm regarding - section type, button alignment, button action.

I'd appreciate input on the direction, and who else I should socialise this will to discover other use cases,  and answer some of the questions that have arisen.

https://www.figma.com/file/87VrlH5EXRGD8fwytABQeD/Button-Placement----Multiple-sections-%233445?type=design&node-id=164-17601&mode=design&t=NwoEsJyrIaHXzBuJ-4

**Comment by vavalos5** [comment]
Nice work Seamus! I left some comments on your Figma file.

**Comment by SeamusLeonardHPE** [comment]
Added in a 2 sections first with interactions & second with experiments on page layout options including

- Using tabs instead of sections
- Using bgback & bgfront to differentiate sections
- Added section action into data collection toolbar where applicable

https://www.figma.com/file/87VrlH5EXRGD8fwytABQeD/Button-Placement----Multiple-sections-%233445?type=design&node-id=190-28082&mode=design&t=TgD5LOvoLppoc1D0-4


Shared with Sylvia, Bhim and Betty, will update based on feedback asap.

**Comment by SeamusLeonardHPE** [comment]
Additional experiment from Betty Davis

**"here is an exploration consolidating Client ID and Secrets, which can go together"**

This example also shifts the "Generate code sample" modal on to the page right columns.


https://www.figma.com/file/1GmOWvQBhlmyMbftWww0Xr/Helsinki-Updates--Created-June-16-2023?type=design&node-id=5119-7779&mode=design&t=Etra88xY8RTopcxV-4

**Comment by SeamusLeonardHPE** [comment]
Updated my recommendations for section level button placement based on my research & suggestions for follow on work.

https://www.figma.com/file/87VrlH5EXRGD8fwytABQeD/Button-Placement----Multiple-sections-%233445?type=design&node-id=288-48596&mode=design&t=HQVxTXLNOV41uY5z-4

**Comment by SeamusLeonardHPE** [comment]
Follow up ticket created [#3500](https://github.com/grommet/hpe-design-system/issues/3500)

**Comment by SOjaHPE** [comment]
This ticket can be closed out, the next steps will be tracked by the two follow on tickets: [#3500](https://github.com/grommet/hpe-design-system/issues/3500) and  [#3501](https://github.com/grommet/hpe-design-system/issues/3501)

**Comment by SOjaHPE** [comment]
closing the ticket
