### ISSUE TITLE
Test how filters present all value types (e.g. string, number, date, time, array of options)

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3588]

**Comment by taysea** [comment]
https://codesandbox.io/s/datafilters-default-behavior-4l2t4q?file=/src/App.js

String:
- If < 5 options, CheckBoxGroup
- If >= 5 options, SelectMultiple

Date (special case string):
- Follows same rules as string for CheckBoxGroup vs SelectMultiple
- Renders timestamp, currently no ability to provide custom label render.
- Would be nice to either be able to customize the label render to a more user friendly format and/or be able to present as a DateInput range depending on the use case

Number: RangeSelector
- As noted in CodeSandbox it appears there must be a bug in the sorting of numeric options because the range is not reflective of the data.

Time (as milliseconds timestamp, number):
- Follows same rules as number.
- Would be nice to be able to customize the rendering of the labels to a user friendly format
