### ISSUE TITLE
ReadOnly - Review and incorporate read only input contribution from Greg

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#3607]
ToDos:
- Review Greg's proposal for "read only input"
- Make recommendation to adopt or not
- Make recommendation as to where the contribution should live (component vs. template)
- Review with developer(s) to discuss anatomy and potential API
- Others?
- Create follow on issues as appropriate for:
  - Adding "read only input" to design system site / updating guidance / auditing instances within site
  - Publishing to Figma library

------------------------------------------------------
Reach back out to Marina C. once the component has been updated, she brought this up in OH 12/14

**Comment by SeamusLeonardHPE** [comment]
For context, original discussion came up in Office Hours and a comment was later placed in hpe-hesign-system slack channel

https://hpe.slack.com/archives/C04LMJWQT/p1698437048781699

Proposed design changes/updates.

https://www.figma.com/file/GoSOHXCTKF3hXsIpYq0cNo/Text-Input-proposal?type=design&node-id=0%3A1&mode=design&t=bD5DOdinwxJCQtDU-1


Notes on initial discovery.
- Should 'read only' be grouped with other 'state' variants, not seperate boolean, since html input cannot be both disabled & ready only?
- Should the 'value + disabled' be fixed (for user entered field that cannot be updated after submission, eg username)




![Image](https://github.com/grommet/hpe-design-system/assets/135040188/23e38c7e-cd5c-4618-8b14-153f0d547678)

**Comment by KennyAtHPE** [comment]
1/3 Update:

**Deliverables**
- [x] Review Greg's proposal for "read only input"
- [ ] Make recommendation to adopt or not
       - **Sharing out to team for feedback on options** 
- [x] Make recommendation as to where the contribution should live (component vs. template)
       - **Input components to be be updated appropriately with updated readonly styling. Inputs with no current readonly variant must also be updated**
- [ ] Review with developer(s) to discuss anatomy and potential API
Others?
        - **Connecting w/ dev to test 2-3 designs**
- [ ] Create follow on issues as appropriate for:
      - [ ] Adding "read only input" to design system site / updating guidance / auditing instances within site
      - [ ] Publishing to Figma library

---------------------------------------------------

[Working Figma file](https://www.figma.com/file/vsPmzaKYVd5ZmxYK4os12j/Readonly?type=design&node-id=0%3A1&mode=design&t=iqEAVEC1j0aFmJ8j-1)
- [Research](https://www.figma.com/file/vsPmzaKYVd5ZmxYK4os12j/Readonly?type=design&node-id=24%3A6417&mode=design&t=iqEAVEC1j0aFmJ8j-1)
       - Some readonly examples and notes from/on Outlook, Github, Shutterfly, and Carbon
- [Explorations](https://www.figma.com/file/vsPmzaKYVd5ZmxYK4os12j/Readonly?type=design&node-id=25%3A8805&mode=design&t=iqEAVEC1j0aFmJ8j-1)
       - Pinging for review @SeamusLeonardHPE @L0ZZI @jcfilben (would love to get your thoughts on any accessibility concerns)
- [WIP Recommendations](https://www.figma.com/file/vsPmzaKYVd5ZmxYK4os12j/Readonly?type=design&node-id=24%3A6405&mode=design&t=iqEAVEC1j0aFmJ8j-1)

**Comment by jcfilben** [comment]
Codesandbox demonstrating various readonly styling options: https://codesandbox.io/p/sandbox/grommet-v2-template-forked-y6tdjr?file=%2Findex.js%3A128%2C19

**Comment by KennyAtHPE** [comment]
Shared out with the team during the demo internal yesterday. Follow on [ticket](https://github.com/grommet/hpe-design-system/issues/3635). Closing out this ticket.
