### ISSUE TITLE
Document & tidy Figma branches

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3608]

**Comment by SeamusLeonardHPE** [comment]
Purge outdated branches.

Document any branches with "to be completed" work.

Merge any branches with completed signed off work.

More detail to follow regarding processes.

**Comment by halocline** [comment]
Is this work all achievable in a single sprint?

**Comment by SeamusLeonardHPE** [comment]
@halocline I believe this is achievable within a single sprint.

I've screencapped all the library files that have branches in the figma file below.

https://www.figma.com/file/CZQyr4ghARJuXRQE7Sftk7/%233608---Document-%26-Tidy-Figma-Branches?type=design&node-id=0%3A1&mode=design&t=IdyFUDE8Sqr2ut2k-1


Additional outcomes I would expect from this ticket:
- [ ] Recommendations for branching naming convention
- [ ] Recommendations for improved deprecation process (eg can we have multiple versions of a component? v2 & v3 active in the figma file as a way of phasing in new components)
- [ ] Further the conversation about ingesting non-refactored components into the "HPE Design SystemComponents" file
- [ ] Connect with @oliverHPE on his plans to improve "fit and finish" on the "HPE Design SystemComponents" file 


In back of mind for this ticket, how can findings & discussion further the following goal:

Reduce files in the figma library to 2:
1- Components
2- Template library

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE created an [Excel Sheet](https://hpe-my.sharepoint.com/:x:/p/kenny_tran/EagZuftPiF9Hj2m-hR6hiMMBx1_aL8mrD9ZscMFTtQhAVQ?e=ghXMmX) detailing all of the current branches, people responsible for them, their status, and links to relevant tickets.

I will be reaching out to all branch contributors to double-check that the statuses displayed are correct.

-----------------------------------------------
### Recommendations

**Recommendations for branching naming convention**
- I recommend that all branches follow this naming convention: (Ticket#)(Affected component) - (Brief description)
      - Ex. #3608 Checkbox - Text color change
- I also recommend that we create a brief template for the author to fill out including ticket link, deliverables, required reviewers, etc.
      - This should live on the FIRST page of the file since this is the default page when opening a branch. 
      - Would significantly help us keep track of older work and responsibility.

 
**Recommendations for improved deprecation process (eg can we have multiple versions of a component? v2 & v3 active in the figma file as a way of phasing in new components)**
- I'd heavily advise against this since every new version would have to be a completely new master component which would be very hard for users to update their files. This would also be very difficult for us to maintain. In a perfect world, we shouldn't be building our components with the thought of having to deprecate them in the future. Instead, let's build our components so that they are scalable for future updates.
- We could maybe do this by using the collections feature within variables. TBD but I'm assuming this is still not worth the effort of creating multiple versions of components.

**Comment by SeamusLeonardHPE** [comment]
Thanks for documenting and sharing the branch status - I'll add some comments on branches Im aware/responsible for.

Regarding the 'brief template' Im feeling that would be best placed in Github, since it will be discoverable via the branch/file name. Suggested workflow below:

1. Github Issue created & populated with template (deliverables, required reviewers, etc.)
2. Create new research Figma file with your naming convention: (Ticket#)(Affected component) - (Brief description)
3. All work, research & experimentation take place here ( eg insert existing component, detach & modify)
4. Reach consensus on changes
5. Branch master with your naming convention: (Ticket#)(Affected component) - (Brief description)
6. For existing component - Update (not replace) relevant component with agreed modifications
7. For new component - Create new page & import finalised component form working file.
8. Merge back to master with relevant change log details. 


**For branches that currently exist that have valid work on them - Suggested workflow below:**
1. Create ticket outlining work and linking to previous related tickets
2. Create new figma file - naming convention: (Ticket#)(Affected component) - (Brief description)
3. Import relevant research - (cautious as to importing modified components, lets discuss this in depth)
4. Proceed from step 3 above.


**Recommendations for improved deprecation process** 

The existing ["deprecation process" ](https://www.figma.com/file/grsz2h0yjVw0lGalHIcu2A/Deprecation-Process?type=design&node-id=3%3A119&mode=design&t=QM3Mn4diVYJ3DFEe-1) file is only relevant to components outside of the main library files that are being refactored/replaced. 

All deprecated components I have seen are components previously lived outside the main library file
<img width="274" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/fcf3cae6-3ffe-49ab-89a7-9fb815a818e5">

All deprecated components have been moved into the "working files" folder - I think this needs consideration, if we move them into a new folder named "deprecated" then it would prevent accidental usage.
<img width="439" alt="image" src="https://github.com/grommet/hpe-design-system/assets/135040188/674cce89-0610-4bee-936b-13e6f49ac485">

We are making an assumption that in the future all components can "evolve" or "scale" inside the main component library.
What is the proposed steps if we do need to deprecate from inside the library, or how do we manage breaking changes? 

How much change can a component take before changes are breaking for consuming designer - eg can we change layer names, order, variant properties? - Use case - designer accepts modified component- all their overrides are cancelled out.

The previous efforts to deprecate allowed 2 components to exist side by side - (one in library , the other in working folders) - This allowed designers to consume updates - see that it was deprecated - offering them the chance to
a - Replace with new component
b- keep using the now deprecated component, knowing it wont be a detached oprhan for 6 months.
