### ISSUE TITLE
Toggle Button Group - Create figma component

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3642]
Following explorations in the data collection toolbar we have designed an MVP for a toggle button group that can be used elsehere in the platform (not limited to toolbar).

Note, the design file attached uses modified instanced of the existing button component. However depending on the use case for single select or multiple select toggle it is likely that styled radio or checkbox html elements are more suited to the purpose.
The existing designs will be rebuilt to match any finding or recommendations uncovered  from the coded prototype.

**Request for a prototype research & designs linked below:**
https://www.figma.com/file/kUSAmsiPTWqD0JyV6R36d9/Feature-Request---Toggle-button-group?type=design&node-id=6-385&mode=design&t=l7WRXPO4Hy9g310P-4

@halocline @taysea @MikeKingdom tagged for visibility.

**This issues is a follow on to:**

Design system ticket
https://github.com/grommet/hpe-design-system/issues/3611

**Comment by SeamusLeonardHPE** [comment]
@britt6612 I see that there is another issues on the dev board linked to this.

https://github.com/grommet/hpe-design-system/issues/3710

In the linked figma file Ashif has modified button component to match the styles he required, however I don't know if you will build this as a styled radio or checkbox (or will there be 2 components for each use case) or a group of buttons.

I believe we will need to create a new custom component(s) in figma to mimic any decisions made in code.

**Comment by britt6612** [comment]
@SeamusLeonardHPE We are still doing a little exploring and research on the dev side of how we want this component so Im think we can talk tomorrow or early next week..

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf @britt6612 

Can we get an update on the status of this ticket before end of day Thursday,


@ashifalinadaf do we need to have a design review for the component styles (hover, focus, text etc) 
What will this component be called, and will there be variations of it for multi select vs single select vs button group?

**Comment by britt6612** [comment]
@SeamusLeonardHPE @ashifalinadaf 

Right now Im working on 2 different approaches on how we are going to add this into grommet. Im doing both single selection as well as multiple selection but if we want to focus on just one that's fine. As of now we are calling this component "ToggleButtonGroup" but agree we can revisit. So the one component "toggleButtonGroup" has a default of having more than one selection. Then a user can pass in `exclusive` which is only one selection allowed. Now some of the issues in grommet is that we are trying to leverage `RadioButtonGroup` as well as `CheckBoxGroup` however those components have a lot of set styles in there so in order to stay backward compatible I had to do a little but of rearranging. Im working on a second approach of just using a `Box` wrapping `Buttons`. You can check out the preview below I will say `hover` `focus` styling is missing until we better narrow which path we are going with, then we will incorporate these styles as well as keyboard behavior. 

https://deploy-preview-7155--sad-tereshkova-173d07.netlify.app/?path=/story/input-togglebuttongroup-simple--simple

**Comment by ashifalinadaf** [comment]
@britt6612 thank you for the update, nice to see the working prototype. 
As far as naming convention, I will have a look and see if we can get some consensus on one / two names.

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf @britt6612 @SeamusLeonardHPE 

Review state of coded prototype & align and differences between style & functionality

**Comment by halocline** [comment]
@SeamusLeonardHPE should this be marked as "closed?"

**Comment by SeamusLeonardHPE** [comment]
Published in [grommet](https://v2.grommet.io/togglegroup) & [figma library](https://www.figma.com/design/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?node-id=27182-429) - 
Closed as completed.
