### ISSUE TITLE
Recommend “quick filter” variants - Custom selection

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3646]
[Mapped to 2024 Q2 Objective 2 - Quick filters](https://hpe.sharepoint.com/:p:/r/teams/hpe-design/_layouts/15/Doc.aspx?sourcedoc=%7B578BCD68-03C8-4054-88BC-B24EADABBE7A%7D&file=HPExs%20Goals%20Jan%202024%20-%20DS.pptx&action=edit&mobileredirect=true)

The need replace the existing "table quick filers" which misuses the card component has been requested. 

Potential solutions to this were suggested by Gina at office hours Dec 14th 2023. 

https://www.figma.com/file/Lh01flLH73cFNGZiFxEFth/HPE---Office-Hours?type=design&node-id=6331-8489&mode=design&t=MtRtel0eEDDiISP9-4

**Considerations:**
Document use cases for this design pattern (quick filter, styled radio/checkbox ) single select vs multi select.
Review suggestion solutions offered by Gina.
Can these styles be used for links in contextual help sidebar?

**Comment by luketa8** [comment]
[Working file](https://www.figma.com/file/WellQcIogaHFdrAR0RYNz8/%233646---Quick-Filters?type=design&node-id=0%3A1&mode=design&t=azPYPRY6lC5pSnI2-1)

**Comment by SeamusLeonardHPE** [comment]
Thanks Lucas,

To narrow the focus into deliverables

- [ ] Define use cases 
- [ ] Create anatomy/Anatomies 

Ask for dev feedback on use cases, could this type of interaction be coded as (styled versions of) radiobuttons, buttons, links, checkboxes, if so what states will need to be created for each type.

**Comment by oliverHPE** [comment]
Hey Lucas,

**Comment by luketa8** [comment]
Great feedback, Oliver!

+1 That the way that selection behaves and looks should be the same between the two components.

In terms of anatomy, the icon element is optional but important in the help/support context but not so in the data filtering uses.

As of multiple selection, it can be used for combining quick data filters, but in the help/support context I didn't find use cases for. Description may only be needed in this context, I do agree that the counter should take its place in the quick filtering component, since a description is not needed here.

I've added options for how to show the selected state on the same working file. 

Thanks!

**Comment by KennyAtHPE** [comment]
Looking good so far @luketa8, I left some comments in your Figma file. 


------------------------------------------------------------------------------------------
**Pasting in one specific Figma comment on possibly making this a single component.** 

Because of the similar way in which these components are designed and their core functionality, I'm wondering if there's an opportunity to create one singular component instead. Quick outline of how I'd envision this component:

The main component would be 'Selection cards'

Anatomy:
- Container
- Header 
         - Title 
         - Checkmark
- Icon (can be status indicators or general icons based on use case)
- Description (can either be text or numbers)

Behavior:
- Single select
- Multi select

Variants:
- Quick filters (this variant by default would be built to have the 'Counter' with the larger font size + any other changes necessary)
- Navigation
----------------------------------
Thinking that if we separate these into two different components, users will quickly get confused about which is which considering they both look visually similar and functionally work the same (both are selectors). Some other random thoughts:
- We'd have to update the datatable page to include guidance on quick filters
- Curious as to what we'd be prescriptive about and what is flexible (font/icon/container sizing)
- Maybe these aren't even new components, but rather variants of cards or some other component?

**Comment by luketa8** [comment]
Added Proposal and Components pages in the [Figma file](https://www.figma.com/file/WellQcIogaHFdrAR0RYNz8/%233646---Quick-selection?type=design&node-id=287%3A2968&mode=design&t=Dsen6DogeuUplUww-1)

Let's review and discuss tomorrow in the swarm.

**Comment by KennyAtHPE** [comment]
@luketa8 left some comments, looking forward to the review sess tomorrow!

**Comment by luketa8** [comment]
Closing task and creating follow up ticket.
