### ISSUE TITLE
Reviewing Skeleton Guidance

### ISSUE THREAD

**Issue by SOjaHPE** [grommet/hpe-design-system#3677]
**Problem - Refresh guidance for clarity**
Feedback from Daniel M. from Compute about Skeleton

The skeleton pattern for data loading- I'm not aware of anyone doing that today, and I wasn't sure how thorough the guidance was on when it should be utilized vs a spinner, when I talked with Blaine (from Compute) he was hoping for some more concrete details like "if it takes more than 500 ms, this is the standard experience to reach for" kind of thing

**Comment by KennyAtHPE** [comment]
@julauxen I think some of the confusion probably stems from the fact that we don't have that many examples on the skeletons page as opposed to the spinner page. The guidance is a bit confusing because of this since it isn't clear as to what the use cases are for skeletons. I'd suggest:
- Creating a do's and don'ts section (ex. ) to showcase when to use skeleton vs spinner
- Identify and create recommendations on how to change conflicting and/or confusing guidance for both components

**Comment by SeamusLeonardHPE** [comment]
@taysea @halocline 
Reviewing Skeleton Guidance PR approved, still not merged.
