### ISSUE TITLE
Create Data Collection Toolbar 2

### ISSUE THREAD

**Issue by ashifalinadaf** [grommet/hpe-design-system#3703]
Follow up ticket from https://github.com/grommet/hpe-design-system/issues/3650

Deliverables: 

- [x]  Figma component based on sandbox prototype 
     - [x] Get reviewed by the devs on the current solution.
     - [ ] Decide on the order of the components within data collection toolbar
     - [ ] Decide on the visibility of Figma components within data collection toolbar at each breakpoint

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf since we have paused work on "saved view"

Can you please look at the data tool bar component again:

Define what customisations are available to each view mode (eg does "Sort" button disappear when in map or chart view mode). This can be done in bullet list.
Review current DS guidance page (figma scrape linked below) and suggest edits to bring guidance into alignment with updated design

https://www.figma.com/file/H47lk4zrHgkkRvwV9EIzq4/%233650---Create-data-toolbar-component?type=design&node-
id=0%3A1&mode=design&t=K8j9Jtxdk0SIkvuK-1

Update for team.

2 versions of the toolbar have been shared amongst the product design team and we are awaiting feedback to their preferred usage.

https://www.figma.com/file/AGC2ntsUG3hEU7QFxD8tkZ/%233650---DataToolbar-Demo?type=design&node-id=0%3A1&mode=design&t=CqfWyGnAnXauc9OP-1

In version 1 we created sub components with all the logic for state & breakpoint & allow the designer to access these form the parent component. ("Expose properties from Nested instances" is how this is described int the parent component property)

In version 2 we provided subcomponents, but the designer needs to be select inside the components to access the nested variants


![image](https://github.com/grommet/hpe-design-system/assets/135040188/d1a7ba30-bc11-4693-a88b-98d6d70c95e6)

**Comment by ashifalinadaf** [comment]
@SeamusLeonardHPE as discussed I will be working on the following,
Defining what customisations are available to each view mode (eg does "Sort" button disappear when in map or chart view mode). This can be done in bullet list.
Review current DS guidance page (figma scrape linked below) and suggest edits to bring guidance into alignment with updated design

https://www.figma.com/file/H47lk4zrHgkkRvwV9EIzq4/%233650---Create-data-toolbar-component?type=design&node-
id=0%3A1&mode=design&t=K8j9Jtxdk0SIkvuK-1

**Comment by ashifalinadaf** [comment]
- From the recent inputs from devs **all controls are applicable to all the views.** 
- Need prototype and guidance on the **map view** and **chart view** to finalise on the controls to these views, we can always revisit and make changes to the controls. 
- Besides we have an option to toggle the controls and use as per the use cases.

**Comment by ashifalinadaf** [comment]
Added some of the guidance on the toolbar in 'Data' page. 
[Figma file ](https://www.figma.com/file/uZD8NwEmL1cdt3SEbT5Bt6/%233650---Create-Data-Collection-Toolbar?type=design&node-id=2753-15410&mode=design&t=wUxNubX87NOLBifC-11)

**Comment by ashifalinadaf** [comment]
@SeamusLeonardHPE I have summarised the feedback from the designers, 
[Feedback ](https://www.figma.com/file/AGC2ntsUG3hEU7QFxD8tkZ/%233650---DataToolbar-Demo?type=design&node-id=579-42138&mode=design&t=skcscbEQGV3ROBk3-11)collected from the designers. 

Concerns raised by 2 persons is in bold 
**1. Bottom border is heavy 
2. Primary/secondary button is used in most cases toolbar button would be confusing
3. Sorting is really needed? less use cases push aside after view controls? 
4. .view controls to switch it on/off** 
5. Boolean over drop downs in control panel
6. Improved data summary accommodates return results
7. Clear filter icon at lower resolution
8. Look into Margins
9. Different icon for grid
10. Filter values can be - changed - enabled/ active 
11. Most used configurations to the top 
12. Ambiguity on use of terms - work on the common used terms

Besides Tales Ebner has provided the [solution](https://www.figma.com/file/AGC2ntsUG3hEU7QFxD8tkZ/%233650---DataToolbar-Demo?type=design&node-id=336-39415&mode=design&t=skcscbEQGV3ROBk3-11) to the most of the issues however the search and saved view width changes as we apply/remove other controls. 
we can visit and make changes accordingly.

**Comment by ashifalinadaf** [comment]
As discussed in designers and devs meet it is recommended to have separate page for data collection toolbar.
Keeping it brief and simple and adopting the previous guidelines from [map ticket. ](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1260-91540&mode=design&t=ZpadL8jljOn67b95-11)

**Comment by SeamusLeonardHPE** [comment]
@ashifalinadaf just a not that I dedit your comment above to specify 
1- You are referring to a guidance page
2- Updated link to the extracted page with Vicky's work isolated.

**Comment by ashifalinadaf** [comment]
Thanks @SeamusLeonardHPE 
Guidance page is not linked, I meant to say a separate guidance page (individual).

**Comment by ashifalinadaf** [comment]
Hey @SeamusLeonardHPE wanted some clarifications on[ these items (Feedback from the designers on toolbar)](https://www.figma.com/file/uQOe4awPm8gzM5Gmpnm1Ms/iteration-DCT?type=design&node-id=24-6669&mode=design&t=2EDb6YFLBo0JFuxR-11) and if you can have a look and provide/decide on the questions/suggestions, 
it will be easier for me to write the guidance and anatomy for the toolbar.

**Comment by SeamusLeonardHPE** [comment]
Added the latest version to a text document & asked for[ feedback form Sylvia & Tales](https://www.figma.com/file/AGC2ntsUG3hEU7QFxD8tkZ/%233650---DataToolbar-Demo?type=design&node-id=707-51170&mode=design&t=Z2Af0biWMg9dEC2d-4).

Created branch of main for data collection toolbar with V3 from our discovery in order to prep for publication.

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/ZpbKWRWXgENLJ0xasTqw3u/HPE-Design-System-Components?type=design&node-id=26982%3A970&mode=design&t=lBX1fVPHQQuuwgid-1

- [ ] Confirm component name

**Comment by ashifalinadaf** [comment]
[Branch and working component](https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/branch/ZpbKWRWXgENLJ0xasTqw3u/HPE-Design-System-Components?type=design&node-id=26982%3A970&mode=design&t=8gLe1q02xw8TOZfO-1) has been added by @SeamusLeonardHPE

**Comment by SeamusLeonardHPE** [comment]
@SeamusLeonardHPE @taysea 
Connect to review the current state of our branch and bring alignment on any divergence between code & figma.
