### ISSUE TITLE
ButtonGroup/ToggleButtonGroup

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#3710]
Research:
- [x] What other component libraries call this (Material UI/Material Web, Carbon, Radix, Headless UI, Tailwind UI, Microsoft Fast)
- [x] What the API surface looks like for those libraries/potential prop names

**Comment by britt6612** [comment]
I found that Carbon, HeadlessUi, and Tailwind do not offer multiple toggleButtonGroup. 

- Carbon - Had a content switcher but this is not what we are looking for.
- HeadllessUI - They have a RadioButtonGroup in which you can customize how the selectors look however since it is a RadioButtonGoup only one selection is allowed.
- Tailwind - Had a ButtonGroup option from what I could find in docs this was also just a singular selection. 

Good matches: 
MaturalUI and Radix were the 2 libraries that had what we are looking for. 

- MaturalUI - They called their component `toggleButton` used to group related options.
- Radix - ToggleGroup is what they are calling their component 

In the figma below I have added screen shots and props in which MaturalUI and Radix offer with their components:
https://www.figma.com/file/EHRRCLCzdtl0ugYf96rhHP/Toggle%2Fbutton-group?type=design&node-id=0-1&mode=design&t=hZJeGBOxR61O656j-0

**Comment by taysea** [comment]
Closing, follow on #3642
