### ISSUE TITLE
Move components into main library file.

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3738]
Follow up to figma library clean tasks:

https://github.com/grommet/hpe-design-system/issues/3700
https://github.com/grommet/hpe-design-system/issues/3648

Existing external components & library tracked on this excel sheet:

https://hpe-my.sharepoint.com/:x:/r/personal/seamus_leonard_hpe_com/Documents/Archive%20folder%20figma.xlsx?d=wb27b78fb45574b0b8bf49b226df2aa68&csf=1&web=1&e=2A6bgx

**Comment by SeamusLeonardHPE** [comment]
Link to instructional steps:

https://www.figma.com/file/BPynj4H7GALt255bE0EaF7/%233738---Library-Tidy?type=design&node-id=42-7308&mode=design&t=XRrjeT6riic6UB3Q-4

- [ ] Moved & published the footer component today

https://www.figma.com/file/5uOrsL2qk8XwwH8C1ZpDb6/HPE-Design-System-Components?type=design&node-id=25173-2&mode=design

@KennyAtHPE if you can track the progress of next components, tackle them in order of complexity and we can make decisions about how to tackle on a per case basis.

**Comment by KennyAtHPE** [comment]
List of external components ranked by effort level for migration:

#### SMALL
- [ ] Empty state
       - Might need small refinements but should be able to migrate as is
- [ ] Spinner
       - Same as empty state
- [ ] Footer
       - File needs to be unpublished/moved to archived or working files


#### MEDIUM
- [ ] Accordion
       - Requires complete refactoring w/ new component and sub-components
       - **Could be a large effort**
- [ ] Text Area
       - Requires a complete refactor w/ new component
       - **Could be a large effort**
- [ ] RangeInput
       - Requires a small refactor
- [ ] Box
       - Doesn't require a component but we will need to make a page for Box with some visual explanations
- [ ] Grid
       - Same as Box
- [ ] Main
       - Same as Box
- [ ] Pagination
       The component refactor is WIP, thought is that we should have that completed before migrating the compopnent. @SeamusLeonardHPE should this be in the large t-shirt sizing section instead?
       - Related ticket #3651 
       
#### LARGE
- [ ] MaskedInput
       - Requires a complete refactor and the direction for this component is unclear
       - Questioning whether or not this even needs its own component. Can we just make copy and pastable instances for this using textinput?
- [ ] Card
       - Needs to be taken a look at entirely, not even sure if this should be a component or a template
       - Unsure if we should move this over as part of this work, I'm thinking no
- [ ] DataTable
       - Requires a large refactor and this page will most likely need updated visual use cases and examples
       - Thinking that we should hold off on moving this over until the component has been refactored
       - Relevant ticket #3705

------------------------------------------------------------
@SeamusLeonardHPE for now, I think the focus should be moving everything over that requires the least amount of effort first. Accordion and TextArea would be tackled last within the medium section

**Comment by SeamusLeonardHPE** [comment]
@KennyAtHPE 

All of these component are to be moved in their current state, any refactoring will happen in branches post move.
The only work required is making the examples conform with Olivers templates.
I'll include a subsequent comment with the steps we took to move the footer component when we did our test.

The only exceptions are:
Card - is it currently unpublished
Box - Unsuited to being a component subsequent discussion decisons will be made in [#3755 ](https://github.com/grommet/hpe-design-system/issues/3755)
Grid - Unsuited to being a component subsequent discussion decisons will be made in [#3755 ](https://github.com/grommet/hpe-design-system/issues/3755)
Main - Unsuited to being a component subsequent discussion decisons will be made in [#3755 ](https://github.com/grommet/hpe-design-system/issues/3755)

**Comment by KennyAtHPE** [comment]
@oliverHPE @SeamusLeonardHPE requesting reviews on the tidy up branch for [Spinner](https://www.figma.com/file/feIeYk1zX36y9E7e7rprc2/branch/eEihUUzgHAykAaObeYjLl4/HPE-Spinner-Component?type=design&node-id=0%3A1&mode=design&t=iYxDLJA2WwRALDha-1) and [Empty State](https://www.figma.com/file/4uEMfLl9riZDJ4y6dlv1Jq/branch/vwkAXwImd6mdQ3uXtUl27L/HPE-Empty-State?type=design&node-id=3028%3A6048&mode=design&t=apdBuoTPK26a5uTS-1)

@oliverHPE left a small comment on the component layout template. I think there are opportunities to further streamline it a bit so that elements would stretch and scale if the frame size changes but overall it worked great and made the process much faster!

-------------------------------------------------
@SeamusLeonardHPE I'd be hesitant for us to migrate over components such as accordion and masked input since we aren't introducing 2 new components to the main file but 14 components for accordion and 22 components for masked input. I'm questioning whether or not, we'd want to refactor and tidy up these components before migrating them over. Cautious here since I think we're adding more fires than stopping them in attempt to rush the process of moving things over instead of moving things over when they are ready. Not sure if we want to have a main component file where some of the components are in an unusable or broken state.

**Comment by KennyAtHPE** [comment]
Did the tidy up work for rangeinput, textarea, and accordion. Marked branch as reviewed @SeamusLeonardHPE. Will work on MaskedInput next and Pagination (need to get status on this component).

**Comment by KennyAtHPE** [comment]
@SeamusLeonardHPE [Maskedinput branch](https://www.figma.com/file/fO285pXUqN9pVZ0xpRoKjL/branch/tKmtFCqQudG5laEwFOVYkN/HPE-Masked-Input-Component?type=design&node-id=0%3A1&mode=design&t=FooJk4dihcBjllBC-1) is ready for review

**Comment by SeamusLeonardHPE** [comment]
Only remaining component that belongs inside the main library is being refactored and the out dateed DataTable component file will be deprecated & archived when work on #3705 is complete.

https://github.com/grommet/hpe-design-system/issues/3705

Box, Grid, Navigation & PageLayout remain in the the Library, but should not be added to the HPE component file.

They will be resolved in subsequent ticket [#3797](https://github.com/grommet/hpe-design-system/issues/3797)
