### ISSUE TITLE
Inline help popup / Enhanced tooltip

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3780]
Deliver “inline help popup” --> Gina T. contextual help asks​

Enhancements for Contextual Help on GLCP.

Tip - 
https://www.figma.com/file/NM3csAgUMhrnB7tIePHy9T/Contextual-Help-Patterns-for-DS?type=design&node-id=2001-85533&mode=design&t=hS387xoGUbGbvt8o-4

Ladders up to:[ 2024 Q2 Objective 1 ](https://hpe.sharepoint.com/:p:/r/teams/hpe-design/Shared%20Documents/HPE%20Design%20System/Goals,%20Planning,%20and%20OKR%27s/HPExs%20Goals%20Jan%202024%20-%20DS.pptx?d=w578bcd6803c8405488bcb24eadabbe7a&csf=1&web=1&e=29EuPh)

[Proposal ](https://www.figma.com/file/NM3csAgUMhrnB7tIePHy9T/Contextual-Help-Patterns-for-DS?type=design&node-id=2001-85607&mode=design&t=LEFWUb3kgZGC9xbb-4)

Investigate impact of implementing enhancements to to tip component.

**Addition of Title/Header**
This was previously part of the component and was removed?
[Currently can be customised in grommet](https://storybook.grommet.io/?path=/story/controls-tip-info--info), should this be a core feature?

**Addition of link**
This would have to be in a tooltip launched by an onClick event, since hover tips cannot contain interactive elements
How do we signify an onClick tool tip vs a hover tool tip? (previous conversation about dotted underline in text styles)

**Guidance for max length in title & copy**

[Usage suggestions](https://www.figma.com/file/NM3csAgUMhrnB7tIePHy9T/Contextual-Help-Patterns-for-DS?type=design&node-id=2001-85801&mode=design&t=LEFWUb3kgZGC9xbb-4)

- [ ] Connect with devs to map impact
- [ ] Branch main library file for figma component experimentation
- [ ] Review & refine [suggested documentation](https://www.figma.com/file/NM3csAgUMhrnB7tIePHy9T/Contextual-Help-Patterns-for-DS?type=design&node-id=2001-85801&mode=design&t=LEFWUb3kgZGC9xbb-4) based on findings.

**Comment by julauxen** [comment]
Talked to Gina:
**About prio and deadline:**
- Main priority is to have the new trigger (dotted line) and the popup concept.
- There's no defined deadline, but she mentioned it would be important to have as she is not the only one in need of it.
**About further context:**
- The information for those popups will be hard coded for now, but in the future the goal is to integrate content with TCaaS and allow the docs team to edit it in Tridion.

**Comment by julauxen** [comment]
Talked to devs
The popover request should be a new component, as using the tip would generate limitations and accessibility issues as it should not have interaction within it.

**Comment by julauxen** [comment]
### Problem:
Currently in our Design System we don't have a component that can help to provide further information in-context without disturbing the main UI.

### Steps to solution:
- [ ] Investigation
- [ ] Initial definition and proposal
- [ ] Reviewing with team
- [ ] Building the component for the library
- [ ] Testing it with consumers, including Gina
- [ ] Build component in Grommet

**Comment by julauxen** [comment]
[Figma file here.](https://www.figma.com/file/r1YUOdncOi0Bdl8msDF7Ni/Popover---%233780?type=design&node-id=0%3A1&mode=design&t=DHeQrKtyuaCOL6kM-1)

**Comment by SeamusLeonardHPE** [comment]
@julauxen after our conversation today, I'd suggest. 

- Connect with dev to eta on their capacity to prototype
- Creating backlog ticket for guidelines
- Define size variants Vs composable variants.
- Document close button requirements (visible/hidden & accessibility impact)

**Comment by julauxen** [comment]
Developers have no capacity to build a prototype in the current sprint (April 17th to May 1st).
Backlog ticket created for guidelines here: [#3844](https://github.com/grommet/hpe-design-system/issues/3844)

**Comment by julauxen** [comment]
This ticket went through design critique and D&D session. Here is the just of it:

**Design Critique Feedback:**

- Deliver in specific sizes to allow for different spacing for each
- Focus on delivering configurable because Slot components have generated confusion in the past
- Any size can should composable (have a slot)
- Maybe add the composable as a variant ("hidden")
- Title is optional
- Avoid creating multiple text styles for each size variant
Watch the session [here.](https://hpe-my.sharepoint.com/:v:/r/personal/lucas_speyer_hpe_com/Documents/Recordings/Design%20Critique%20Monday-20240422_131625-Meeting%20Recording.mp4?csf=1&web=1&e=njMNuN&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

**D&D Feedback**

- For the accessibility questions, we will build a prototype and test with Bill. 
- For button size, as long as we follow the minimum requirements for accessibility (24x24) we are fine.
-  The close button can have relationship with the container.

### Next Steps

- Discuss with Seamus what Feedback should be aggregated
- Wait on decision from leadership as to where this work should live and if it should be a template or a componenet

**Comment by julauxen** [comment]
Ticket created for follow on on devs side: [#3856](https://github.com/grommet/hpe-design-system/issues/3856)
Specs delivered [here.](https://www.figma.com/file/r1YUOdncOi0Bdl8msDF7Ni/Popover---%233780?type=design&node-id=327%3A15262&mode=design&t=tfQhFyFDOoX95v3C-1)
