### ISSUE TITLE
Icon library missing files

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3788]
**Who is requesting this fix?** (add contact details here)
Design system team

**Where is this fix needed?** (links and screenshots)
The [DS figma icon asset file](https://www.figma.com/design/G99KGffGLFKICy8xRs51lW/HPE-Icons?m=auto) is missing svgs that are available in the [grommet library](https://icons.grommet.io/)

**Expected Behaviour** (tell us what should happen)
Parity between grommet & figma icon components

**Current Behaviour** (show us the current behaviour)
Missing icons include (but not limited to [Bold](https://icons.grommet.io/?s=bold) [underline](https://icons.grommet.io/?s=underline)
__________________________________________________________
**Reviewers:**

- [ ] Reviewer 1

- [ ] Reviewer 2

**List possible consequences, involved assets and components:**
1. Addition of new icons
2. Review need for dark mode icons (will tokens replace these assets?)

**Checklist** (add your progress in the comments)

- [x] Align with stakeholders

- [x] Gather historical information

- [x] Build proposal

- [ ] Gather feedback

- [x] Create a PR or [Create a Figma Branch](https://hpe.atlassian.net/wiki/spaces/DS/pages/2516288954/Branching+Merging+and+Publishing#Creating-a-New-Branch)

- [ ] Ask for review

- [ ] Publish

- [ ] Communicate

**Comment by vavalos5** [comment]
- [ ] create a branch in Figma with ticket number
- [ ] Identify and create a list of icons in Grommet not available in Figma and vice versa
- [ ] identify a search plug in for icons
- [ ] identify a plug in to export all layer naming conventions into an excel sheet
- [ ] identify a plug in to change naming in bulks
- [ ] connect with devs on naming
- [ ] apply naming to Figma using plug in

**Comment by vavalos5** [comment]
In efforts to get this work ongoing, i've handed to Asif while out for the next 3 days to continue making traction.
@SeamusLeonardHPE @ashifalinadaf 

I've sent the following message to Asif:

1. Download [Figma Search plug in](https://www.figma.com/community/plugin/976153400648431633/figma-search) & run in this [Figma branch file](https://www.figma.com/design/G99KGffGLFKICy8xRs51lW/branch/PS1eK1CnNd0inKTJFVqmXf/HPE-Icons?m=auto&node-id=582-7&t=nhheaiygzpYl6oPw-1)
2. Go through list of [Grommet icons](https://github.com/grommet/grommet-icons/blob/master/public/img/image.svg) ( I left off at image)
3. Using the Figma plug in, look for icon name and note down whether icon is aligned to Figma (ok), not aligned (mismatch), not in Figma ( icon not in figma), or not in Grommet ( icon not in Grommet) in the status column of this [Excel sheet](https://hpe-my.sharepoint.com/:x:/p/vicky_avalos/EeNw-gRiBERErLX1eR8X1SkBJzIvVfp_YgUyxA_UhNpqyw?e=8mlm0H).
4. Note down specific notes on the discrepancies in the “discrepancies” column.
5. FYI, I also had to search for icons in Grommet because I came to the realization that some icons that are in GitHub are not in Grommet.

Thank you!!

**Comment by ashifalinadaf** [comment]
Hey Vicky, 
I will have a look and will try to fill up the excel sheet as much as possible.

**Comment by SeamusLeonardHPE** [comment]
For your reference Vicky, Ashif had to duplicate the excel sheet to gain edit access, so updated entries are at  this file.
We can aggregate next week.

https://hpe-my.sharepoint.com/:x:/r/personal/ashifali_nadaf_hpe_com/_layouts/15/Doc.aspx?sourcedoc=%7B5ee935db-c5da-48c9-9924-512607cbcbcc%7D&action=edit&wdPreviousSession=8f5533c4-9268-83d2-996d-6950e68e5341

**Comment by ashifalinadaf** [comment]
@vavalos5 @SeamusLeonardHPE I tried to compare the icons in grommet and figma, 
added additional column to have figma icon group. 
find the copied version [here ](https://hpe-my.sharepoint.com/:x:/r/personal/ashifali_nadaf_hpe_com/_layouts/15/Doc.aspx?sourcedoc=%7B5ee935db-c5da-48c9-9924-512607cbcbcc%7D&action=edit&wdPreviousSession=8f5533c4-9268-83d2-996d-6950e68e5341)(as I didn't had access) and please try to copy the file/ data from the same. 
completed till _streetview Icon_

**Comment by vavalos5** [comment]
Thanks so much for the help @ashifalinadaf, we were able to get through 647 icons together!!

In this [Excel sheet](https://hpe-my.sharepoint.com/:x:/r/personal/ashifali_nadaf_hpe_com/Documents/Shared%20files/Grommet_Icon_Audit_13_June_2024%20V2%20(from%20Impact%20Icon).xlsx?d=w5ee935dbc5da48c99924512607cbcbcc&csf=1&web=1&e=K3Z2b7), all icons missing in Grommet/Figma can be found.

**Comment by ashifalinadaf** [comment]
Hey @vavalos5 hope that was helpful,
Please copy the file and keep it in your files/common DS files, as I am leaving the organisation this shouldn't be a problem later.

**Comment by vavalos5** [comment]
Adding here for future reference. All GitHub metadata for Grommet icons can be found [here](https://github.com/grommet/grommet-icons/blob/master/src/js/metadata.js).
