### ISSUE TITLE
Library folder final edits.

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3797]
Research & decide on the best outcomes for the current files located in the public library:
Grid, Navigation, Box & Page Layouts.

Grid: Contains outdated grid styles - fix or unpublish
Navigation: Contains components that are not helpful to designers in representing the grommet navigation component
Box: Contains components that are not helpful to designers in representing the grommet navigation component
Page Layouts: This is a template file that needs work & possibly rehoused.

**Comment by vavalos5** [comment]
**Grid:**
- go around ask designers if they're utilizing this Figma at all when working on designs (my hunch is probably not since we build out components) + they likely rely on guidance on HPE DS site + theme when handing off. 
- review Figma statistics to see who is utilizing and when last used
- IF designers are using, then we should update, IF NOT, don't think we should spend the time updating as we the design system don't even utilize them when creating designs. We refer to the Page Layouts. Perhaps we agree to implement them into PageLayouts. Not definitive yet though. TBD

**Box:**
- Same as above

**Navigation**
- Same as above

**Page Layouts:**
- Same as above


All of the above could live in a "Foundations" folder like [Material ](https://m3.material.io/foundations/layout/understanding-layout/overview)should we decide on that direction OR "Elements" like [Carbon](https://carbondesignsystem.com/elements/pictograms/library/) alongside our colors, text, etc... However, this might change once we make implement design tokens.

**Comment by vavalos5** [comment]
### **Box:**
I noticed on the DS site, we don't include: height, width, border, round, spacing, or any of these details under "box". Nor do we link t-shirt sizing to direct our users. We may want to do that on the site. 

 Including screen shot of analytics

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/a27954eb-0584-4081-8a8f-11fac1d9e671)

**Quick fix:**
While we include all of these specs into our components, how often do designers actually need to implement spacing into elements? Probably not very often. We should just "deprecate", and consider the long-term proposal below. 

**Long-term Proposal:**
I took a look at how [Material organizes their Figma UI Kit](https://www.figma.com/file/9dIDCS8kubzjaIBSK3msCi/Material-3-Design-Kit-(Community)?type=design&node-id=49823-12141&mode=design&t=Yrm6AywvQ60yLIVO-0) and like the fact that they had an introductory getting started page (see image) that links to these foundations: typography, colors, icons, guidance, resolution breakpoints, perhaps we can do something similar. Since we're wanting the design system site to the single source of truth, this would direct them to any guidance but all of these foundations would live on a single file.

- in addition, ensuring that everything is aligned correctly

![Image](https://github.com/grommet/hpe-design-system/assets/62117454/22e15613-99c6-433e-af21-5a518d9e98a8)


### Grid

**Quick fix:**
- No components here, so no analytics to show. Would still be interesting to understand whether any designers are referring to these and how they're being utilized. As a quick fix, we should remove, all of the guidance and examples are being best represented on our site.


**Long-term Proposal:**
Remove entirely


### Navigation

**Quick fix:**
Navigation doesn't have any components that would be utilized but rather these are the outlines of the pages we currently have published on the design system site - thus no analytics to show. Removing

**Long-term Proposal:**
Same as Box


### Page Layouts
I saw there's a branch on this one recently for ticket #3624 - Need to chat w/ @SeamusLeonardHPE to discuss what changes he's making as ticket seems to be correlate to this one.

**Quick fix:**
TBD

**Long-term Proposal:**
TBD

**Comment by vavalos5** [comment]
@SeamusLeonardHPE Would love your eyes on my comments above. Let me know if you'd like to hop on a call and chat further as some of the work you're doing for PageLayouts seems to be similar to what I'm doing.

**Comment by SeamusLeonardHPE** [comment]
@vavalos5 thanks for the update and adding in you suggestions. I'd be happy to connect and discuss the best direction and how we could apply this thinking to all existing (and upcoming ) components.

I added some notes in this file were I aggregated the links to each figma, grommet & guidance site link.
Defining the conceptual similarity or differences between what is a grommet component and what is achievable in figma - 
some concepts might be suited to tokens, styles, components, templates etc so its up to us to map this out like an API as we refactor components and update guidance. 
I've tried to be specific to "grommet component" and "figma component"

https://hpe-my.sharepoint.com/:x:/p/seamus_leonard/ERhQGCmemj9Ggql-9UfryrkBgGF4MLjSQ7fwVTrzsiajmg?e=G14pn8

**Comment by vavalos5** [comment]
Including Figma link to the page i'm working on.

https://www.figma.com/file/rDDV3sETlviId9Dn1AbrPW/HPE-Foundations-Page?type=design&node-id=0%3A1&mode=design&t=bT5ao5JY84cGckZi-1

**Comment by vavalos5** [comment]
### Next steps:

**Low risk:** 

- Removing/archiving: box, grid and Navigation; placing the "Foundations" [Figma file](https://www.figma.com/design/rDDV3sETlviId9Dn1AbrPW/HPE-Foundations-Page?node-id=0%3A1&t=UWnchOAeHJZasZst-1) i'm proposing in the Library file that directs our users to the design system site.
- Page Layouts should be moved to templates. (confused why there's two: one in working files and the original one in Library)
- Also, if I'm a user, i'd expect "assets" to live in the library folder.
**High risk:** 

- Although not a part of this ticket, considering moving colors, icons and typography to one single file called "assets" of "foundations" We can chat with others such as designers using our files for reactions on this. High risk due to people utilizing icons and colors/typography are styles in Figma from within the files.

**Comment by SeamusLeonardHPE** [comment]
@vavalos5 thanks for the update.

For the **High Risk** tasks, it's possible we can roll these into some other upcoming work:

Typography  - Adopting metric 2 font and using tokens for text styles
Icons - Lozzi has a whole new set, so maybe we can deprecate/version existing& replace?
Colors - Adopting tokens instead of styles

They are some pretty major changes, so we will need to do some impact research & testing first.

**Comment by vavalos5** [comment]
@SeamusLeonardHPE Do we have a standardized way on how we're deprecating components? Previously we were inserting "Deprecated 🛑 " to the component name but not un-publishing the files. I reviewed some of the archived previously published components and noticed that they were following the deprecated labeling we were doing alongside un-publishing the components. Just want to confirm "this is the way " <---- lol if you know the reference. Don't want to un-publish until we confirm but I feel confident about un-publishing given the metrics above. Let me know if i'm missing anything else. Thanks!

**Comment by vavalos5** [comment]
In addition, in my message above, I noticed we have two PageLayout pages, are we ok with moving the templates we have readily available for designers into the HPE Template Library and move the PageLayout Figma file to "archive"? @SeamusLeonardHPE

**Comment by vavalos5** [comment]
I've archived Grid, Box, Navigation and PageLayouts.

Just awaiting on a response to my questions above before closing.

**Comment by SeamusLeonardHPE** [comment]
Hey Vicky, thanks for taking care of those.
The deprecation process has been following the [existing document](https://www.figma.com/design/grsz2h0yjVw0lGalHIcu2A/Deprecation-Process?node-id=2%3A47&t=qfnMLyxPKInrZXB6-1), with the additional step of moving to archive.

Maybe we can discuss during swarm moving the page templates ([or the new examples in the branch](https://www.figma.com/design/4rdBkUlHd5MCVq3hvUOXHd/branch/2TC7PI0KxoWROnlnnozsy9/Page-Layouts?m=auto)) to the template library.

A follow up task for all the files & components would be to remove or update any links in the DS site as appropriate.

**Comment by vavalos5** [comment]
Since we've archived Figma files for Box, Grid, and Navigation, we'll want to request the devs to remove from Figma. I've submitted the question on how to make the changes on the staff channel.

For PageLayouts, Seamus and I have already talked about transferring some of the previous work i've done and completing ticket #3871

**Comment by vavalos5** [comment]
Removed Grid, Box, Navigation and PageLayouts Figma files from website - PRs have been included in ticket and merged.
