### ISSUE TITLE
Create atomic slot component

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#3826]
Standardise how we are implementing slot components.

Create a component variant set that can be used in other designs for

- How a slot appears
- Language
- Links to supporting educational material

This will likely be an .unpublished component set that is available only to the DS team.

Experiment with the impact on current components that use slot (layer component + tabledata ) and upcoming components (selector + popover)

**Comment by SeamusLeonardHPE** [comment]
Initial research 
https://www.figma.com/file/KUfWwwcBkVsY9m9bntqEU9/%233826---Create-slot-component?type=design&node-id=0-1&mode=design

**Comment by KennyAtHPE** [comment]
Acceptance criteria for atomic slot component:
- Ease of use. The slot component should speed up a designer's workflow instead of being overly complex
- Flexibility. It should be created in a way that any component can be built using it
- Manageability. The single atomic slot component should be easy to manage and scalable for any future updates
- Naming. Aligned with Grommet and designers' mental models, is "Slot" the terminology we want to use?

Next Steps:
- [x] Explore different slot component approaches. Make a list of pros and cons
- [WIP] Prototype different slot component approaches using design system components. Make note of limitations if any.
- [ ] Review w/ the team
- [ ] Finalize approach, create ticket for next steps (finalizing component, swap them out with current slot components, merge + publish, create educational material)

**Comment by KennyAtHPE** [comment]
Update:

**Comment by KennyAtHPE** [comment]
Update: WIP
