### ISSUE TITLE
Clear selection and filtering

### ISSUE THREAD

**Issue by oliverHPE** [grommet/hpe-design-system#3925]
In Office Hours the following issue with filtering options was brought up:

### Link to problem

https://www.figma.com/design/JHrPqLlTHr14ICl1r4UPES/Fix%3A-Clear-selection?node-id=0-1&t=gO5lLWq11pYEOFF8-1

### Current problem

When filtering, not all single-selection components, like a radio-button, have a method of being cleared or deselected. When you have made a choice - selected a radio-button - there is no way to deselect that radio button. The result is that if you want to edit the filter, and remove that selection, you have to clear all filters and start the filtering process from the begining.

### Expected behavior or solution

A method to clear, or deselect a particular choice would solve this. On the provided Figma file, there are several proposed ideas to solve this problem.

**Comment by halocline** [comment]
Currently this would be achieved by the "Clear filters" button in the Toolbar or I would close the layer without "applying filters."

Radio button groups by definition enforce one value to be selected. Perhaps they are not the right input for the "last X days" use case and Select would be the appropriate control?

ToggleGroup allows for unselection of all options if desired. Is this an issue with how the Figma component is constructed?

Leaving comments in Figma file. I'm not sure the "clear" behavior treatments are needed. Instead, I think there exist more appropriate input choices for the use cases.

**Comment by SeamusLeonardHPE** [comment]
@luketa8 if you can connect with @oliverHPE  on this [document he created](https://www.figma.com/design/tAVsLQ0FbSEutnz5USgrCv/Clear-Selection---Discovery?node-id=1-3689&t=4MH3siAagoXB6IKk-1) and review the comments in figma a Matt links to above.


To me it appears that the radiobutton group was the incorrect filtering tool to use, due to its default behaviour (once selected, one option always required).
We may need to update our guidance to be more specific about the behaviour, and when it suitable to use radio vs checkbox. If it appears guidance pushed a product designer into a bad pattern lets locate and address this.

As this is a customer success oriented ticket, communication and alignment with Tales as the primary stakeholder is a requirement.

**Comment by SeamusLeonardHPE** [comment]
@luketa8 can you link to the figma files where you have been drafting documentation and exploring solutions

**Comment by luketa8** [comment]
Adding Figma links
 [Clear selection discovery](https://www.figma.com/design/tAVsLQ0FbSEutnz5USgrCv/Clear-Selection---Discovery?node-id=0-1&t=9MAGuSUFAjUHaDXK-0)
[Clear selection Figma](https://www.figma.com/design/JHrPqLlTHr14ICl1r4UPES/Fix%3A-Clear-selection?node-id=0-1&t=pEbDmUJUfUhHDit5-0)

Ready to review [Pull Request](https://github.com/grommet/hpe-design-system/pull/4066)
