### ISSUE TITLE
Test -- Build Tab

### ISSUE THREAD

**Issue by taysea** [grommet/hpe-design-system#4041]
Task:
Build "Tab" using available tokens and following approach documented in "achieving component height"
Documentation: "achieving component height": https://hpe.atlassian.net/l/cp/U1L001h3

As there are no component-specific tokens for **Tabs** yet, please build them with semantic tokens. Furthermore, see if you can build them with `component` (as opposed to component-specific) tokens, for example, `component.medium.minHeight`.

- [x] Apply available tokens to build "Tab" components
- [x] Document any places where a token was not available
- [x] Document any places where a token value seemed incorrect

Reviewers (check this box once reviewed and approved):
- [x] @oliverHPE 
- [x] @taysea

**Comment by julauxen** [comment]
This task is done.
[Feedback.](https://hpe.atlassian.net/wiki/spaces/~7120200aef6dd18fe543fb94524027e72fd862/pages/2614789435/Tab)
[Rebuild.](https://www.figma.com/design/mgOVt0Udt2ya03ETPh4CQO/branch/mJ8d7bv5I8zgfo8BTJOpUO/%F0%9F%9F%A0-HPE-Design-System-Components-(Duplicate-Test)?m=auto&node-id=38279-8&t=2Xwf00UJlRwu888C-1)

**Comment by oliverHPE** [comment]
Review of Julias feedback can be found here: https://www.figma.com/design/1oYTgR5ZxPESOBoBtOzDfi/Feedback-1?node-id=19-51&t=TSuDyLZku4FiikDr-1

**Comment by oliverHPE** [comment]
- Julia mentioned not all tokens could come from the generic `component` category, e.g. the category that holds `component.medium.spacingY` etc. We should revisit this again and decide how to categorise tokens and whether to have the component size category.
- In the test, the Tab was built using `component.medium` tokens.  however, that is for a 36px high component. While not wrong, the actual Tab is actually 46px high (should probably be 48px high), so `component.large` tokens would have been more appropriate for this size.
- In our actual tabs, the gap between text and icons is 12px, however, the textToIcon token in component size tokens is 6px. We need to think about how to address this, e.g. standardise textToIcon, or rather allow more generic spacing to be applied. For example, use `spacing.small` rather than `component.medium.textToIcon`
- It wasn't clear what vertical padding to use, again we need to decide on how to apply padding and what, if any, tokens should be used for padding.

**Comment by taysea** [comment]
Closing issue as done, can file any follow on work as new ticket
