### ISSUE TITLE
Notification - Phase 2 - Build

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4243]
Working in the v2 library apply tokens to the notification component.

https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2168-1437

- [ ] Create branch specific to this issue
- [ ] Replace existing styles with tokens
- [ ] Note any missing tokens or unused tokens related to state

**Comment by luketa8** [comment]
Updated three [notifications components](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2168-1437&node-type=canvas&t=FE13BcdYNP0KLx83-0) with Tokens and added a few observations:

![image](https://github.com/user-attachments/assets/c07e360c-3dc9-4d36-8644-308b8d65a17b)
### Not sure what the (1) means. It appeared when I added the underline decoration to the anchor.medium Token


![image](https://github.com/user-attachments/assets/e4f874ab-fe9f-4439-b239-a19c3a9358e1)

### I modify this Fill but it keeps going back to Light/Text. Is this a Figma bug due to having multiple styles in the same layer?

**Comment by luketa8** [comment]
Components ready for review [here](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2168-1437)

**Comment by julauxen** [comment]
Review is split into the following issues:
#4302 
#4303 
#4304
