### ISSUE TITLE
Switch-control - Phase 2 - Build

### ISSUE THREAD

**Issue by SeamusLeonardHPE** [grommet/hpe-design-system#4265]
Create and tokensise an atomic component for the checkbox-toggle switch variant.

Consider all states in the image below (may not be comprehensive) and all tokens available.

![image](https://github.com/user-attachments/assets/4accb2a4-55db-43b4-95c1-1e739c9794d3)

Build "control only' atom

**Comment by CillianHPE** [comment]
The switch control is currently blocked due to visual issues from the current set of tokens.

The issues are as follows
- Overlapping borders 
- Transparent backgrounds cause issues when the drop shadow effect gets added.

Also there's component specific tokens for everything except the drop shadow. I believe we should have tokens specific for this.


<img width="658" alt="image" src="https://github.com/user-attachments/assets/e125dfe7-875d-4cc7-b865-5df9949cfa4a">

**Comment by SeamusLeonardHPE** [comment]
Tokens updated:
https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/v2-Construction-Site?node-id=2504-2477&t=5Ksr1p4FkN5XDrpO-4


![Image](https://github.com/user-attachments/assets/77673f49-b41c-4104-a589-f9ad0f1c2051)

**Comment by CillianHPE** [comment]
**Links to Review** 
[Tokens](https://github.com/grommet/hpe-design-system/issues/4423)
[Figma Build](https://github.com/grommet/hpe-design-system/issues/4424)
[Code Parity](https://github.com/grommet/hpe-design-system/issues/4425)
