### ISSUE TITLE
NOTIFICATION - Code parity

### ISSUE THREAD

**Issue by julauxen** [grommet/hpe-design-system#4303]
Branch: https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/branch/mO02iMASrrXu9aYmO6nXIW/v2-Construction-Site?m=auto&node-id=2168-1437&t=jh11zVPuF98gg8Wh-1

**Comment by luketa8** [comment]
All Updates made to [Figma file](https://www.figma.com/design/5NUO23O2mDjiulO2H0S2Os/branch/mO02iMASrrXu9aYmO6nXIW/v2-Construction-Site?node-id=2168-1437&node-type=canvas&t=auMXoLjFqy0LKhEQ-0)


- Fixed layer and prop naming
- Fixed missing properties
- Fixed color tokens for dark mode
- Added a couple of comments

**Comment by luketa8** [comment]
Hey @britt6612 , added you for a code parity review. Here's the [Figma frame](https://www.figma.com/design/mO02iMASrrXu9aYmO6nXIW/%234243-NOTIFICATION-REVIEW-(Julia)?node-id=2976-6266&t=sOf1KNfXHltG7xWp-4) for the code parity review. Thanks!

**Comment by britt6612** [comment]
@julauxen @luketa8 

## Notification
	
Toast Notifications
- Should Close button be an option? 
- not able to edit text for title or message

Global notifications:
-    Im not able to change the message or title?
-    Link?
-    Close button? Optional? 

Warning:
-  does not look correct in light mode

Critical
- dark background not showing canvas background does not change 

Inline Notifications
- Should Link be an option?
- Should Close button be an option? 
- Not able to change title or message

Normal 
- light mode doesn’t seem to be working
- is dark mode correct

Warning:
 - light mode doesn’t seem to be working
 
Critical:
- Dark mode doesn’t seem to be working

Form validation:
- doesn’t look correct in either dark/light mode

**Comment by luketa8** [comment]
- Light / Mode issues are due to Figma Dev mode not changing background automatically  and notifications using transparent color tokens. 

> Should Link be an option?

- Link has to be part of the Message text layer to recreate the same text wrap as in code. Figma has only `display: block;` and `display: flex;` type behavior. Therefore, there is no way te set up a Link boolean. 

> Should Close button be an option?

- Good catch, it became detached when updating the close button component. Fixed in all 3 components

> Not able to change title or message.

- Title and message are to be updated directly in the text layer. We didn't build in any text properties because it would reset the message/link font styling, leading to a bad user experience for the designer.

**Comment by britt6612** [comment]
@luketa8 thank you for addressing looks good and agree on the points with the `title` and `linik`

**Comment by luketa8** [comment]
Ok, thanks!

- Moving review to done. 
- Outstanding paragraph wrap issue solved and created [Dev issue ](https://github.com/grommet/hpe-design-system/issues/4407)to replicate in code.
