### ISSUE TITLE
Code Block component: Fix color token used in comments

### ISSUE THREAD

**Issue by luketa8** [grommet/hpe-design-system#4359]
### Link to problem

https://deploy-preview-4353--unrivaled-bublanina-3a9bae.netlify.app/?path=/story/code-blocks--code-block

### Current problem

[Code Blocks](https://design-system.hpe.design/templates/code-blocks?q=code)

Comments in code are not passing the WCAG AAA required contrast ratio of 4.5:1.
Current contrast ratio -> 4.23:1 
#008567 foreground
#F5F5F5 background

### Steps 
- Select a new color token and apply in code.

**Comment by jcfilben** [comment]
Reminder: Connect with Taylor on this

**Comment by luketa8** [comment]
- [ ] Checked dark mode, current contrast ratio is 13.42:1, no change needed. 

My proposal is to use this token: `base/color/green/800` for comments in code

- Meets AA and AAA contrast ratios 6.3

![image](https://github.com/user-attachments/assets/27cd6d7c-10da-4722-b13f-62bfc9a58d96)

More info in [Figma file](https://www.figma.com/design/pE55XqhCp27fAxWfDqvrOe/4359---Contrast?node-id=2-3&t=2FjJ7GmvD0OStPRO-4)

Tagging @taysea for review.

**Comment by taysea** [comment]
Thanks Lucas, this seems like a reasonable adjustment that stays true to the original style. Let's use a semantic token here instead of the "base" value. I adjusted the value of text/primary to use "green/800" (this is in alignment with what would be coming with the theme update).

@jcfilben Let's move forward with that hex value (#006750).

**Comment by jcfilben** [comment]
Perfect, just put up a PR for this change https://github.com/grommet/grommet-theme-hpe/pull/418
