### ISSUE TITLE
Search removed on click

### ISSUE THREAD

**Issue by gregfuruiye** [grommet/hpe-design-system#774]
### Is this issue related to the design system core library or design system website?

design-system-website

### Expected Behavior

When clicking in search, then scrolling at possible items, when I click again in the search field I should still be able to input text

### Actual Behavior
When clicking in search, then scrolling at options, when I click back into the search input the field closes.

### Steps to Reproduce

1. Click to search 2. Scroll to possible items 3. Click in the search field

### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by taysea** [comment]
Hey Greg, the reason this is happening it because we are using `onSuggestionsClose` (which tracks when the suggestions close) to know when to collapse the search input. When you click back on the input, it's closing the suggestions and then closing the text input.

However, as you scroll down through the options, the textinput is still in focus so you can just start typing without clicking into it again. However, I do think that clicking back into the text input could be a natural behavior, so we'll want to explore a fix here.

**Comment by jcfilben** [comment]
Closing, the search on the design system site has changed since this issue was filed and this is no longer an issue.
