### ISSUE TITLE
Categorize GLC guidance requests

### ISSUE THREAD

**Issue by halocline** [grommet/hpe-design-system#793]
### Deliverables
- [ ] separate issues for items mentioned below as needed

--

Capturing from Slack: https://hpe.slack.com/archives/GPPLUK6LR/p1589926704066600?thread_ts=1589822903.006300&cid=GPPLUK6LR

Cheri Herndon  6 minutes ago
Along these lines, in our recent GLC Design Review meetings, we've been having discussions that include a desire for DS guidance on the following types of pages:

Cheri Herndon  6 minutes ago
Detail View for selected object

Cheri Herndon  6 minutes ago
Add/Create

Cheri Herndon  6 minutes ago
Edit/Update

Cheri Herndon  6 minutes ago
Delete, including force delete

Cheri Herndon  5 minutes ago
Also, Filtering examples

Cheri Herndon  5 minutes ago
I think Edgar wants to talk about some of these in our upcoming DS/GLC Design meeting

**Comment by cherih** [comment]
@halocline - Thank you for creating an issue for this Matt!

**Comment by halocline** [comment]
> @halocline - Thank you for creating an issue for this Matt!

Of course. Anytime.

**Comment by saggiemilva** [comment]
I had a meeting with Jens about some additional aspects that he though would be helpful to consider for the design system:

- How to format a text heavy pages such as a privacy policy, large text documents, or detail page. Example: https://client.greenlake.hpe.com/trial-terms

- GLC is required to only show forms from a side layer which can be challenging since they have longer forms that require scrolling. We were asked to help give some examples or guidance for this.

- Asked to add t-shirt sizing options to Figma components to allow for creating responsive designs for all screens

- Recommended adding a page to the design site about creating responsive designs and helping define breakpoints.

**Comment by halocline** [comment]
> * How to format a text heavy pages such as a privacy policy, large text documents, or detail page. Example: https://client.greenlake.hpe.com/trial-terms

For long, text heavy pages, some areas we might want to provide guidance:
- Line length (number of characters per line) in relation to trackability/maintaining position
- Table of contents / index tracking that aligns with section headings and visually indicates where I am in relation to that index -- paired with navigation (e.g. expanded sidebar nav - [as described in 1.ii.c here](https://github.com/hpe-design/design-system/pull/528#issuecomment-600376752))
- Use of scroll-to-top when pages exceed a certain length

**Comment by ericsoderberghp** [comment]
Either already addressed or will allow new issues to be raised
