### ISSUE TITLE
Document releases/updates to add transparency. "Whats new"

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-design-system#822]
GL Product Owners have asked for a mechanism to better understand whats been updated or new for the Design System. 

Considerations:
- How does this fit into a continuous delivery model 
- How can we show alignment between WIP and the roadmap. (Work to be completed, work in progress, completed work) 
- Can this be automated in order to reduce overhead? Is it worth it?

**Comment by ShimiSun** [comment]
In order for this to work on the dev side, we will need to find a solution for this type of version's transparency on the grommet side as well.

**Comment by vavalos5** [comment]
I'm wondering if there's an easy way for this page to be editable without having the developers to edit the "WIP" section on a weekly basis. Would we be able to build the page in Grommet? If we do build it in Grommet, is it easy to access/change things?

**Comment by ericsoderberghp** [comment]
We could consider having a Markdown page that anyone could edit directly in GitHub and that the site could then render using Grommet.

**Comment by MikeWalrath** [comment]
@vavalos5 @taysea created an easy way to update content on the site (Taylor you'll have to help me with the acronym). You might have a quick discussion with her but I think that would be the easiest way to update the page without digging into dynamic content.

**Comment by vavalos5** [comment]
Oooh, exciting!! I imagine we build the design in Figma first and then once we have a solid idea, we start building in Grommet? 🤔 

i did see Carbon using an application called zenhub that is integrated with GitHub.I've added a screen shot below. I'll peep through a few of these to see how they're being designed and implemented.
![Screen Shot 2020-11-30 at 10 58 16 AM](https://user-images.githubusercontent.com/62117454/100651991-255d8c80-32fb-11eb-9ac2-50182948cc09.png)

**Comment by vavalos5** [comment]
Design blocked. To be continued week after the next.

Figma file: https://www.figma.com/file/ZF49kIemstIfIiAul0rvWj/What-s-New-Page?node-id=0%3A1

**Comment by vavalos5** [comment]
Going to put this into "in review' to see if I get any other comments but will continue to work on it.

https://www.figma.com/file/ZF49kIemstIfIiAul0rvWj/What-s-New-Page?node-id=0%3A1

**Comment by vavalos5** [comment]
Chatted with Chris today, here is what we chatted about on the "what's new page"

Started off with what is a "what's new page" and what do people do on here?

While speaking with Chris, we discussed whether creating this page to be like a social media feed is necessary. We feel it isn’t as people really are coming to this page to quickly scan what’s new and what’s happening.

if we want to include a social aspect to this ,we can add new components, etc.. to a Twitter account of whatever social thread we use.

We feel this should be more of a text-format rather than including imagery as that itself could be time consuming. Many other “what’s new” pages are text-format based.

If people have questions, we can have some type of social thread?

We could create out home page to be more of a marketing page: like material:
Header, banner, cards, what’s new, video, contact us, footer

----------------------------------------------------------------------------------------

My thought are that we keep this page very simple. After doing some researching of other "what's new" pages, they all seem to keep it minimal with no imagery. People wants to go on here to quickly see what's new and perhaps find that new feature, guidance etc.. that they've been looking for. Adding imagery can take up more of the page, make it longer and would also be adding more to our plate to create these visuals each time we update this page.

**Comment by MikeWalrath** [comment]
Sounds good @vavalos5 thanks for adding your thoughts. Im happy and agree with the approach above. I think we might be able to close this issue and start looking at the next steps for implementation. Have a great holiday ahead! Nice work.

**Comment by ericsoderberghp** [comment]
So, I think we're going with "Desktop - 25" for the What's New page itself. This work will be covered by https://github.com/grommet/hpe-design-system/issues/1335.

For the home page, I see a couple of new sections in the Figma file. I think we should work on a home page refresh separately, and include the new promo video as well. This work will be covered by https://github.com/grommet/hpe-design-system/issues/1336.
